### ISSUE TITLE
Unable to create new admin account due to invalid password. Improve error message

### ISSUE THREAD

**Issue by mbedded** [overleaf/overleaf#1033]
## Steps to Reproduce

1. Using the toolkit as described here: https://github.com/overleaf/toolkit/blob/master/doc/quick-start-guide.md
2. `bin/up`
3. open: http://localhost/launchpad
4. Insert email: `dummy@example.de`
5. Insert password: `dummy` => Here I get an error
6. Change password to `dummy123` => It works

## Expected Behaviour

- The website should specify the error like "password does not match requirements (must contain ...)"
- Any password should work
- Not working examples:
```
dummy
Gk#odoi+3-q;xVrZJc?+
g{O%s#`-le:{:O.}!9Tl8Ja8,c(#OfZ2_`_h(@`{U_-lr;F+}0
```

## Observed Behaviour

I get an general error message where I am not able to identify the cause of the error. In my case: The password didn't match the requirements. It seems only a-Z and 0-9 are allowed.

![2022-07-08 09-11-33](https://user-images.githubusercontent.com/22235508/177938438-9f712ddf-dcfb-4974-a25e-bb1cc13f42bb.png)

## Context

I tried to start the application locally (self hosted) for the first time and create the first (admin) account via /launchpad

## Technical Info

* URL: http://localhost/launchpad
* Browser Name and version: Brave [Version 1.40.107 Chromium: 103.0.5060.53 (Official Build) (64-bit)](https://brave.com/latest/)
* Operating System and version (desktop or mobile): Linux Mint 20.3 Cinnamon

## Analysis

```
bin/logs -f web

{"name":"web","hostname":"a1c109f039dc","pid":139,"level":50,"err":{"message":"request is not valid","name":"Error","stack":"Error: request is not valid\n    at Object.registerNewUser (/overleaf/services/web/app/src/Features/User/UserRegistrationHandler.js:47:23)\n    at /overleaf/services/web/modules/launchpad/app/src/LaunchpadController.js:229:38\n    at /overleaf/services/web/modules/launchpad/app/src/LaunchpadController.js:99:16\n    at /overleaf/libraries/metrics/timeAsyncMethod.js:82:25\n    at /overleaf/services/web/node_modules/mongodb/lib/utils.js:704:5\n    at executeCallback (/overleaf/services/web/node_modules/mongodb/lib/operations/execute_operation.js:65:7)\n    at handleCallback (/overleaf/services/web/node_modules/mongodb/lib/utils.js:109:55)\n    at /overleaf/services/web/node_modules/mongodb/lib/operations/find_one.js:31:9\n    at /overleaf/services/web/node_modules/mongodb/lib/utils.js:704:5\n    at /overleaf/services/web/node_modules/mongodb/lib/cursor.js:252:9\n    at /overleaf/services/web/node_modules/mongodb/lib/core/cursor.js:746:9\n    at handleCallback (/overleaf/services/web/node_modules/mongodb/lib/core/cursor.js:32:5)\n    at /overleaf/services/web/node_modules/mongodb/lib/core/cursor.js:690:38\n    at Cursor._endSession (/overleaf/services/web/node_modules/mongodb/lib/core/cursor.js:404:7)\n    at _setCursorNotifiedImpl (/overleaf/services/web/node_modules/mongodb/lib/core/cursor.js:699:10)\n    at setCursorNotified (/overleaf/services/web/node_modules/mongodb/lib/core/cursor.js:690:3)\n    at done (/overleaf/services/web/node_modules/mongodb/lib/core/cursor.js:465:16)\n    at queryCallback (/overleaf/services/web/node_modules/mongodb/lib/core/cursor.js:510:20)\n    at /overleaf/services/web/node_modules/mongodb/lib/core/cursor.js:555:9\n    at /overleaf/services/web/node_modules/mongodb/lib/utils.js:704:5\n    at executeCallback (/overleaf/services/web/node_modules/mongodb/lib/operations/execute_operation.js:65:7)\n    at callbackWithRetry (/overleaf/services/web/node_modules/mongodb/lib/operations/execute_operation.js:112:14)","info":{}},"url":"/launchpad/register_admin","method":"POST","user":null,"msg":"error passed to top level next middleware","time":"2022-07-08T07:10:21.562Z","v":0}
{"name":"web","hostname":"a1c109f039dc","pid":139,"level":30,"req":{"method":"POST","url":"/launchpad/register_admin","remoteAddress":"127.0.0.1","headers":{"referer":"http://localhost/launchpad","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36","content-length":"94"}},"res":{"statusCode":500,"headers":{"content-length":"762"}},"responseTimeMs":40,"msg":"POST /launchpad/register_admin","time":"2022-07-08T07:10:21.582Z","v":0}
{"name":"web","hostname":"a1c109f039dc","pid":139,"level":30,"rss":"128.49","heapTotal":"76.38","heapUsed":"71.19","external":"19.66","arrayBuffers":"17.87","msg":"process.memoryUsage()","time":"2022-07-08T07:11:09.332Z","v":0}
```

**Comment by das7pad** [comment]
Hello,

Thanks for the report. We fixed this back in 2022 (released with 3.4.x), but missed to get back to you. This is what I get with the latest version (5.1.1):

![image](https://github.com/user-attachments/assets/43bf8e70-c822-4999-b9ad-ac31b4ee4926)


Greetings,
Jakob
