### ISSUE TITLE
error mongo with 2.7.1

### ISSUE THREAD

**Issue by wixaw** [overleaf/overleaf#1041]
Hello
We have this error when project compiles on error

```
{"name":"web","hostname":"d1b696a1f6eb","pid":148,"level":40,"error":{"code":"ESOCKETTIMEDOUT","connect":false},"projectId":"626283703729f3008e26ba11","msg":"error making request to document updater","time":"2022-08-17T12:02:18.459Z","v":0}
{"name":"web","hostname":"d1b696a1f6eb","pid":148,"level":50,"err":{"message":"ESOCKETTIMEDOUT","name":"Error","stack":"Error: ESOCKETTIMEDOUT\n    at ClientRequest.<anonymous> (/var/www/sharelatex/web/node_modules/request/request.js:816:19)\n    at Object.onceWrapper (events.js:420:28)\n    at ClientRequest.emit (events.js:314:20)\n    at ClientRequest.EventEmitter.emit (domain.js:483:12)\n    at Socket.emitRequestTimeout (_http_client.js:715:9)\n    at Object.onceWrapper (events.js:420:28)\n    at Socket.emit (events.js:326:22)\n    at Socket.EventEmitter.emit (domain.js:483:12)\n    at Socket._onTimeout (net.js:483:8)\n    at listOnTimeout (internal/timers.js:554:17)\n    at processTimers (internal/timers.js:497:7)\nTaggedError: failed to flush project to Mongo\n    at /var/www/sharelatex/web/app/src/Features/Compile/ClsiManager.js:730:18\n    at Request._callback (/var/www/sharelatex/web/app/src/Features/DocumentUpdater/DocumentUpdaterHandler.js:310:9)\n    at self.callback (/var/www/sharelatex/web/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:314:20)\n    at Request.EventEmitter.emit (domain.js:483:12)\n    at ClientRequest.<anonymous> (/var/www/sharelatex/web/node_modules/request/request.js:819:16)\n    at Object.onceWrapper (events.js:420:28)\n    at ClientRequest.emit (events.js:314:20)\n    at ClientRequest.EventEmitter.emit (domain.js:483:12)\n    at Socket.emitRequestTimeout (_http_client.js:715:9)\n    at Object.onceWrapper (events.js:420:28)\n    at Socket.emit (events.js:326:22)\n    at Socket.EventEmitter.emit (domain.js:483:12)\n    at Socket._onTimeout (net.js:483:8)\n    at listOnTimeout (internal/timers.js:554:17)\n    at processTimers (internal/timers.js:497:7)\nTaggedError: failed to get contents from Mongo\n    at /var/www/sharelatex/web/app/src/Features/Compile/ClsiManager.js:586:24\n    at /var/www/sharelatex/web/app/src/Features/Compile/ClsiManager.js:729:16\n    at Request._callback (/var/www/sharelatex/web/app/src/Features/DocumentUpdater/DocumentUpdaterHandler.js:310:9)\n    at self.callback (/var/www/sharelatex/web/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:314:20)\n    at Request.EventEmitter.emit (domain.js:483:12)\n    at ClientRequest.<anonymous> (/var/www/sharelatex/web/node_modules/request/request.js:819:16)\n    at Object.onceWrapper (events.js:420:28)\n    at ClientRequest.emit (events.js:314:20)\n    at ClientRequest.EventEmitter.emit (domain.js:483:12)\n    at Socket.emitRequestTimeout (_http_client.js:715:9)\n    at Object.onceWrapper (events.js:420:28)\n    at Socket.emit (events.js:326:22)\n    at Socket.EventEmitter.emit (domain.js:483:12)\n    at Socket._onTimeout (net.js:483:8)\n    at listOnTimeout (internal/timers.js:554:17)\n    at processTimers (internal/timers.js:497:7)\nTaggedError: Could not build request to CLSI\n    at /var/www/sharelatex/web/app/src/Features/Compile/ClsiManager.js:73:20\n    at /var/www/sharelatex/web/app/src/Features/Compile/ClsiManager.js:585:22\n    at /var/www/sharelatex/web/app/src/Features/Compile/ClsiManager.js:729:16\n    at Request._callback (/var/www/sharelatex/web/app/src/Features/DocumentUpdater/DocumentUpdaterHandler.js:310:9)\n    at self.callback (/var/www/sharelatex/web/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:314:20)\n    at Request.EventEmitter.emit (domain.js:483:12)\n    at ClientRequest.<anonymous> (/var/www/sharelatex/web/node_modules/request/request.js:819:16)\n    at Object.onceWrapper (events.js:420:28)\n    at ClientRequest.emit (events.js:314:20)\n    at ClientRequest.EventEmitter.emit (domain.js:483:12)\n    at Socket.emitRequestTimeout (_http_client.js:715:9)\n    at Object.onceWrapper (events.js:420:28)\n    at Socket.emit (events.js:326:22)\n    at Socket.EventEmitter.emit (domain.js:483:12)\n    at Socket._onTimeout (net.js:483:8)\n    at listOnTimeout (internal/timers.js:554:17)\n    at processTimers 
```
sharelatex 2.7.1
mongo 4.0
redis 5
docker-compose 
We can't upgrade for moment, you have an idea to fix this ? 
Thanks you in advance

**Comment by wixaw** [comment]
fix with upgrade
