### ISSUE TITLE
Create-user script fails

### ISSUE THREAD

**Issue by chschenk** [overleaf/overleaf#1084]
## Steps to Reproduce

1. Run `./bin/shell sharelatex`
2. Change into the script directory `cd /overleaf/services/web/modules/server-ce-scripts/scripts`
3. Create user with node command `node create-user --email=email@example.com`

## Expected Behaviour
A User should be created and a mail with an activation URL should be sent to email@example.com

## Observed Behaviour
The command fails with a stacktrace
```
Set UV_THREADPOOL_SIZE=16
Using settings from /etc/sharelatex/settings.js
/overleaf/services/web/app/src/Features/V1/V1Api.js:17
  baseUrl: settings.apis.v1.url,
                            ^

TypeError: Cannot read properties of undefined (reading 'url')
    at Object.<anonymous> (/overleaf/services/web/app/src/Features/V1/V1Api.js:17:29)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/overleaf/services/web/app/src/Features/TokenGenerator/TokenGenerator.js:14:15)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/overleaf/services/web/app/src/models/User.js:3:24)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
```

## Context
I'm trying to create a user via command line

## Technical Info
N/A

**Comment by Ezimkin** [comment]
I had a similar issue and think I may have found a solution. Make sure to `cd /overleaf/services/web` and **then** run the scripts like shown in the grunt wrapper.
https://github.com/overleaf/overleaf/blob/main/server-ce/bin/grunt

**Comment by das7pad** [comment]
Hello,

Indeed, the `create-user` script must be invoked from the `/overleaf/services/web` folder.

Greetings,
Jakob
