### ISSUE TITLE
Overleaf CE 3.5.0 - Full Project History migration

### ISSUE THREAD

**Issue by mserranom** [overleaf/overleaf#1087]
The `3.5.0` release of Overleaf Community Edition includes the [Full Project History feature](https://www.overleaf.com/learn/latex/Using_the_History_feature) that is already available in our SaaS offering, [overleaf.com](http://overleaf.com/) 

The new Full Project History brings several improvements for users:
- It tracks changes in binary files, which is unsupported in the legacy system.
- There is support for labelled versions.
- The system is in general more robust, there is less chance of data loss.

[Check the instructions to migrate your existing projects to Full Project History](https://github.com/overleaf/overleaf/wiki/Full-Project-History-Migration)

**Comment by wixaw** [comment]
Hi,
I have 76 errors on 6000 project, I sent you a report =)

**Comment by maksimatveev** [comment]
@mserranom Hello! I needed to install Overleaf CE 2.4.1 on my own server due to the peculiarities of one package used, which only works correctly with TeX Live 2020.
Question: the message "no_history_available" when you click on the "History" button is it because of the low version Overleaf CE 2.4.1?

**Comment by holyfive** [comment]
After upgrading to the latest version I keep getting these errors:

Migrate "20230512100122_ensure_history_migration"
Error: Error during migrate "20230512100122_ensure_history_migration": Found 923 projects not migrated to Full Project History
at exports.migrate (/overleaf/services/web/migrations/20230512100122_ensure_history_migration.js:9:11)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async /overleaf/node_modules/p-map/index.js:57:22
npm ERR! Lifecycle script `migrations` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: @overleaf/web
npm ERR!   at location: /overleaf/services/web
*** /etc/my_init.d/99_run_web_migrations.sh failed with status 1
*** Killing all processes...

The container keeps restarting, so it is not even possible to try any migration command or something else. I had to downgrade the image. 

Is that a known issue and how can it be solved?

**Comment by mserranom** [comment]
> The container keeps restarting, so it is not even possible to try any migration command or something else. I had to downgrade the image.
> Is that a known issue and how can it be solved?

You need to perform the migration using version 3.5.x (latest is `3.5.13`). Only after all the projects are migrated you can update to `4.x`.

Check instructions in https://github.com/overleaf/overleaf/wiki/Full-Project-History-Migration

**Comment by holyfive** [comment]
Thanks a lot. Perhaps you should add a hint to the documentation that 3.5.x is needed as an intermediate step when using the "latest" tag.
