### ISSUE TITLE
Similar issue to https://github.com/overleaf/overleaf/issues/1082

### ISSUE THREAD

**Issue by maestro1315** [overleaf/overleaf#1109]
1. clone toolkit folder
2. bin/init
3. configure TLS/NGINX
4. /bin/up
5. log in and create first user account
6. create project

below error - 
![image](https://user-images.githubusercontent.com/105432585/230472456-7e885a72-34fc-4d3b-b4eb-7aff74f73691.png)

expected - create the first project

error in log - 
Using default settings from /overleaf/services/web/config/settings.defaults.js
Using settings from /etc/sharelatex/settings.js
{"name":"web","hostname":"853089dcf1f2","pid":147,"level":40,"msg":"Email transport and/or parameters not defined. No emails will be sent.","time":"2023-04-06T16:28:49.181Z","v":0}
{"name":"web","hostname":"853089dcf1f2","pid":147,"level":50,"err":{"message":"failed to initialize project history","name":"OError","stack":"OError: failed to initialize project history\n at Object.initializeProject (/overleaf/services/web/app/src/Features/History/HistoryManager.js:25:11)\n at processTicksAndRejections (node:internal/process/task_queues:96:5)\n at async _createBlankProject (/overleaf/services/web/app/src/Features/Project/ProjectCreationHandler.js:164:23)\n at async Object.createBasicProject (/overleaf/services/web/app/src/Features/Project/ProjectCreationHandler.js:84:19)","info":{"statusCode":500}},"url":"/project/new","method":"POST","user":{"id":"642eee910c1c980093b1c954","email":"

**Comment by mserranom** [comment]
Would you mind sharing also `project-history.log` and `history-v1.log`?
