### ISSUE TITLE
Running locally without docker container

### ISSUE THREAD

**Issue by zeakey** [overleaf/overleaf#1128]
I'm trying to setup the services locally without docker container because I'm familiar with developing and debugging with a native environment.

## Steps to Reproduce
I first copied the source code from the container (`/overleaf` folder in the `sharelatex` container) and tried to reproduce the web service in my local environment by running: `node services/web/app.js`.

## Expected Behaviour
I was expected to be able to visit the service in my browser.

## Observed Behaviour
I visited my browser but it gives me this:
![image](https://github.com/overleaf/overleaf/assets/6763078/611ad069-b629-4a33-982f-e402a6b50977)

And I got error message in the terminal running `node services/web/app.js`:
```
{"name":"web","hostname":"XXX","pid":1083753,"level":20,"responseTimeMs":8,"req":{"method":"GET","url":"/undefined","remoteAddress":"10.147.20.223","headers":{"referer":"http://10.147.20.102:3000/login","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.43"}},"res":{"statusCode":302,"headers":{"content-length":"28"}},"msg":"GET /undefined","time":"2023-06-27T19:36:53.084Z","v":0}
{"name":"web","hostname":"XXX","pid":1083753,"level":50,"err":{"message":"/media/hdd1/Code/overleaf/from-containers/sharelatex/overleaf/services/web/app/views/layout-base.pug:18\n    16| \t\tlink(rel='stylesheet', href=buildCssPath(getCssThemeModifier(userSettings, brandVariation)), id=\"main-stylesheet\")\n    17| \t\tblock css\n  > 18| \t\t\teach file in entrypointStyles(entrypoint)\n    19| \t\t\t\tlink(rel='stylesheet', href=file)\n    20| \n    21| \t\tblock _headLinks\n\nCannot read properties of undefined (reading 'marketing')","name":"TypeError","stack":"TypeError: /media/hdd1/Code/overleaf/from-containers/sharelatex/overleaf/services/web/app/views/layout-base.pug:18\n    16| \t\tlink(rel='stylesheet', href=buildCssPath(getCssThemeModifier(userSettings, brandVariation)), id=\"main-stylesheet\")\n    17| \t\tblock css\n  > 18| \t\t\teach file in entrypointStyles(entrypoint)\n    19| \t\t\t\tlink(rel='stylesheet', href=file)\n    20| \n    21| \t\tblock _headLinks\n\nCannot read properties of undefined (reading 'marketing')\n    at getWebpackAssets (/media/hdd1/Code/overleaf/from-containers/sharelatex/overleaf/services/web/app/src/infrastructure/ExpressLocals.js:78:37)\n    at res.locals.entrypointStyles (/media/hdd1/Code/overleaf/from-containers/sharelatex/overleaf/services/web/app/src/infrastructure/ExpressLocals.js:180:22)\n    at eval (eval at wrap (/media/hdd1/Code/overleaf/from-containers/sharelatex/overleaf/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:256:15)\n    at eval (eval at wrap (/media/hdd1/Code/overleaf/from-containers/sharelatex/overleaf/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:272:4)\n    at template (eval at wrap (/media/hdd1/Code/overleaf/from-containers/sharelatex/overleaf/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:1653:7)\n    at Object.exports.renderFile (/media/hdd1/Code/overleaf/from-containers/sharelatex/overleaf/node_modules/pug/lib/index.js:454:38)\n    at Object.exports.renderFile (/media/hdd1/Code/overleaf/from-containers/sharelatex/overleaf/node_modules/pug/lib/index.js:444:21)\n    at View.exports.__express [as engine] (/media/hdd1/Code/overleaf/from-containers/sharelatex/overleaf/node_modules/pug/lib/index.js:493:11)\n    at View.render (/media/hdd1/Code/overleaf/from-containers/sharelatex/overleaf/node_modules/express/lib/view.js:135:8)\n    at tryRender (/media/hdd1/Code/overleaf/from-containers/sharelatex/overleaf/node_modules/express/lib/application.js:657:10)\n    at Function.render (/media/hdd1/Code/overleaf/from-containers/sharelatex/overleaf/node_modules/express/lib/application.js:609:3)\n    at ServerResponse.render (/media/hdd1/Code/overleaf/from-containers/sharelatex/overleaf/node_modules/express/lib/response.js:1039:7)\n    at loginPage (/media/hdd1/Code/overleaf/from-containers/sharelatex/overleaf/services/web/app/src/Features/User/UserPagesController.js:160:9)\n    at Layer.handle [as handle_request] (/media/hdd1/Code/overleaf/from-containers/sharelatex/overleaf/node_modules/express/lib/router/layer.js:95:5)\n    at next (/media/hdd1/Code/overleaf/from-containers/sharelatex/overleaf/node_modules/express/lib/router/route.js:144:13)\n    at Route.dispatch (/media/hdd1/Code/overleaf/from-containers/sharelatex/overleaf/node_modules/express/lib/router/route.js:114:3)","info":{}},"url":"/login","method":"GET","user":null,"msg":"error passed to top level next middleware","time":"2023-06-27T19:36:53.306Z","v":0}
```

## Context
I speculated that this could be possibly due to other services (e.g. `services/clsi`, `services/filestore`) are not running. Then I tried to running other services, but the problem till persists.

Is there any way of running a local web service without containers?

**Comment by logesh810** [comment]
Hi @zeakey I also tried this way in Windows   I am getting errors like this "throw new Error('No API user and password provided')" and I can't see any files like this overleaf/public/manifest.json in container can you help me?

**Comment by mderycke22** [comment]
https://github.com/overleaf/overleaf/issues/1018#issuecomment-3179761569
