### ISSUE TITLE
east-migrate error: Error during migrate (...) not migrated to Full Project History

### ISSUE THREAD

**Issue by rpmcruz** [overleaf/overleaf#1134]
I did an upgrade from overleaf 3.25.1 (I think) to the latest (4.0.5) using `bin/upgrade`.

Unfortunately, I am getting the following error on `bin/up`. The sharelatex container keeps giving this error and restarting.

```
sharelatex    | Mongodb is up.
mongo         | {"t":{"$date":"2023-07-21T13:56:59.098+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn32","msg":"Connection ended","attr":{"remote":"172.18.0.4:38146","connectionId":32,"connectionCount":4}}
mongo         | {"t":{"$date":"2023-07-21T13:56:59.098+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn31","msg":"Connection ended","attr":{"remote":"172.18.0.4:38138","connectionId":31,"connectionCount":3}}
sharelatex    | Using default settings from /overleaf/services/web/config/settings.defaults.js
sharelatex    | Using settings from /etc/sharelatex/settings.js
sharelatex    | Set UV_THREADPOOL_SIZE=16
sharelatex    | Redis is up.
sharelatex    | All checks passed
sharelatex    | *** Running /etc/my_init.d/99_run_web_migrations.sh...
sharelatex    | Running migrations for server-ce
sharelatex    | 
sharelatex    | > migrations
sharelatex    | > east migrate -t server-ce
sharelatex    | 
sharelatex    | Using default settings from /overleaf/services/web/config/settings.defaults.js
sharelatex    | Using settings from /etc/sharelatex/settings.js
sharelatex    | Set UV_THREADPOOL_SIZE=16
mongo         | {"t":{"$date":"2023-07-21T13:56:59.842+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.18.0.4:38150","connectionId":33,"connectionCount":4}}
mongo         | {"t":{"$date":"2023-07-21T13:56:59.846+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn33","msg":"client metadata","attr":{"remote":"172.18.0.4:38150","client":"conn33","doc":{"driver":{"name":"nodejs|Mongoose","version":"4.13.0"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"5.15.0-76-generic"},"platform":"Node.js v16.20.1, LE (unified)","version":"4.13.0|6.9.1","application":{"name":"web"}}}}
mongo         | {"t":{"$date":"2023-07-21T13:56:59.857+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.18.0.4:38160","connectionId":34,"connectionCount":5}}
mongo         | {"t":{"$date":"2023-07-21T13:56:59.858+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn34","msg":"client metadata","attr":{"remote":"172.18.0.4:38160","client":"conn34","doc":{"driver":{"name":"nodejs|Mongoose","version":"4.13.0"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"5.15.0-76-generic"},"platform":"Node.js v16.20.1, LE (unified)","version":"4.13.0|6.9.1","application":{"name":"web"}}}}
mongo         | {"t":{"$date":"2023-07-21T13:56:59.985+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.18.0.4:38172","connectionId":35,"connectionCount":6}}
mongo         | {"t":{"$date":"2023-07-21T13:56:59.987+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn35","msg":"client metadata","attr":{"remote":"172.18.0.4:38172","client":"conn35","doc":{"driver":{"name":"nodejs|Mongoose","version":"4.13.0"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"5.15.0-76-generic"},"platform":"Node.js v16.20.1, LE (unified)","version":"4.13.0|6.9.1","application":{"name":"web"}}}}
sharelatex    | Target migrations:
sharelatex    | 	20230512100122_ensure_history_migration
sharelatex    | Migrate "20230512100122_ensure_history_migration"
sharelatex    | Error: Error during migrate "20230512100122_ensure_history_migration": Found 32 projects not migrated to Full Project History
sharelatex    |     at exports.migrate (/overleaf/services/web/migrations/20230512100122_ensure_history_migration.js:9:11)
sharelatex    |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
sharelatex    |     at async /overleaf/node_modules/p-map/index.js:57:22
mongo         | {"t":{"$date":"2023-07-21T13:57:00.000+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn35","msg":"Connection ended","attr":{"remote":"172.18.0.4:38172","connectionId":35,"connectionCount":5}}
mongo         | {"t":{"$date":"2023-07-21T13:57:00.000+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn34","msg":"Connection ended","attr":{"remote":"172.18.0.4:38160","connectionId":34,"connectionCount":4}}
mongo         | {"t":{"$date":"2023-07-21T13:57:00.000+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn33","msg":"Connection ended","attr":{"remote":"172.18.0.4:38150","connectionId":33,"connectionCount":3}}
sharelatex    | npm ERR! Lifecycle script `migrations` failed with error: 
sharelatex    | npm ERR! Error: command failed 
sharelatex    | npm ERR!   in workspace: @overleaf/web 
sharelatex    | npm ERR!   at location: /overleaf/services/web 
sharelatex    | *** /etc/my_init.d/99_run_web_migrations.sh failed with status 1
sharelatex    | 
sharelatex    | *** Killing all processes...
sharelatex    | Jul 21 13:57:00 13a4077d78df syslog-ng[61]: syslog-ng shutting down; version='3.25.1'
sharelatex exited with code 1
```

**Comment by senyai** [comment]
_Found 32 projects not migrated to Full Project History_. Have you followed https://github.com/overleaf/overleaf/wiki/Full-Project-History-Migration? If there are any history migration errors, see #1127.

**Comment by rpmcruz** [comment]
The sharelatex container was in such a state that I could not run any of those commands. Those commands require running things inside the sharelatex container (`bin/docker-compose exec sharelatex /bin/bash -c "..."`). The problem I was having (I have since downgraded) was that the sharelatex container kept restarting due to that error, therefore I could not run any commands inside the container.
