### ISSUE TITLE
sharelatex 4 - 98_check_db_access.sh failed

### ISSUE THREAD

**Issue by CrysK** [overleaf/overleaf#1141]
I running sharelatex on Ubuntu 22 in Docker.

With sharelatex version 3 I have no Issues. Everything works fine.
But I can't create a clean new sharelatex 4 or 4.1 server.

<details>
  <summary>It breaks everytime with the following</summary>
  
  ```bash
  sharelatex_mongo  | 2023-08-24T19:13:49.905356785Z {"t":{"$date":"2023-08-24T19:13:49.902+00:00"},"s":"I",  "c":"CONTROL",  "id":23285,   "ctx":"main","msg":"Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'"}
sharelatex_mongo  | 2023-08-24T19:13:49.911948156Z {"t":{"$date":"2023-08-24T19:13:49.911+00:00"},"s":"I",  "c":"NETWORK",  "id":4648601, "ctx":"main","msg":"Implicit TCP FastOpen unavailable. If TCP FastOpen is required, set tcpFastOpenServer, tcpFastOpenClient, and tcpFastOpenQueueSize."}
sharelatex_mongo  | 2023-08-24T19:13:49.914874870Z {"t":{"$date":"2023-08-24T19:13:49.913+00:00"},"s":"I",  "c":"STORAGE",  "id":4615611, "ctx":"initandlisten","msg":"MongoDB starting","attr":{"pid":1,"port":27017,"dbPath":"/data/db","architecture":"64-bit","host":"684ba92d7612"}}
sharelatex_mongo  | 2023-08-24T19:13:49.914995989Z {"t":{"$date":"2023-08-24T19:13:49.913+00:00"},"s":"I",  "c":"CONTROL",  "id":23403,   "ctx":"initandlisten","msg":"Build Info","attr":{"buildInfo":{"version":"4.4.24","gitVersion":"0b86b9b7b42ad9970c5f818c527dd86c0634243a","openSSLVersion":"OpenSSL 1.1.1f  31 Mar 2020","modules":[],"allocator":"tcmalloc","environment":{"distmod":"ubuntu2004","distarch":"x86_64","target_arch":"x86_64"}}}}
sharelatex_mongo  | 2023-08-24T19:13:49.915010938Z {"t":{"$date":"2023-08-24T19:13:49.913+00:00"},"s":"I",  "c":"CONTROL",  "id":51765,   "ctx":"initandlisten","msg":"Operating System","attr":{"os":{"name":"Ubuntu","version":"20.04"}}}
sharelatex_mongo  | 2023-08-24T19:13:49.915016802Z {"t":{"$date":"2023-08-24T19:13:49.913+00:00"},"s":"I",  "c":"CONTROL",  "id":21951,   "ctx":"initandlisten","msg":"Options set by command line","attr":{"options":{"net":{"bindIp":"*"}}}}
sharelatex_mongo  | 2023-08-24T19:13:49.915093760Z {"t":{"$date":"2023-08-24T19:13:49.914+00:00"},"s":"I",  "c":"STORAGE",  "id":22297,   "ctx":"initandlisten","msg":"Using the XFS filesystem is strongly recommended with the WiredTiger storage engine. See http://dochub.mongodb.org/core/prodnotes-filesystem","tags":["startupWarnings"]}
sharelatex_mongo  | 2023-08-24T19:13:49.915107576Z {"t":{"$date":"2023-08-24T19:13:49.915+00:00"},"s":"I",  "c":"STORAGE",  "id":22315,   "ctx":"initandlisten","msg":"Opening WiredTiger","attr":{"config":"create,cache_size=31615M,session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000,close_scan_interval=10,close_handle_minimum=250),statistics_log=(wait=0),verbose=[recovery_progress,checkpoint_progress,compact_progress],"}}
sharelatex_redis  | 2023-08-24T19:13:49.878746620Z 1:C 24 Aug 2023 19:13:49.877 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
sharelatex_redis  | 2023-08-24T19:13:49.878792262Z 1:C 24 Aug 2023 19:13:49.877 # Redis version=6.2.13, bits=64, commit=00000000, modified=0, pid=1, just started
sharelatex_redis  | 2023-08-24T19:13:49.878798410Z 1:C 24 Aug 2023 19:13:49.877 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
sharelatex_redis  | 2023-08-24T19:13:49.878803642Z 1:M 24 Aug 2023 19:13:49.878 * monotonic clock: POSIX clock_gettime
sharelatex_redis  | 2023-08-24T19:13:49.883883291Z 1:M 24 Aug 2023 19:13:49.883 * Running mode=standalone, port=6379.
sharelatex_redis  | 2023-08-24T19:13:49.883908676Z 1:M 24 Aug 2023 19:13:49.883 # Server initialized
sharelatex_redis  | 2023-08-24T19:13:49.883914586Z 1:M 24 Aug 2023 19:13:49.883 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
sharelatex_redis  | 2023-08-24T19:13:49.884349992Z 1:M 24 Aug 2023 19:13:49.884 * Ready to accept connections
sharelatex        | 2023-08-24T19:13:50.320519013Z *** Running /etc/my_init.d/00_make_sharelatex_data_dirs.sh...
sharelatex        | 2023-08-24T19:13:50.373276746Z *** Running /etc/my_init.d/00_regen_sharelatex_secrets.sh...
sharelatex        | 2023-08-24T19:13:50.377196249Z generating random secrets
sharelatex        | 2023-08-24T19:13:50.409822846Z *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
sharelatex        | 2023-08-24T19:13:50.420499434Z *** Running /etc/my_init.d/00_restore_site_status...
sharelatex        | 2023-08-24T19:13:50.427820815Z *** Running /etc/my_init.d/00_set_docker_host_ipaddress.sh...
sharelatex        | 2023-08-24T19:13:50.438740446Z *** Running /etc/my_init.d/01_nginx_config_template.sh...
sharelatex        | 2023-08-24T19:13:50.440910689Z Nginx: generating config file from template
sharelatex        | 2023-08-24T19:13:50.441936874Z Nginx: reloading config
sharelatex_mongo  | 2023-08-24T19:13:50.448379873Z {"t":{"$date":"2023-08-24T19:13:50.448+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1692904430:448215][1:0x7fc0680a2cc0], txn-recover: [WT_VERB_RECOVERY | WT_VERB_RECOVERY_PROGRESS] Set global recovery timestamp: (0, 0)"}}
sharelatex_mongo  | 2023-08-24T19:13:50.448396592Z {"t":{"$date":"2023-08-24T19:13:50.448+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1692904430:448251][1:0x7fc0680a2cc0], txn-recover: [WT_VERB_RECOVERY | WT_VERB_RECOVERY_PROGRESS] Set global oldest timestamp: (0, 0)"}}
sharelatex        | 2023-08-24T19:13:50.450483031Z  * Reloading nginx configuration nginx
sharelatex_mongo  | 2023-08-24T19:13:50.455496355Z {"t":{"$date":"2023-08-24T19:13:50.455+00:00"},"s":"I",  "c":"STORAGE",  "id":4795906, "ctx":"initandlisten","msg":"WiredTiger opened","attr":{"durationMillis":540}}
sharelatex_mongo  | 2023-08-24T19:13:50.455525711Z {"t":{"$date":"2023-08-24T19:13:50.455+00:00"},"s":"I",  "c":"RECOVERY", "id":23987,   "ctx":"initandlisten","msg":"WiredTiger recoveryTimestamp","attr":{"recoveryTimestamp":{"$timestamp":{"t":0,"i":0}}}}
sharelatex        | 2023-08-24T19:13:50.457076974Z    ...done.
sharelatex        | 2023-08-24T19:13:50.459973038Z *** Running /etc/my_init.d/10_delete_old_logs.sh...
sharelatex        | 2023-08-24T19:13:50.466128932Z *** Running /etc/my_init.d/10_syslog-ng.init...
sharelatex_mongo  | 2023-08-24T19:13:50.466678093Z {"t":{"$date":"2023-08-24T19:13:50.466+00:00"},"s":"I",  "c":"STORAGE",  "id":22262,   "ctx":"initandlisten","msg":"Timestamp monitor starting"}
sharelatex_mongo  | 2023-08-24T19:13:50.469118551Z {"t":{"$date":"2023-08-24T19:13:50.468+00:00"},"s":"W",  "c":"CONTROL",  "id":22120,   "ctx":"initandlisten","msg":"Access control is not enabled for the database. Read and write access to data and configuration is unrestricted","tags":["startupWarnings"]}
sharelatex_mongo  | 2023-08-24T19:13:50.469750779Z {"t":{"$date":"2023-08-24T19:13:50.469+00:00"},"s":"I",  "c":"STORAGE",  "id":20320,   "ctx":"initandlisten","msg":"createCollection","attr":{"namespace":"admin.system.version","uuidDisposition":"provided","uuid":{"uuid":{"$uuid":"f653de4f-852f-4046-b582-d7002ccc6209"}},"options":{"uuid":{"$uuid":"f653de4f-852f-4046-b582-d7002ccc6209"}}}}
sharelatex_mongo  | 2023-08-24T19:13:50.479129089Z {"t":{"$date":"2023-08-24T19:13:50.479+00:00"},"s":"I",  "c":"INDEX",    "id":20345,   "ctx":"initandlisten","msg":"Index build: done building","attr":{"buildUUID":null,"namespace":"admin.system.version","index":"_id_","commitTimestamp":{"$timestamp":{"t":0,"i":0}}}}
sharelatex_mongo  | 2023-08-24T19:13:50.479377099Z {"t":{"$date":"2023-08-24T19:13:50.479+00:00"},"s":"I",  "c":"COMMAND",  "id":20459,   "ctx":"initandlisten","msg":"Setting featureCompatibilityVersion","attr":{"newVersion":"4.4"}}
sharelatex_mongo  | 2023-08-24T19:13:50.479780712Z {"t":{"$date":"2023-08-24T19:13:50.479+00:00"},"s":"I",  "c":"STORAGE",  "id":20536,   "ctx":"initandlisten","msg":"Flow Control is enabled on this deployment"}
sharelatex_mongo  | 2023-08-24T19:13:50.480630739Z {"t":{"$date":"2023-08-24T19:13:50.480+00:00"},"s":"I",  "c":"STORAGE",  "id":20320,   "ctx":"initandlisten","msg":"createCollection","attr":{"namespace":"local.startup_log","uuidDisposition":"generated","uuid":{"uuid":{"$uuid":"1b8c4a31-a6f7-455c-912b-342586447a26"}},"options":{"capped":true,"size":10485760}}}
sharelatex_mongo  | 2023-08-24T19:13:50.489481320Z {"t":{"$date":"2023-08-24T19:13:50.489+00:00"},"s":"I",  "c":"INDEX",    "id":20345,   "ctx":"initandlisten","msg":"Index build: done building","attr":{"buildUUID":null,"namespace":"local.startup_log","index":"_id_","commitTimestamp":{"$timestamp":{"t":0,"i":0}}}}
sharelatex_mongo  | 2023-08-24T19:13:50.490163009Z {"t":{"$date":"2023-08-24T19:13:50.490+00:00"},"s":"I",  "c":"FTDC",     "id":20625,   "ctx":"initandlisten","msg":"Initializing full-time diagnostic data capture","attr":{"dataDirectory":"/data/db/diagnostic.data"}}
sharelatex_mongo  | 2023-08-24T19:13:50.490563085Z {"t":{"$date":"2023-08-24T19:13:50.490+00:00"},"s":"I",  "c":"REPL",     "id":6015317, "ctx":"initandlisten","msg":"Setting new configuration state","attr":{"newState":"ConfigReplicationDisabled","oldState":"ConfigPreStart"}}
sharelatex_mongo  | 2023-08-24T19:13:50.492400053Z {"t":{"$date":"2023-08-24T19:13:50.491+00:00"},"s":"I",  "c":"NETWORK",  "id":23015,   "ctx":"listener","msg":"Listening on","attr":{"address":"/tmp/mongodb-27017.sock"}}
sharelatex_mongo  | 2023-08-24T19:13:50.492422659Z {"t":{"$date":"2023-08-24T19:13:50.491+00:00"},"s":"I",  "c":"CONTROL",  "id":20712,   "ctx":"LogicalSessionCacheReap","msg":"Sessions collection is not set up; waiting until next sessions reap interval","attr":{"error":"NamespaceNotFound: config.system.sessions does not exist"}}
sharelatex_mongo  | 2023-08-24T19:13:50.492444860Z {"t":{"$date":"2023-08-24T19:13:50.491+00:00"},"s":"I",  "c":"NETWORK",  "id":23015,   "ctx":"listener","msg":"Listening on","attr":{"address":"0.0.0.0"}}
sharelatex_mongo  | 2023-08-24T19:13:50.492450672Z {"t":{"$date":"2023-08-24T19:13:50.491+00:00"},"s":"I",  "c":"NETWORK",  "id":23016,   "ctx":"listener","msg":"Waiting for connections","attr":{"port":27017,"ssl":"off"}}
sharelatex_mongo  | 2023-08-24T19:13:50.492455198Z {"t":{"$date":"2023-08-24T19:13:50.491+00:00"},"s":"I",  "c":"STORAGE",  "id":20320,   "ctx":"LogicalSessionCacheRefresh","msg":"createCollection","attr":{"namespace":"config.system.sessions","uuidDisposition":"generated","uuid":{"uuid":{"$uuid":"8bf4e93f-829c-4846-8def-95ce54eb875f"}},"options":{}}}
sharelatex        | 2023-08-24T19:13:50.500192413Z Aug 24 19:13:50 b56d220cd398 syslog-ng[88]: syslog-ng starting up; version='3.25.1'
sharelatex_mongo  | 2023-08-24T19:13:50.505003815Z {"t":{"$date":"2023-08-24T19:13:50.504+00:00"},"s":"I",  "c":"INDEX",    "id":20345,   "ctx":"LogicalSessionCacheRefresh","msg":"Index build: done building","attr":{"buildUUID":null,"namespace":"config.system.sessions","index":"_id_","commitTimestamp":{"$timestamp":{"t":0,"i":0}}}}
sharelatex_mongo  | 2023-08-24T19:13:50.505021874Z {"t":{"$date":"2023-08-24T19:13:50.504+00:00"},"s":"I",  "c":"INDEX",    "id":20345,   "ctx":"LogicalSessionCacheRefresh","msg":"Index build: done building","attr":{"buildUUID":null,"namespace":"config.system.sessions","index":"lsidTTLIndex","commitTimestamp":{"$timestamp":{"t":0,"i":0}}}}
sharelatex        | 2023-08-24T19:13:51.512964768Z *** Running /etc/my_init.d/98_check_db_access.sh...
sharelatex        | 2023-08-24T19:13:51.518115341Z Checking can connect to mongo and redis
sharelatex        | 2023-08-24T19:13:51.692139388Z Using default settings from /overleaf/services/web/config/settings.defaults.js
sharelatex        | 2023-08-24T19:13:51.694867456Z Using settings from /etc/sharelatex/settings.js
sharelatex        | 2023-08-24T19:13:51.865507579Z Set UV_THREADPOOL_SIZE=16
sharelatex_mongo  | 2023-08-24T19:13:51.885928690Z {"t":{"$date":"2023-08-24T19:13:51.885+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"192.168.208.4:39140","connectionId":1,"connectionCount":1}}
sharelatex_mongo  | 2023-08-24T19:13:51.889703175Z {"t":{"$date":"2023-08-24T19:13:51.889+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn1","msg":"client metadata","attr":{"remote":"192.168.208.4:39140","client":"conn1","doc":{"application":{"name":"web"},"driver":{"name":"nodejs|Mongoose","version":"4.16.0|6.11.4"},"platform":"Node.js v18.17.1, LE","os":{"name":"linux","architecture":"x64","version":"5.15.0-76-generic","type":"Linux"}}}}
sharelatex_mongo  | 2023-08-24T19:13:51.900754940Z {"t":{"$date":"2023-08-24T19:13:51.900+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"192.168.208.4:39154","connectionId":2,"connectionCount":2}}
sharelatex_mongo  | 2023-08-24T19:13:51.901766007Z {"t":{"$date":"2023-08-24T19:13:51.901+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn2","msg":"client metadata","attr":{"remote":"192.168.208.4:39154","client":"conn2","doc":{"application":{"name":"web"},"driver":{"name":"nodejs|Mongoose","version":"4.16.0|6.11.4"},"platform":"Node.js v18.17.1, LE","os":{"name":"linux","architecture":"x64","version":"5.15.0-76-generic","type":"Linux"}}}}
sharelatex        | 2023-08-24T19:13:51.907459543Z Mongo instance doesn't support transactions
sharelatex        | 2023-08-24T19:13:51.908466543Z MongoServerError: Transaction numbers are only allowed on a replica set member or mongos
sharelatex        | 2023-08-24T19:13:51.908489075Z     at Connection.onMessage (/overleaf/services/web/node_modules/mongodb/lib/cmap/connection.js:231:30)
sharelatex        | 2023-08-24T19:13:51.908495484Z     at MessageStream.<anonymous> (/overleaf/services/web/node_modules/mongodb/lib/cmap/connection.js:61:60)
sharelatex        | 2023-08-24T19:13:51.908500946Z     at MessageStream.emit (node:events:514:28)
sharelatex        | 2023-08-24T19:13:51.908506318Z     at processIncomingData (/overleaf/services/web/node_modules/mongodb/lib/cmap/message_stream.js:125:16)
sharelatex        | 2023-08-24T19:13:51.908510469Z     at MessageStream._write (/overleaf/services/web/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
sharelatex        | 2023-08-24T19:13:51.908514031Z     at writeOrBuffer (node:internal/streams/writable:392:12)
sharelatex        | 2023-08-24T19:13:51.908518731Z     at _write (node:internal/streams/writable:333:10)
sharelatex        | 2023-08-24T19:13:51.908523404Z     at Writable.write (node:internal/streams/writable:337:10)
sharelatex        | 2023-08-24T19:13:51.908527646Z     at Socket.ondata (node:internal/streams/readable:766:22)
sharelatex        | 2023-08-24T19:13:51.908532322Z     at Socket.emit (node:events:514:28) {
sharelatex        | 2023-08-24T19:13:51.908536880Z   ok: 0,
sharelatex        | 2023-08-24T19:13:51.908541095Z   code: 20,
sharelatex        | 2023-08-24T19:13:51.908555116Z   codeName: 'IllegalOperation',
sharelatex        | 2023-08-24T19:13:51.908560277Z   [Symbol(errorLabels)]: Set(0) {}
sharelatex        | 2023-08-24T19:13:51.908565205Z }
sharelatex_mongo  | 2023-08-24T19:13:51.913054834Z {"t":{"$date":"2023-08-24T19:13:51.912+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn1","msg":"Connection ended","attr":{"remote":"192.168.208.4:39140","connectionId":1,"connectionCount":1}}
sharelatex_mongo  | 2023-08-24T19:13:51.913096903Z {"t":{"$date":"2023-08-24T19:13:51.912+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn2","msg":"Connection ended","attr":{"remote":"192.168.208.4:39154","connectionId":2,"connectionCount":0}}
sharelatex        | 2023-08-24T19:13:51.913097675Z *** /etc/my_init.d/98_check_db_access.sh failed with status 1
sharelatex        | 2023-08-24T19:13:51.913112416Z
sharelatex        | 2023-08-24T19:13:51.913143175Z *** Killing all processes...
  ```  
</details>

<details>
  <summary>docker-compose.yml</summary>

  ```bash
  APP_VER=4
  LIB_VER=4
  APP_RED_VER=6
  ```
  
  ```bash
  version: '3.9'

services:
  sharelatex:
    restart: always
    image: sharelatex/sharelatex:${APP_VER}
    container_name: sharelatex
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - 8083:80
    links:
      - mongo
      - redis
    stop_grace_period: 60s
    volumes:
      - ${APP_ROOT}/${FOLDER}/app${APP_VER}:/var/lib/sharelatex
    environment:
      SHARELATEX_APP_NAME: "LaTeX Online"
      SHARELATEX_MONGO_URL: mongodb://mongo/sharelatex
      SHARELATEX_REDIS_HOST: sharelatex_redis
      REDIS_HOST: sharelatex_redis
      ENABLED_LINKED_FILE_TYPES: 'project_file,project_output_file'
      ENABLE_CONVERSIONS: 'true'
      EMAIL_CONFIRMATION_DISABLED: 'true'
      TEXMFVAR: /var/lib/sharelatex/tmp/texmf-var

  mongo:
    restart: always
    image: mongo:${LIB_VER}
    container_name: sharelatex_mongo
    expose:
      - 27017
    volumes:
      - ${LIB_ROOT}/${FOLDER}/lib_a${APP_VER}_d${LIB_VER}:/data/db
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  redis:
    restart: always
    image: redis:${APP_RED_VER}
    container_name: sharelatex_redis
    expose:
      - 6379
    volumes:
      - ${LIB_ROOT}/${FOLDER}/redis_a${APP_VER}_r${APP_RED_VER}:/data
  ```
  
</details>

Even if I enter the exact version numbers: mongo:4.4; redis:6.2 (as in [1]) does not change. 
The exact same script with sharelatex version 3 works fine. 

[1] https://github.com/overleaf/overleaf/blob/main/docker-compose.yml

What could be the reason for this?

**Comment by senyai** [comment]
Looks like you should update your docker-compose.yml according to [Release Notes 4.x.x](https://github.com/overleaf/overleaf/wiki/Release-Notes--4.x.x#manually-setting-up-mongodb-as-a-replica-set)

**Comment by CrysK** [comment]
This works perfect. Should be added in the `docker-compose.yml`
But for me only `docker compose`, without minus worked.
