### ISSUE TITLE
Security Issue : Authenticated Users Gaining Access to All Projects Without Permissions + other issue 4.1.1

### ISSUE THREAD

**Issue by wixaw** [overleaf/overleaf#1151]
Hello,

I was looking at the logs for 4.1.1 because there are errors that I will put at the bottom of this ticket.
I saw actions on a project, and I decided to enter the ID in the URL of my browser, and then I found myself on another user's project without them granting me any rights.
We conducted various tests. If I share all the links to my projects with a colleague without sharing via the application, they have full editing access!
I tested this with 4.0.5, and the issue already existed.
You might argue that it's not a problem since you need to find the URLs, but let's say we share a project with someone and then revoke their access. If they still have the link, they will still have access.
I believe this is a significant security issue.
For your information, if you're not logged in, access is correctly denied.

Other error logs:

``` 
{"name":"web","hostname":"025c5d94f336","pid":182,"level":40,"err":{"message":"Premature close","name":"Error","stack":"Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close\n    at new NodeError (node:internal/errors:405:5)\n    at ServerResponse.onclose (node:internal/streams/end-of-stream:154:30)\n    at ServerResponse.emit (node:events:526:35)\n    at ServerResponse.emit (node:domain:489:12)\n    at emitCloseNT (node:_http_server:996:10)\n    at Socket.onServerResponseClose (node:_http_server:278:5)\n    at Socket.emit (node:events:526:35)\n    at Socket.emit (node:domain:489:12)\n    at TCP.<anonymous> (node:net:323:12)","info":{},"code":"ERR_STREAM_PREMATURE_CLOSE"},"projectId":"63072a93ba1213009d314493","url":"http://localhost:3013/project/63072a93ba1213009d314493/user/5a042cdf3b6f8e42705773c1/build/18a926bdb3e-7fae2313d0a7e881/output/Publi.blg?compileGroup=standard&compileBackendClass=e2","action":"output-file","reqAborted":true,"duration":6,"msg":"CLSI proxy error","time":"2023-09-14T06:40:56.928Z","v":0}
{"name":"clsi","hostname":"025c5d94f336","pid":166,"level":40,"err":{"message":"request failed","name":"RequestFailedError","stack":"RequestFailedError: request failed\n    at fetchStreamWithResponse (/overleaf/libraries/fetch-utils/index.js:55:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async fetchStream (/overleaf/libraries/fetch-utils/index.js:45:22)\n    at async pipeUrlToFile (/overleaf/services/clsi/app/js/UrlFetcher.js:35:18)\n    at async Object.pipeUrlToFileWithRetry (/overleaf/services/clsi/app/js/UrlFetcher.js:13:7)\n    at async download (/overleaf/services/clsi/app/js/UrlCache.js:65:5)\n    at async Object.downloadUrlToFile (/overleaf/services/clsi/app/js/UrlCache.js:52:3)","info":{"url":"http://localhost:3009/project/63072a93ba1213009d314493/file/63072a94ba1213009d3144d8","method":"GET","status":404}},"url":"http://localhost:3009/project/63072a93ba1213009d314493/file/63072a94ba1213009d3144d8","filePath":"/var/lib/sharelatex/data/cache/63072a93ba1213009d314493/-project-63072a93ba1213009d314493-file-63072a94ba1213009d3144d8-1661414036416","remainingAttempts":2,"msg":"error downloading url","time":"2023-09-14T06:40:43.736Z","v":0}
{"name":"project-history","hostname":"025c5d94f336","pid":165,"level":40,"err":{"message":"ESOCKETTIMEDOUT","name":"Error","stack":"Error: ESOCKETTIMEDOUT\n    at ClientRequest.<anonymous> (/overleaf/node_modules/request/request.js:816:19)\n    at Object.onceWrapper (node:events:628:28)\n    at ClientRequest.emit (node:events:514:28)\n    at Socket.emitRequestTimeout (node:_http_client:847:9)\n    at Object.onceWrapper (node:events:628:28)\n    at Socket.emit (node:events:526:35)\n    at Socket._onTimeout (node:net:571:8)\n    at listOnTimeout (node:internal/timers:569:17)\n    at process.processTimers (node:internal/timers:512:7)\nTaggedError\n    at Request._callback (file:///overleaf/services/project-history/app/js/HistoryStoreManager.js:417:30)\n    at self.callback (/overleaf/node_modules/request/request.js:185:22)\n    at Request.emit (node:events:514:28)\n    at ClientRequest.<anonymous> (/overleaf/node_modules/request/request.js:819:16)\n    at Object.onceWrapper (node:events:628:28)\n    at ClientRequest.emit (node:events:514:28)\n    at Socket.emitRequestTimeout (node:_http_client:847:9)\n    at Object.onceWrapper (node:events:628:28)\n    at Socket.emit (node:events:526:35)\n    at Socket._onTimeout (node:net:571:8)\n    at listOnTimeout (node:internal/timers:569:17)\n    at process.processTimers (node:internal/timers:512:7)\nTaggedError: failed to send changes to v1\n    at file:///overleaf/services/project-history/app/js/HistoryStoreManager.js:208:16\n    at Request._callback (file:///overleaf/services/project-history/app/js/HistoryStoreManager.js:417:14)\n    at self.callback (/overleaf/node_modules/request/request.js:185:22)\n    at Request.emit (node:events:514:28)\n    at ClientRequest.<anonymous> (/overleaf/node_modules/request/request.js:819:16)\n    at Object.onceWrapper (node:events:628:28)\n    at ClientRequest.emit (node:events:514:28)\n    at Socket.emitRequestTimeout (node:_http_client:847:9)\n    at Object.onceWrapper (node:events:628:28)\n    at Socket.emit (node:events:526:35)\n    at Socket._onTimeout (node:net:571:8)\n    at listOnTimeout (node:internal/timers:569:17)\n    at process.processTimers (node:internal/timers:512:7)","info":{"projectId":"65004e3ee6cfbdcf3c37fa45","historyId":"65004e3ee6cfbdcf3c37fa45","endVersion":523,"errorCode":"ESOCKETTIMEDOUT"},"code":"ESOCKETTIMEDOUT"},"msg":"ESOCKETTIMEDOUT","time":"2023-09-13T13:57:55.023Z","v":0}

```

**Comment by das7pad** [comment]
Hi William,

Thank you for writing this up. It looks like you are reporting a potential security issue. We prefer private reports for these, see [our security policy on GitHub](https://github.com/overleaf/overleaf/security).
Would you mind dropping us a message at security@overleaf.com to discuss this further?

Thanks,
Jakob

**Comment by wixaw** [comment]
Sorry, i can't delete my first message, i send mail

**Comment by jdleesmiller** [comment]
Thank you for sending the email. We have received it and will get back to you shortly. I will delete this issue.
