### ISSUE TITLE
overleaf not running after upgrade, something to do with migration

### ISSUE THREAD

**Issue by michaelvanhorn** [overleaf/overleaf#1158]
I've just upgraded overleaf from 3.0.1 to 4.1.3. Now, when I restart the service, the mongo and redis containers start just fine, but the sharelatex container keeps dying and restarting. There error is this over and over again:

sharelatex    | *** Running /etc/my_init.d/99_run_web_migrations.sh...
sharelatex    | Running migrations for server-ce
sharelatex    | 
sharelatex    | > migrations
sharelatex    | > east migrate -t server-ce
sharelatex    | 
sharelatex    | Using default settings from /overleaf/services/web/config/settings.defaults.js
sharelatex    | Using settings from /etc/sharelatex/settings.js
sharelatex    | Set UV_THREADPOOL_SIZE=16
sharelatex    | Target migrations:
sharelatex    | 	20230512100122_ensure_history_migration
sharelatex    | 	20230817081910_back_fill_gitBridge_feature_server_pro
sharelatex    | Migrate "20230512100122_ensure_history_migration"
sharelatex    | Error: Error during migrate "20230512100122_ensure_history_migration": Found 384 projects not migrated to Full Project History
sharelatex    |     at exports.migrate (/overleaf/services/web/migrations/20230512100122_ensure_history_migration.js:9:11)
sharelatex    |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
sharelatex    |     at async /overleaf/node_modules/p-map/index.js:57:22
sharelatex    | npm ERR! Lifecycle script `migrations` failed with error: 
sharelatex    | npm ERR! Error: command failed 
sharelatex    | npm ERR!   in workspace: @overleaf/web 
sharelatex    | npm ERR!   at location: /overleaf/services/web 
sharelatex    | *** /etc/my_init.d/99_run_web_migrations.sh failed with status 1
sharelatex    | 
sharelatex    | *** Killing all processes...
sharelatex    | Oct  6 18:16:35 d855a45ecfe5 syslog-ng[60]: syslog-ng shutting down; version='3.25.1'
sharelatex exited with code 1

There doesn't seem to be an indication as to what actually goes wrong. If I manually run "npm run migrations -- migrate -t server-ce", it just shows the same error messages, so I don't know what's actually failing.

**Comment by henryclw** [comment]
Maybe this [migration document](https://github.com/overleaf/overleaf/wiki/Full-Project-History-Migration) would be a nice hint for you?

**Comment by michaelvanhorn** [comment]
I looked at that page, but I assumed it was outdated, as there is doesn't seem to be /overleaf/services/web/scripts directory in our container, so I can't run the migrate_history.js script which that page says I should run.

**Comment by henryclw** [comment]
I think you might want to backup all your data (the docker mount volumes), then upgrade from 3.0.1 to 3.5.11, which introduce the [Full Project History Migration](https://github.com/overleaf/overleaf/wiki/Full-Project-History-Migration), and then use the migration script to migrate your data, then upgrade from 3.5.11 to 4.1.3

**Comment by michaelvanhorn** [comment]
Okay, so how do I upgrade to 3.5.11? The upgrade script goes straight to the latest version.

---
Mike VanHorn
Senior Computer Systems Administrator
College of Engineering and Computer Science
Wright State University
265 Russ Engineering Center
937-775-5157
***@***.***
Sent from my iPhone
________________________________

**Comment by henryclw** [comment]
I'm not sure how you host your sharelatex, I was using docker compose to host my sharelatex. The way I did my upgrade is to change to image label, like `image: sharelatex/sharelatex:3.5.11`.
But since 3.0.1 is quite far from 3.5.11, I'll suggest you backup all your docker volume, mark down your configs. And then upgrade from 3.0.1 to 3.1, then to 3.2, then 3.3 and so on. If any upgrade shows an error, then you could pin down which version upgrade the cause of the problem. Luckily, I've upgraded to 3.5.11 without any error.
Hope this would work for you as well.

**Comment by michaelvanhorn** [comment]
So you just change the image: label, and then run the upgrade script, and it will upgrade to that version? I thought that image label got changed by the upgrade script. Thank you for explaining that.

---
Mike VanHorn
Senior Computer Systems Administrator
College of Engineering and Computer Science
Wright State University
265 Russ Engineering Center
937-775-5157
***@***.***
Sent from my iPhone
________________________________

**Comment by henryclw** [comment]
According to <https://github.com/overleaf/overleaf/wiki/Full-Project-History-Migration>

> The 3.5.x release of Overleaf Community Edition includes the [Full Project History feature](https://www.overleaf.com/learn/latex/Using_the_History_feature) that is already available in our SaaS offering, [overleaf.com](http://overleaf.com/)

So I think this might indicate that the migration script is only available till 3.5, so we should upgrade to 3.5, run the migration script, then upgrade to 4
Hope this works for you.
Cheers

**Comment by michaelvanhorn** [comment]
Yes, I realize that I need to upgrade to 3.5 first. The question I had was how to do that? I didn't know you could change the image label and then run the upgrade script. I thought the image label was changed by the upgrade script, not an input to the upgrade script.

**Comment by michaelvanhorn** [comment]
So, I don't seem to have any file that says "image: sharelatex/sharelatex" in it. I do have a config/version file which simply contains the version number; is this the same thing?

**Comment by henryclw** [comment]
> So, I don't seem to have any file that says "image: sharelatex/sharelatex" in it. I do have a config/version file which simply contains the version number; is this the same thing?

May I ask how do you host the sharelatex on your server? I'm using docker compose, so I just edit the docker compose file. Would you mind giving more information about the config/version file that you currently have?

**Comment by michaelvanhorn** [comment]
I am using the toolkit, so editing the yml file doesn’t usually seem to be the way to do things. I figured out that the config/version file is use to get an image upgraded, and I was able to go from 3.0.1 to 3.5.11, update the history, and then upgrade from 3.5.11 to 4.1.3 and it all seems to work.

Thanks!

---
Mike VanHorn
Senior Computer Systems Administrator
College of Engineering and Computer Science
Wright State University
265 Russ Engineering Center
937-775-5157
***@***.***

From: Henry ***@***.***>
Reply-To: overleaf/overleaf ***@***.***>
Date: Monday, October 16, 2023 at 2:09 PM
To: overleaf/overleaf ***@***.***>
Cc: Mike VanHorn ***@***.***>, Author ***@***.***>
Subject: Re: [overleaf/overleaf] overleaf not running after upgrade, something to do with migration (Issue #1158)

So, I don't seem to have any file that says "image: sharelatex/sharelatex" in it. I do have a config/version file which simply contains the version number; is this the same thing? May I ask how do you host the sharelatex on your server? I'm
ZjQcmQRYFpfptBannerStart
CAUTION: This Message Is From an External Sender
Exercise caution when opening attachments or clicking links.
ZjQcmQRYFpfptBannerEnd

So, I don't seem to have any file that says "image: sharelatex/sharelatex" in it. I do have a config/version file which simply contains the version number; is this the same thing?

May I ask how do you host the sharelatex on your server? I'm using docker compose, so I just edit the docker compose file. Would you mind giving more information about the config/version file that you currently have?

**Comment by henryclw** [comment]
That's great, cheers!!!

P.S. If this problem has been solved you may close the issue if you want
