### ISSUE TITLE
Cannot find module @overleaf/promise-utils

### ISSUE THREAD

**Issue by Serdans** [overleaf/overleaf#1162]
## Steps to Reproduce

1. Build overleaf image from current branch
2. Run bin/init and bin/up from overleaf/toolkit

## Expected Behaviour

Overleaf runs.

## Observed Behaviour

Overleaf is not running. I get this error constantly in the Docker logs.

```
sharelatex  | *** Running /etc/my_init.d/99_run_web_migrations.sh...
sharelatex  | Running migrations for server-ce
sharelatex  |
sharelatex  | > migrations
sharelatex  | > east migrate -t server-ce
sharelatex  |
sharelatex  | Using default settings from /overleaf/services/web/config/settings.defaults.js
sharelatex  | Using settings from /etc/sharelatex/settings.js
sharelatex  | Set UV_THREADPOOL_SIZE=16
mongo       | {"t":{"$date":"2023-10-24T20:15:25.578+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.23.0.5:47636","connectionId":12,"connectionCount":4}}
mongo       | {"t":{"$date":"2023-10-24T20:15:25.582+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn12","msg":"client metadata","attr":{"remote":"172.23.0.5:47636","client":"conn12","doc":{"application":{"name":"web"},"driver":{"name":"nodejs|Mongoose","version":"4.17.1|6.12.0"},"platform":"Node.js v18.17.1, LE","os":{"name":"linux","architecture":"arm64","version":"5.15.0-1046-oracle","type":"Linux"}}}}
mongo       | {"t":{"$date":"2023-10-24T20:15:25.597+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.23.0.5:47640","connectionId":13,"connectionCount":5}}
mongo       | {"t":{"$date":"2023-10-24T20:15:25.598+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn13","msg":"client metadata","attr":{"remote":"172.23.0.5:47640","client":"conn13","doc":{"application":{"name":"web"},"driver":{"name":"nodejs|Mongoose","version":"4.17.1|6.12.0"},"platform":"Node.js v18.17.1, LE","os":{"name":"linux","architecture":"arm64","version":"5.15.0-1046-oracle","type":"Linux"}}}}
sharelatex  | Error: Error during load of migration "20190730093801_script_example": Error loading module "/overleaf/services/web/migrations/20190730093801_script_example.js":
sharelatex  |  Error: Cannot find module '@overleaf/promise-utils'
sharelatex  | Require stack:
sharelatex  | - /overleaf/services/web/app/src/Features/V1/V1Api.js
sharelatex  | - /overleaf/services/web/app/src/Features/TokenGenerator/TokenGenerator.js
sharelatex  | - /overleaf/services/web/app/src/models/User.js
sharelatex  | - /overleaf/services/web/scripts/example/script_for_migration.js
sharelatex  | - /overleaf/services/web/migrations/20190730093801_script_example.js
sharelatex  | - /overleaf/node_modules/east/lib/migrator/methods/_loadModule.js
sharelatex  | - /overleaf/node_modules/east/lib/migrator/methods/index.js
sharelatex  | - /overleaf/node_modules/east/lib/migrator/index.js
sharelatex  | - /overleaf/node_modules/east/lib/migrationManager.js
sharelatex  | - /overleaf/node_modules/east/bin/actions/base.js
sharelatex  | - /overleaf/node_modules/east/bin/actions/init.js
sharelatex  | - /overleaf/node_modules/east/bin/east.js
sharelatex  |     at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
sharelatex  |     at Module._load (node:internal/modules/cjs/loader:922:27)
sharelatex  |     at Module.require (node:internal/modules/cjs/loader:1143:19)
sharelatex  |     at require (node:internal/modules/cjs/helpers:121:18)
sharelatex  |     at Object.<anonymous> (/overleaf/services/web/app/src/Features/V1/V1Api.js:13:26)
sharelatex  |     at Module._compile (node:internal/modules/cjs/loader:1256:14)
sharelatex  |     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
sharelatex  |     at Module.load (node:internal/modules/cjs/loader:1119:32)
sharelatex  |     at Module._load (node:internal/modules/cjs/loader:960:12)
sharelatex  |     at Module.require (node:internal/modules/cjs/loader:1143:19)
sharelatex  |     at /overleaf/node_modules/east/lib/migrator/methods/_loadModule.js:21:10
sharelatex  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
sharelatex  |     at async /overleaf/node_modules/p-map/index.js:57:22
```

## Context

I am unable to have a local instance of Overleaf running. This issue only started happening recently.

## Technical Info

Running an arm64 instance. Built it on there since there's no arm64 builds.
* URL:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Signed in as:
* Project and/or file:

**Comment by emcsween** [comment]
Thanks for reporting this. A directory is missing from the repository. We'll add it shortly.

**Comment by emcsween** [comment]
I added the libraries/promise-utils directory to the repository. A new build from the main branch should now run correctly.
