### ISSUE TITLE
history-v1 return (connectionString.startsWith('mongodb://')

### ISSUE THREAD

**Issue by Thovi98** [overleaf/overleaf#1184]
Hello!

I’m trying to update the [Yunohost package](https://github.com/YunoHost-Apps/overleaf_ynh) of Overleaf Community Edition.
Unfortunately, Yunohost doesn’t support docker packaging, so we have to compile the app.

Everything installs well (`npm ci --quiet`).
After installation, I can access the web but cannot create a project.
If fact the `history-v1.service` refuses to start with following logs:

```
déc 17 16:32:09 systemd[1]: overleaf-history-v1.service: Scheduled restart job, restart counter is at 124.
déc 17 16:32:09 systemd[1]: Stopped overleaf history-v1.
déc 17 16:32:09 systemd[1]: overleaf-history-v1.service: Consumed 2.775s CPU time.
déc 17 16:32:09 systemd[1]: Started overleaf history-v1.
déc 17 16:32:12 systemd[1]: overleaf-history-v1.service: Main process exited, code=exited, status=1/FAILURE
déc 17 16:32:12 systemd[1]: overleaf-history-v1.service: Failed with result 'exit-code'.
déc 17 16:32:12 systemd[1]: overleaf-history-v1.service: Consumed 2.749s CPU time.
déc 17 16:32:17 systemd[1]: overleaf-history-v1.service: Scheduled restart job, restart counter is at 125.
déc 17 16:32:17 systemd[1]: Stopped overleaf history-v1.
déc 17 16:32:17 systemd[1]: overleaf-history-v1.service: Consumed 2.749s CPU time.
déc 17 16:32:17 systemd[1]: Started overleaf history-v1.
déc 17 16:32:19 systemd[1]: overleaf-history-v1.service: Main process exited, code=exited, status=1/FAILURE
déc 17 16:32:19 systemd[1]: overleaf-history-v1.service: Failed with result 'exit-code'.
déc 17 16:32:19 systemd[1]: overleaf-history-v1.service: Consumed 2.796s CPU time.

LOGFILE: /var/log/overleaf/history-v1.log
Initializing metrics
Set UV_THREADPOOL_SIZE=16
/var/www/overleaf/live/node_modules/mongodb-connection-string-url/lib/index.js:9
    return (connectionString.startsWith('mongodb://') ||
                             ^

TypeError: Cannot read properties of undefined (reading 'startsWith')
    at connectionStringHasValidScheme (/var/www/overleaf/live/node_modules/mongodb-connection-string-url/lib/index.js:9:30)
    at new ConnectionString (/var/www/overleaf/live/node_modules/mongodb-connection-string-url/lib/index.js:85:34)
    at parseOptions (/var/www/overleaf/live/services/history-v1/node_modules/mongodb/lib/connection_string.js:185:17)
    at new MongoClient (/var/www/overleaf/live/services/history-v1/node_modules/mongodb/lib/mongo_client.js:51:63)
    at Object.<anonymous> (/var/www/overleaf/live/services/history-v1/storage/lib/mongodb.js:6:16)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/var/www/overleaf/live/services/history-v1/storage/lib/blob_store/index.js:17:17)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
```

Am I right saying that `history-v1.service` is mandatory to make the app work?

I can create an admin and I see the Mongo db is updated, so I don’t think it’s related to a wrong mongo url?

Currently, it looks like this:
`SHARELATEX_MONGO_URL="mongodb://127.0.0.1:27017/__DB_NAME__"`

If someone has an idea about it I would be glad, thanks!

## Technical Info

Server OS: Yunohost 11 (Debian 11 Bullseye-based)
Mongo 4.4/6.0 (tried both)

**Comment by das7pad** [comment]
Hi there,

We do not support running the services outside of docker. There are a lot of expectations from directory layouts to security boundaries (internal services not being exposed to the host/internet) that need to be taken care of.

With that said, I can point you at our startup script for the history-v1 service, which sports an alias for the environment variable `SHARELATEX_MONGO_URL`:

https://github.com/overleaf/overleaf/blob/537c8227892209579a368a747b0bd2ac2f43a3a7/server-ce/runit/history-v1-sharelatex/run#L9

Happy hacking,
Jakob

**Comment by Thovi98** [comment]
Thank you!
Indeed, adding those environment variables fixes the issue, I could make it work!

Thank for your kind answer :)
