### ISSUE TITLE
Overleaf Docker not starting but worked before

### ISSUE THREAD

**Issue by ldehner** [overleaf/overleaf#1225]
## Steps to Reproduce

1. Start Overleaf Docker in Unraid

## Expected Behaviour
Overleaf starts

## Observed Behaviour
Overleaf Crashes

## Temporary sketchy fix:
https://github.com/overleaf/overleaf/issues/1225#issuecomment-2162344498

## Analysis
Log:
```
text  error  warn  system  array  login  

*** /etc/my_init.d/910_initiate_doc_version_recovery failed with status 1

*** Killing all processes...
*** Running /etc/my_init.d/000_check_for_old_bind_mounts_5.sh...
*** Running /etc/my_init.d/000_check_for_old_env_vars_5.sh...
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/100_generate_secrets.sh...
*** Running /etc/my_init.d/100_make_overleaf_data_dirs.sh...
*** Running /etc/my_init.d/100_restore_site_status.sh...
*** Running /etc/my_init.d/100_set_docker_host_ipaddress.sh...
*** Running /etc/my_init.d/10_syslog-ng.init...
*** Running /etc/my_init.d/200_nginx_config_template.sh...
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
*** Running /etc/my_init.d/300_delete_old_logs.sh...
*** Running /etc/my_init.d/500_check_db_access.sh...
Mongodb is up.
[WARN] This Redis server's `default` user does not require a password, but a password was supplied
Redis is up.
*** Running /etc/my_init.d/900_run_web_migrations.sh...
*** Running /etc/my_init.d/910_initiate_doc_version_recovery...
*** /etc/my_init.d/910_initiate_doc_version_recovery failed with status 1

*** Killing all processes...
}
May  9 22:07:27 ec9768d0c85d syslog-ng[51]: syslog-ng shutting down; version='3.35.1'
May  9 22:08:58 ec9768d0c85d syslog-ng[51]: syslog-ng starting up; version='3.35.1'
Nginx: generating config file from template
Checking Nginx config
Nginx: reloading config
 * Reloading nginx configuration nginx
   ...done.
Checking can connect to mongo and redis
Using default settings from /overleaf/services/web/config/settings.defaults.js
Using settings from /etc/overleaf/settings.js
Set UV_THREADPOOL_SIZE=16
Using default settings from /overleaf/services/web/config/settings.defaults.js
Using settings from /etc/overleaf/settings.js
Set UV_THREADPOOL_SIZE=16
All checks passed
Running migrations for server-ce

> migrations
> MONGO_SOCKET_TIMEOUT=0 east migrate -t server-ce

Using default settings from /overleaf/services/web/config/settings.defaults.js
Using settings from /etc/overleaf/settings.js
Set UV_THREADPOOL_SIZE=16
Nothing to migrate
Finished migrations
Checking for doc version recovery. This can take a while if needed. Logs are in /var/lib/overleaf/data/history/doc-version-recovery.log
Using settings from /etc/overleaf/settings.js
Set UV_THREADPOOL_SIZE=16
{"name":"default","hostname":"ec9768d0c85d","pid":126,"level":30,"backend":"fs","msg":"Loading backend","time":"2024-05-09T22:09:00.879Z","v":0}
(node:126) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
{"name":"default","hostname":"ec9768d0c85d","pid":126,"level":40,"err":{"message":"We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.\n\nPlease migrate your code to use AWS SDK for JavaScript (v3).\nFor more information, check the migration guide at https://a.co/7PzMCcy","name":"NOTE","stack":"NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.\n\nPlease migrate your code to use AWS SDK for JavaScript (v3).\nFor more information, check the migration guide at https://a.co/7PzMCcy\n    at emitWarning (/overleaf/node_modules/aws-sdk/lib/maintenance_mode_message.js:37:13)\n    at Timeout._onTimeout (/overleaf/node_modules/aws-sdk/lib/maintenance_mode_message.js:45:5)\n    at listOnTimeout (node:internal/timers:569:17)\n    at process.processTimers (node:internal/timers:512:7)","info":{}},"msg":"Warning details","time":"2024-05-09T22:09:00.966Z","v":0}
[WARN] This Redis server's `default` user does not require a password, but a password was supplied
Need to recover doc versions. This will take a while.
Need to check 2 projects and up-to 0 deleted projects with a total of 2 docs.
{"name":"default","hostname":"ec9768d0c85d","pid":126,"level":50,"err":{"message":"chunk for 65e9c488375edacb3ec24e73 not persisted yet","name":"NotPersistedError","stack":"NotPersistedError: chunk for 65e9c488375edacb3ec24e73 not persisted yet\n    at /overleaf/services/history-v1/storage/lib/history_store.js:81:15\n    at tryCatcher (/overleaf/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/overleaf/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/overleaf/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/overleaf/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/overleaf/node_modules/bluebird/js/release/promise.js:725:18)\n    at _drainQueueStep (/overleaf/node_modules/bluebird/js/release/async.js:93:12)\n    at _drainQueue (/overleaf/node_modules/bluebird/js/release/async.js:86:9)\n    at Async._drainQueues (/overleaf/node_modules/bluebird/js/release/async.js:102:5)\n    at Async.drainQueues [as _onImmediate] (/overleaf/node_modules/bluebird/js/release/async.js:15:14)\n    at process.processImmediate (node:internal/timers:476:21)","info":{"projectId":"65e9c488375edacb3ec24e73"}},"projectId":"65e9c488375edacb3ec24e73","msg":"Failed to process project","time":"2024-05-09T22:09:01.016Z","v":0}
0 projects updated in Redis
0 projects updated in Mongo
0 projects updated in both Mongo and Redis
0 projects had good versions
0 deleted projects updated in Mongo
0 deleted projects updated in Redis
0 deleted projects updated in both Mongo and Redis
0 deleted projects had good versions
0 projects skipped
Flushing log queue.
NotPersistedError: chunk for 65e9c488375edacb3ec24e73 not persisted yet
    at /overleaf/services/history-v1/storage/lib/history_store.js:81:15
    at tryCatcher (/overleaf/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/overleaf/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/overleaf/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/overleaf/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/overleaf/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/overleaf/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/overleaf/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/overleaf/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues [as _onImmediate] (/overleaf/node_modules/bluebird/js/release/async.js:15:14)
    at process.processImmediate (node:internal/timers:476:21) {
  info: { projectId: '65e9c488375edacb3ec24e73' },
  projectId: '65e9c488375edacb3ec24e73'
}
May  9 22:09:01 ec9768d0c85d syslog-ng[51]: syslog-ng shutting down; version='3.35.1'

** Press ANY KEY to close this window **

**Comment by mserranom** [comment]
Would you mind confirming the version of Overleaf CE you're using?

**Comment by ldehner** [comment]
@mserranom  I am using sharelatex/sharelatext:latest

**Comment by KnightWolf-50** [comment]
I am having the exact same issue. 
@ldehner did you find a solution?

**Comment by ldehner** [comment]
@KnightWolf-50 - sadly no, and nobody of the dev team seems to care. Any updates on your side?

I think that the solution would be to erase all mongo db instances, but I dont want to do this everytime it crashes. The whole data storage system isn't very good in my opinion, with everything just stored in mongo. Because I was afraid of something like this, I built myself a workflow which downloads the files after compile. But something like this can't happen in my opinion. At least I hoped for some support

**Comment by KnightWolf-50** [comment]
@ldehner I managed to get it working again, but as you mentioned, it required erasing the Mongo database. Fortunately, I had backups of all my projects, so in the end it was a hassle but I didn't lose any data.

**Comment by ldehner** [comment]
Thank you so much @bockulator. Thats kinda sketchy but also kinda genius. Actually Overleaf should implement a parameter to set if startup should skip it.. I am using unraid thus I had to do following:

```
# Create a directory for the custom Dockerfile
mkdir custom-sharelatex
cd custom-sharelatex

# Create and edit the Dockerfile
cat <<EOF > Dockerfile
# Start from the official ShareLaTeX image
FROM sharelatex/sharelatex

# Move the recovery script to skip it during startup
RUN mv /etc/my_init.d/910_initiate_doc_version_recovery /910_initiate_doc_version_recovery.backup

# Any additional customization can be added here
EOF

# Build the custom Docker image
docker build -t custom-sharelatex .

docker run -d \
  --network br0 \
  --ip 192.168.178.30 \
  -p 80:80 \
  -v /mnt/user/Overleaf/:/var/lib/overleaf \
  -e OVERLEAF_APP_NAME="Overleaf" \
  -e OVERLEAF_NAV_TITLE="Overleaf" \
  -e OVERLEAF_SITE_URL="https://your-overleaf-instance.example.com" \
  -e OVERLEAF_ADMIN_EMAIL="admin@example.com" \
  -e OVERLEAF_REDIS_HOST="192.168.178.27" \
  -e OVERLEAF_REDIS_PORT="6379" \
  -e OVERLEAF_REDIS_PASS='your_redis_password' \
  -e OVERLEAF_MONGO_URL="mongodb://192.168.178.29" \
  -e OVERLEAF_BEHIND_PROXY="true" \
  -e OVERLEAF_SESSION_SECRET="your_random_string" \
  -e OVERLEAF_SECURE_COOKIE="1" \
  -e OVERLEAF_RESTRICT_INVITES_TO_EXISTING_ACCOUNTS="false" \
  -e OVERLEAF_ALLOW_PUBLIC_ACCESS="true" \
  -e OVERLEAF_ALLOW_ANONYMOUS_READ_AND_WRITE_SHARING="false" \
  -e OVERLEAF_EMAIL_SMTP_HOST="smtp.example.com" \
  -e OVERLEAF_EMAIL_SMTP_PORT="465" \
  -e OVERLEAF_EMAIL_SMTP_USER="smtp_user@example.com" \
  -e OVERLEAF_EMAIL_SMTP_PASS='your_smtp_password' \
  -e OVERLEAF_EMAIL_FROM_ADDRESS="overleaf@example.com" \
  --name overleafV2 \
  custom-sharelatex

**Comment by minuq** [comment]
> Thank you so much @bockulator. Thats kinda sketchy but also kinda genius. Actually Overleaf should implement a parameter to set if startup should skip it.. I am using unraid thus I had to do following:
...

Using unraid as well, but being a bit more lazy i connected to the cli and as a quick and dirty solution did the following:
`docker start overleaf && docker exec -it overleaf mv /etc/my_init.d/910_initiate_doc_version_recovery /910_initiate_doc_version_recovery.backup && docker logs -ft overleaf`

Subsequent restarts of the container worked without issue, my best guess is that a powerout caused the initial error in my setup.

**Comment by das7pad** [comment]
Hello,

Missing chunks indicate data-loss and as a result, some of your projects will have broken project histories. Using a backup to restore these files is a good first step.

I'm afraid Unraid is not a supported operation system for Overleaf Community Edition or [Server Pro](https://www.overleaf.com/for/enterprises). As [noted in our docs](https://github.com/overleaf/overleaf/wiki/Quick-Start-Guide#operating-systems), we recommend using a Debian/Ubuntu based operation system.

Greetings,
Jakob
