### ISSUE TITLE
MongoServerError: Transaction numbers are only allowed on a replica set member or mongos

### ISSUE THREAD

**Issue by hzxie** [overleaf/overleaf#1229]
## Steps to Reproduce

1. Use docker-compose following the official instructions https://github.com/overleaf/overleaf/wiki/Quick-Start-Guide
2. Edit `docker-compose.yml`
3. `docker-compose up -d`

## Expected Behaviour

The webpage can be display normally.

## Observed Behaviour

```
*** Killing all processes...
May 23 04:16:40 d11f251fbdb4 syslog-ng[51]: syslog-ng shutting down; version='3.35.1'
*** Running /etc/my_init.d/000_check_for_old_bind_mounts_5.sh...
*** Running /etc/my_init.d/000_check_for_old_env_vars_5.sh...
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/100_generate_secrets.sh...
*** Running /etc/my_init.d/100_make_overleaf_data_dirs.sh...
*** Running /etc/my_init.d/100_restore_site_status.sh...
*** Running /etc/my_init.d/100_set_docker_host_ipaddress.sh...
*** Running /etc/my_init.d/10_syslog-ng.init...
May 23 04:17:40 d11f251fbdb4 syslog-ng[51]: syslog-ng starting up; version='3.35.1'
*** Running /etc/my_init.d/200_nginx_config_template.sh...
Nginx: generating config file from template
Checking Nginx config
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
Nginx: reloading config
 * Reloading nginx configuration nginx
   ...done.
*** Running /etc/my_init.d/300_delete_old_logs.sh...
*** Running /etc/my_init.d/500_check_db_access.sh...
Checking can connect to mongo and redis
Using default settings from /overleaf/services/web/config/settings.defaults.js
Using settings from /etc/overleaf/settings.js
Set UV_THREADPOOL_SIZE=16
Mongo instance doesn't support transactions
MongoServerError: Transaction numbers are only allowed on a replica set member or mongos
    at Connection.onMessage (/overleaf/node_modules/mongodb/lib/cmap/connection.js:231:30)
    at MessageStream.<anonymous> (/overleaf/node_modules/mongodb/lib/cmap/connection.js:61:60)
    at MessageStream.emit (node:events:517:28)
    at processIncomingData (/overleaf/node_modules/mongodb/lib/cmap/message_stream.js:125:16)
    at MessageStream._write (/overleaf/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at Socket.ondata (node:internal/streams/readable:809:22)
    at Socket.emit (node:events:517:28) {
  ok: 0,
  code: 20,
  codeName: 'IllegalOperation',
  [Symbol(errorLabels)]: Set(0) {}
}
*** /etc/my_init.d/500_check_db_access.sh failed with status 1
```

## Technical Info

* URL:
* Browser Name and version: Chrome 125.0.6422.76 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Arch Linux
* Signed in as: N/A
* Project and/or file: N/A

**Comment by mserranom** [comment]
MongoDB needs to run as a Replica Set since 4.0.1. 

Check the release notes for any extra information: https://github.com/overleaf/overleaf/wiki/Release-Notes--4.x.x#server-pro-401
