### ISSUE TITLE
Overleaf says Out of sync while connected

### ISSUE THREAD

**Issue by sduperret** [overleaf/overleaf#1287]
## Steps to Reproduce

1. Install and run ovearleaf CE with docker compose (and toolkit) / last version
2. Create a new project and type some things
3. A message with "Saving main.tex (X seconds of unsaved change) displayed
4. Connection lost pop-up
![image](https://github.com/user-attachments/assets/b4a44909-24c8-48f8-9ae0-ae733b24efed)
5. Out of sync pop-up
![image](https://github.com/user-attachments/assets/3757803e-8bd3-4f69-b1da-b63d5cf16a5a)

## Expected Behaviour

Saving the document.

## Observed Behaviour

Nothing in the docker logs for all services.

![image](https://github.com/user-attachments/assets/b4a44909-24c8-48f8-9ae0-ae733b24efed)
![image](https://github.com/user-attachments/assets/3757803e-8bd3-4f69-b1da-b63d5cf16a5a)

## Context

Overleaf is not usable. I was trying to write a document.

## Technical Info

Nothing in the log

* URL:sel-hosted instance with traefik reverse-proxy
* Browser Name and version: google chrome (v. 131.0.6778.86)
* Operating System and version (desktop or mobile): docker running on Ubuntu 24.04.1 LTS (GNU/Linux 6.8.0-48-generic x86_64)
* Signed in as: admin
* Project and/or file: main.tex

## Analysis

Nothing special in the logs.

**Comment by Shadowxp13** [comment]
I'm running into this issue in my instance as well. There's nothing unusual in the logs expect for these lines:

**Comment by Shadowxp13** [comment]
I'm running into this issue in my instance as well. There's nothing unusual in the logs expect for these lines almost every time that the issue arises:

```
{"name":"default","hostname":"8cac49fe42d1","pid":175,"level":40,"err":{"message":"We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.\n\nPlease migrate your code to use AWS SDK for JavaScript (v3).\nFor more information, check the migration guide at https://a.co/7PzMCcy","name":"NOTE","stack":"NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.\n\nPlease migrate your code to use AWS SDK for JavaScript (v3).\nFor more information, check the migration guide at https://a.co/7PzMCcy\n    at emitWarning (/overleaf/node_modules/aws-sdk/lib/maintenance_mode_message.js:37:13)\n    at Timeout._onTimeout (/overleaf/node_modules/aws-sdk/lib/maintenance_mode_message.js:45:5)\n    at listOnTimeout (node:internal/timers:569:17)\n    at process.processTimers (node:internal/timers:512:7)","info":{}},"msg":"Warning details","time":"2024-11-28T08:29:11.689Z","v":0}
(node:175) [MONGODB DRIVER] Warning: cursor.count is deprecated and will be removed in the next major version, please use `collection.estimatedDocumentCount` or `collection.countDocuments` instead 
{"name":"web","hostname":"8cac49fe42d1","pid":175,"level":40,"err":{"message":"cursor.count is deprecated and will be removed in the next major version, please use `collection.estimatedDocumentCount` or `collection.countDocuments` instead ","name":"Warning","stack":"Warning: cursor.count is deprecated and will be removed in the next major version, please use `collection.estimatedDocumentCount` or `collection.countDocuments` instead \n    at emitWarning (/overleaf/node_modules/mongodb-legacy/node_modules/mongodb/lib/utils.js:856:20)\n    at emitWarningOnce (/overleaf/node_modules/mongodb-legacy/node_modules/mongodb/lib/utils.js:869:16)\n    at LegacyFindCursor.count (/overleaf/node_modules/mongodb-legacy/node_modules/mongodb/lib/cursor/find_cursor.js:94:37)\n    at LegacyFindCursor.count (/overleaf/node_modules/mongodb-legacy/src/legacy_wrappers/cursors.js:25:34)\n    at Object.countActiveUsers (/overleaf/services/web/app/src/Features/User/UserHandler.js:23:6)\n    at publishActiveUsersMetric (/overleaf/services/web/app/src/infrastructure/SiteAdminHandler.js:54:6)\n    at Object.initialise (/overleaf/services/web/app/src/infrastructure/SiteAdminHandler.js:79:7)\n    at file:///overleaf/services/web/app.mjs:79:32\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","info":{},"code":"MONGODB DRIVER"},"msg":"Warning details","time":"2024-11-28T08:29:11.960Z","v":0}
{"name":"web","hostname":"8cac49fe42d1","pid":175,"level":40,"offset":669,"msg":"slow event loop","time":"2024-11-28T12:00:46.987Z","v":0}
{"name":"web","hostname":"8cac49fe42d1","pid":175,"level":40,"offset":210,"msg":"slow event loop","time":"2024-11-28T17:47:40.952Z","v":0}
{"name":"web","hostname":"8cac49fe42d1","pid":175,"level":40,"offset":362,"msg":"slow event loop","time":"2024-11-28T20:28:07.020Z","v":0}
```

**Comment by mlevans0** [comment]
The error you are seeing normally relates to an issue with communication between your browser and the real-time service within Overleaf. The proxy may be involved, so if you would like to test this, it would be useful to know whether you still have issues when the proxy isn't involved. 

Otherwise, it would be useful if we could see any logs that the real-time service is producing or that are visible from the browser's developer console. Another source of information would be the messages that are sent back and forth on the WebSocket, which should be visible in the network tab of the browser by filtering to WebSocket requests (may be written as ws depending on the browser). Any other servers or proxies that sit between your instance and the browser might also be involved, so if there's anything specific about those that you are aware of, then that information would be helpful, too.

**Comment by mlevans0** [comment]
Hey there! As there hasn't been any recent comments or activity on this issue since Jan 6, we’re going to close it to keep our tracker focused on the most active and current issues/questions.

If you’re still experiencing this issue and would like to keep it open, please verify the issue is present on the latest version of Overleaf CE and leave a comment to re-open. Thanks!
