### ISSUE TITLE
Overleaf Sending Email Failed

### ISSUE THREAD

**Issue by simon4477** [overleaf/overleaf#1290]
I have a custom SMTP using which I am able to send emails. However, with Overleaf CE 5, I get the following error. I have checked SMTP the configuration, it is all correct in `config/variables.env`. The SMTP server is also working fine as I am able to send emails via other applications.

```
DEBUG Sending mail using SMTP/6.9.9[client:6.9.9]
DEBUG [XqvxEbgc0Pg] Resolved <SMTP HOST> as <SMTP_IP> [cache miss]
INFO  [XqvxEbgc0Pg] Connection established to <SMTP_IP>:587
INFO  [XqvxEbgc0Pg] Connection upgraded with STARTTLS
DEBUG [XqvxEbgc0Pg] SMTP handshake finished
INFO  [XqvxEbgc0Pg] User "<SMTP_USER>" authenticated
INFO  Sending message <681a437d-8fa2-4e0b-e13d-ccdf0af7fcdd@localhost> to <EMAIL_ADDRESS>
DEBUG [XqvxEbgc0Pg] Closing connection to the server using "end"
ERROR Send error for <681a437d-8fa2-4e0b-e13d-ccdf0af7fcdd@localhost>: Mail command failed: 550 5.7.1 Sending from domain  is not allowed
ERROR Send Error: Mail command failed: 550 5.7.1 Sending from domain  is not allowed
{"name":"web","hostname":"2c16be564508","pid":201,"level":40,"err":{"message":"error sending message","name":"OError","stack":"OError: error sending message
    at Object.sendEmail (/overleaf/services/web/app/src/Features/Email/EmailSender.js:109:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.sendEmail (/overleaf/services/web/app/src/Features/Email/EmailHandler.js:26:3)
    at async Object.registerNewUserAndSendActivationEmail (/overleaf/services/web/app/src/Features/User/UserRegistrationHandler.js:116:5)
caused by:
    Error: Mail command failed: 550 5.7.1 Sending from domain  is not allowed
        at SMTPConnection._formatError (/overleaf/node_modules/nodemailer/lib/smtp-connection/index.js:790:19)
        at SMTPConnection._actionMAIL (/overleaf/node_modules/nodemailer/lib/smtp-connection/index.js:1594:34)
        at SMTPConnection.<anonymous> (/overleaf/node_modules/nodemailer/lib/smtp-connection/index.js:1063:18)
        at SMTPConnection._processResponse (/overleaf/node_modules/nodemailer/lib/smtp-connection/index.js:969:20)
        at SMTPConnection._onData (/overleaf/node_modules/nodemailer/lib/smtp-connection/index.js:755:14)
        at SMTPConnection._onSocketData (/overleaf/node_modules/nodemailer/lib/smtp-connection/index.js:193:44)
        at TLSSocket.emit (node:events:517:28)
        at TLSSocket.emit (node:domain:489:12)
        at addChunk (node:internal/streams/readable:368:12)
        at readableAddChunk (node:internal/streams/readable:341:9)","info":{}},"msg":"failed to send activation email","time":"xxxxxxxxxxxxxxxxxxxxxxxxx","v":0}
INFO  [XqvxEbgc0Pg] Connection closed
```

What does it mean and how to resolve it?
```
Error: Mail command failed: 550 5.7.1 Sending from domain is not allowed
```

**Comment by simon4477** [comment]
Issue solved.

**Comment by simon4477** [comment]
Issue solved.
