### ISSUE TITLE
Opening project never finishes. "socket hang up" Error

### ISSUE THREAD

**Issue by xeon-j** [overleaf/overleaf#301]
When I tries to open a project from web page, the project loading page is shown up and the loading never finishes, just saying "Lost Connection.Reconnecting in X secs." over and over.

This is how I installed sharelatex:
1. Prepare KVM guest with clean installation of Ubuntu 14.04.2 LTS. The network is public bridged (http://www.linux-kvm.org/page/Networking#public_bridge), so that I can reach the web server using public IP.
2. sharelatex is installed by following the production installation instruction:
https://github.com/sharelatex/sharelatex/wiki/Production-Installation-Instructions
3. By setting reverse proxy of apache2 (https://github.com/sharelatex/sharelatex/wiki/Apache-as-a-Reverse-Proxy), I got the web service working, and created the admin account.

I saw some issues discussed before, and knew that some of them are related to not properly invoking the required services.
I think this is not the case for me, and here is the evidence; the output of netstat -tulpn

```
tcp        0      0 127.0.0.1:3026          0.0.0.0:*               LISTEN      15015/node      
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      990/sshd        
tcp        0      0 127.0.0.1:3000          0.0.0.0:*               LISTEN      15021/node      
tcp        0      0 0.0.0.0:10843           0.0.0.0:*               LISTEN      15015/node      
tcp        0      0 127.0.0.1:3003          0.0.0.0:*               LISTEN      14999/node      
tcp        0      0 127.0.0.1:3005          0.0.0.0:*               LISTEN      14473/node      
tcp        0      0 127.0.0.1:3009          0.0.0.0:*               LISTEN      14459/node      
tcp        0      0 127.0.0.1:3010          0.0.0.0:*               LISTEN      15022/node      
tcp        0      0 127.0.0.1:3012          0.0.0.0:*               LISTEN      14481/node      
tcp        0      0 127.0.0.1:3013          0.0.0.0:*               LISTEN      14437/node      
tcp        0      0 127.0.0.1:3015          0.0.0.0:*               LISTEN      15005/node      
tcp        0      0 127.0.0.1:3016          0.0.0.0:*               LISTEN      14445/node      
tcp        0      0 127.0.0.1:27017         0.0.0.0:*               LISTEN      995/mongod      
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      15032/redis-server 
tcp6       0      0 :::80                   :::*                    LISTEN      14761/apache2   
tcp6       0      0 :::22                   :::*                    LISTEN      990/sshd        
```

... and this is the log of /var/log/sharelatex/web.log:

```
{"name":"web-sharelatex","hostname":"vm-sharelatex","pid":14523,"level":30,"req":{"url":"/project/5535ddddf3551777367f013c"
,"method":"GET","referrer":"http://141.223.91.109/project","remote-addr":"127.0.0.1","user-agent":"Mozilla/5.0 (Windows NT 
6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36"},"res":{"statusCode":200},"response-
time":1594,"msg":"http request","time":"2015-04-21T05:22:59.899Z","v":0}
{"name":"web-sharelatex","hostname":"vm-sharelatex","pid":14523,"level":30,"req":{"url":"/socket.io/socket.io.js","method":
"GET","referrer":"http://141.223.91.109/project/5535ddddf3551777367f013c","remote-addr":"127.0.0.1","user-agent":"Mozilla/5
.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36"},"res":{"statusCode":
304},"response-time":1362,"msg":"http request","time":"2015-04-21T05:23:01.350Z","v":0}
{"name":"web-sharelatex","hostname":"vm-sharelatex","pid":14523,"level":30,"req":{"url":"/socket.io/1/?t=1429593784812","me
thod":"GET","referrer":"http://141.223.91.109/project/5535ddddf3551777367f013c","remote-addr":"127.0.0.1","user-agent":"Moz
illa/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36"},"res":{"status
Code":200},"response-time":8,"msg":"http request","time":"2015-04-21T05:23:02.646Z","v":0}
{"name":"web-sharelatex","hostname":"vm-sharelatex","pid":14523,"level":50,"err":{"message":"socket hang up","name":"Error"
,"stack":"Error: socket hang up\n  at createHangUpError (http.js:1473:15)\n  at Socket.socketOnEnd [as onend] (http.js:1569
:23)\n  at Socket.g (events.js:180:16)\n  at Socket.emit (events.js:117:20)\n  at _stream_readable.js:944:16\n  at process.
_tickDomainCallback (node.js:492:13)\n","code":"ECONNRESET"},"url":"/socket.io/1/websocket/18IQR5OfM1UqXcWZbbtm","method":"
GET","msg":"error passed to top level next middlewear","time":"2015-04-21T05:23:02.980Z","v":0}
{"name":"web-sharelatex","hostname":"vm-sharelatex","pid":14523,"level":30,"req":{"url":"/socket.io/1/xhr-polling/18IQR5OfM
1UqXcWZbbtm?t=1429593795249","method":"GET","referrer":"http://141.223.91.109/project/5535ddddf3551777367f013c","remote-add
r":"127.0.0.1","user-agent":"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.10
1 Safari/537.36"},"res":{"statusCode":200},"response-time":5,"msg":"http request","time":"2015-04-21T05:23:13.083Z","v":0}
{"name":"web-sharelatex","hostname":"vm-sharelatex","pid":14523,"level":50,"err":{"message":"Forbidden","name":"Error","sta
ck":"Error: Forbidden\n  at Object.exports.error (/var/www/sharelatex/web/node_modules/express/node_modules/connect/lib/uti
ls.js:62:13)\n  at /var/www/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/csrf.js:55:41\n  at Obj
ect.handle (/var/www/sharelatex/web/app/js/infrastructure/Server.js:113:14)\n  at next (/var/www/sharelatex/web/node_module
s/express/node_modules/connect/lib/proto.js:190:15)\n  at Object.handle (/var/www/sharelatex/web/app/js/infrastructure/Serv
er.js:103:14)\n  at next (/var/www/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)\n  at next
 (/var/www/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/session.js:312:9)\n  at /var/www/sharela
tex/web/node_modules/express/node_modules/connect/lib/middleware/session.js:336:9\n  at /var/www/sharelatex/web/node_module
s/connect-redis/lib/connect-redis.js:102:14\n  at try_callback (/var/www/sharelatex/web/node_modules/redis-sharelatex/node_
modules/redis/index.js:592:9)\n  at RedisClient.return_reply (/var/www/sharelatex/web/node_modules/redis-sharelatex/node_mo
dules/redis/index.js:685:13)\n  at ReplyParser.<anonymous> (/var/www/sharelatex/web/node_modules/redis-sharelatex/node_modu
les/redis/index.js:321:14)\n  at ReplyParser.emit (events.js:95:17)\n  at ReplyParser.send_reply (/var/www/sharelatex/web/n
ode_modules/redis-sharelatex/node_modules/redis/lib/parser/javascript.js:300:10)\n  at ReplyParser.execute (/var/www/sharel
atex/web/node_modules/redis-sharelatex/node_modules/redis/lib/parser/javascript.js:203:22)\n  at RedisClient.on_data (/var/
www/sharelatex/web/node_modules/redis-sharelatex/node_modules/redis/index.js:547:27)\n  at Socket.<anonymous> (/var/www/sha
relatex/web/node_modules/redis-sharelatex/node_modules/redis/index.js:102:14)\n  at Socket.emit (events.js:95:17)\n  at Soc
ket.<anonymous> (_stream_readable.js:765:14)\n  at Socket.emit (events.js:92:17)\n  at emitReadable_ (_stream_readable.js:4
27:10)\n  at emitReadable (_stream_readable.js:423:5)\n  at readableAddChunk (_stream_readable.js:166:9)\n  at Socket.Reada
ble.push (_stream_readable.js:128:10)\n  at TCP.onread (net.js:529:21)\n","status":403},"url":"/socket.io/1/xhr-polling/18I
QR5OfM1UqXcWZbbtm?t=1429593795370","method":"POST","msg":"error passed to top level next middlewear","time":"2015-04-21T05:
23:13.198Z","v":0}
```

I do not know why even a clean installation is not working.

**Comment by xeon-j** [comment]
Okay, I just run firefox directly in the VM to see whether apache2 reverse proxy has the problem.
By accessing through http://127.0.0.1:3000/ it has no problem at all.
So I removed apache2 and just followed the instruction on using nginx (https://github.com/sharelatex/sharelatex/wiki/Nginx-as-a-Reverse-Proxy).
Problem solved.

**Comment by psxlover** [comment]
For reverse proxy on apache 2.4 and sharelatex 1.4 you'll need to enable mod_proxy, mod_proxy_http and mod_proxy_wstunnel and use this:
```
<VirtualHost *:80>
    ServerName [[[INSERT YOUR HOSTNAME HERE]]]
    ProxyPreserveHost On

    ProxyPass /socket.io/1/websocket ws://localhost:3000/socket.io/1/websocket
    ProxyPassReverse /socket.io/1/websocket ws://localhost:3000/socket.io/1/websocket

    ProxyPass / http://localhost:3000/
    ProxyPassReverse / http://localhost:3000/
</VirtualHost>
```

**Comment by the-nic** [comment]
Thanks, the solution provided by @psxlover works!

**Comment by dudheit314** [comment]
I get a similar error using apache2 with the proposed configuration. Examining the network requests brings up a 403 Forbidden error during the post query to
```
http://latex.domain.com/socket.io/1/xhr-polling/gsh_JRFHP3NJJxi6Tn8p?t=1438702731996
```
Any ideas?

**Comment by henryoswald** [comment]
Do you have avast antivirus installed?

On Tue, Aug 4, 2015 at 4:44 PM, dudheit314 <notifications@github.com> wrote:

> I get a similar error using apache2 with the proposed configuration.
> Examining the network requests brings up a 403 Forbidden error during the
> post query to
>
> http://latex.domain.com/socket.io/1/xhr-polling/gsh_JRFHP3NJJxi6Tn8p?t=1438702731996
>
> Any ideas?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sharelatex/sharelatex/issues/301#issuecomment-127654567>
> .
>



-- 
Henry Oswald
shareLaTeX.com co-founder

**Comment by quintard** [comment]
Thanks, the solution provided by @psxlover works for me also
with sharelatex v0.1.4 / apache 2.4.6 
( => the following line :
LoadModule proxy_wstunnel_module modules/mod_proxy_wstunnel.so
was missing in the file /etc/httpd/conf.modules.d/00-proxy.conf.
I added this line and restarted httpd, after everything worked just fine.)

**Comment by hrjakobsen** [comment]
Hi! The recommended way to run Overleaf Community Edition is now with Docker, using the [Overleaf Toolkit](https://github.com/overleaf/toolkit). I'll close this issue, as it is based on old build instructions, but please open a new issue if you face problems using Overleaf Toolkit.
