### ISSUE TITLE
Sharelatex builds documents but fails to preview in standalone

### ISSUE THREAD

**Issue by ajira86** [overleaf/overleaf#407]
I have a docker container of Sharelatex which is working like a charm.

But since my last container restart the built-in preview stops to work. The error message is : "Sorry, something went wrong and your project could not be compiled. Please try again in a few moments."

If I choose the to download the PDF immediately, he is well compiled. But I'm not an expert of the technologies behind sharelatex. Could someone help me to debug this ?

I tried to find some logs but there are plenty of files under /var/log/sharelatex which are not really easy to read. I think clsi.log is interesting. Here a trace of what happening during generation:

```
Executing (default): SELECT * FROM `Projects` WHERE `Projects`.`project_id`='56d5909594cc834d006400c2' LIMIT 1;
Executing (default): UPDATE `Projects` SET `project_id`='56d5909594cc834d006400c2',`lastAccessed`='2016-03-29 20:31:28',`id`=24,`createdAt`='2016-03-29 20:19:35',`updatedAt`='2016-03-29 20:31:28' WHERE `id`=24
{"name":"clsi","hostname":"63eb9548f5be","pid":69,"level":30,"project_id":"56d5909594cc834d006400c2","msg":"starting compile","time":"2016-03-29T20:31:28.028Z","v":0}
{"name":"clsi","hostname":"63eb9548f5be","pid":69,"level":30,"directory":"/var/lib/sharelatex/data/compiles/56d5909594cc834d006400c2","msg":"getting output files","time":"2016-03-29T20:31:28.028Z","v":0}
{"name":"clsi","hostname":"63eb9548f5be","pid":69,"level":30,"args":["/var/lib/sharelatex/data/compiles/56d5909594cc834d006400c2","-name",".cache","-prune","-o","-type","f","-print"],"msg":"running find command","time":"2016-03-29T20:31:28.028Z","v":0}
Executing (default): SELECT * FROM `UrlCaches` WHERE `UrlCaches`.`url`='http://localhost:3009/project/56d5909594cc834d006400c2/file/56d5909594cc834d006400c5' AND `UrlCaches`.`project_id`='56d5909594cc834d006400c2' LIMIT 1;
{"name":"clsi","hostname":"63eb9548f5be","pid":69,"level":30,"url":"http://localhost:3009/project/56d5909594cc834d006400c2/file/56d5909594cc834d006400c5","lastModified":"2016-03-01T12:52:37.000Z","msg":"URL is up to date in cache","time":"2016-03-29T20:31:28.037Z","v":0}
{"name":"clsi","hostname":"63eb9548f5be","pid":69,"level":30,"project_id":"56d5909594cc834d006400c2","time_taken":10,"msg":"written files to disk","time":"2016-03-29T20:31:28.038Z","v":0}
{"name":"clsi","hostname":"63eb9548f5be","pid":69,"level":30,"directory":"/var/lib/sharelatex/data/compiles/56d5909594cc834d006400c2","compiler":"pdflatex","timeout":60000,"mainFile":"main.tex","msg":"starting compile","time":"2016-03-29T20:31:28.038Z","v":0}
{"name":"clsi","hostname":"63eb9548f5be","pid":69,"level":30,"project_id":"56d5909594cc834d006400c2","command":["latexmk","-cd","-f","-jobname=output","-auxdir=/var/lib/sharelatex/data/compiles/56d5909594cc834d006400c2","-outdir=/var/lib/sharelatex/data/compiles/56d5909594cc834d006400c2","-pdf","-e","$pdflatex='pdflatex -synctex=1 -interaction=batchmode %O %S'","/var/lib/sharelatex/data/compiles/56d5909594cc834d006400c2/main.tex"],"directory":"/var/lib/sharelatex/data/compiles/56d5909594cc834d006400c2","msg":"running command","time":"2016-03-29T20:31:28.038Z","v":0}
{"name":"clsi","hostname":"63eb9548f5be","pid":69,"level":40,"msg":"timeouts and sandboxing are not enabled with CommandRunner","time":"2016-03-29T20:31:28.039Z","v":0}
Latexmk: This is Latexmk, John Collins, 5 February 2015, version: 4.43a.
Latexmk: Changing directory to '/var/lib/sharelatex/data/compiles/56d5909594cc834d006400c2/'
Rule 'pdflatex': File changes, etc:
   Non-existent destination files:
      '/var/lib/sharelatex/data/compiles/56d5909594cc834d006400c2/output.pdf'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex -synctex=1 -interaction=batchmode  -recorder -output-directory="/var/lib/sharelatex/data/compiles/56d5909594cc834d006400c2" --jobname="output"  "main.tex"'
------------
Latexmk: applying rule 'pdflatex'...
This is pdfTeX, Version 3.1415926-2.5-1.40.14 (TeX Live 2013/Debian)
 restricted \write18 enabled.
entering extended mode

SyncTeX written on /var/lib/sharelatex/data/compiles/56d5909594cc834d006400c2/output.synctex.gz.'output.fls' and '/var/lib/sharelatex/data/compiles/56d5909594cc834d006400c2/output.fls' are identical (not copied) at /usr/local/texlive/2014/bin/x86_64-linux//latexmk line 6814.
Latexmk: Found input bbl file 'output.bbl'
Latexmk: Found input bbl file 'output.bbl'
Latexmk: Log file says output to 'output.pdf'
Latexmk: ===For rule 'pdflatex', actual output 'output.pdf'
       ======appears not to match expected output '/var/lib/sharelatex/data/compiles/56d5909594cc834d006400c2/output.pdf'
Latexmk: Found bibliography file(s) [references.bib]
Latexmk: Undoing directory change
Latexmk: All targets (/var/lib/sharelatex/data/compiles/56d5909594cc834d006400c2/output.pdf) are up-to-date
{"name":"clsi","hostname":"63eb9548f5be","pid":69,"level":30,"project_id":"56d5909594cc834d006400c2","time_taken":441,"msg":"done compile","time":"2016-03-29T20:31:28.479Z","v":0}
{"name":"clsi","hostname":"63eb9548f5be","pid":69,"level":30,"directory":"/var/lib/sharelatex/data/compiles/56d5909594cc834d006400c2","msg":"getting output files","time":"2016-03-29T20:31:28.479Z","v":0}
{"name":"clsi","hostname":"63eb9548f5be","pid":69,"level":30,"args":["/var/lib/sharelatex/data/compiles/56d5909594cc834d006400c2","-name",".cache","-prune","-o","-type","f","-print"],"msg":"running find command","time":"2016-03-29T20:31:28.479Z","v":0}
{"name":"clsi","hostname":"63eb9548f5be","pid":69,"level":30,"cache":"/var/lib/sharelatex/data/compiles/56d5909594cc834d006400c2/.cache/clsi","dir":"153c411a6b6","msg":"removed expired cache dir","time":"2016-03-29T20:31:28.488Z","v":0}
{"name":"clsi","hostname":"63eb9548f5be","pid":69,"level":30,"args":["--linearize","/var/lib/sharelatex/data/compiles/56d5909594cc834d006400c2/output.pdf","/var/lib/sharelatex/data/compiles/56d5909594cc834d006400c2/.cache/clsi/153c412eee6/output.pdf.opt"],"msg":"running qpdf command","time":"2016-03-29T20:31:28.496Z","v":0}
{"name":"clsi","hostname":"63eb9548f5be","pid":69,"level":40,"err":{"message":"spawn ENOENT","name":"Error","stack":"Error: spawn ENOENT\n    at errnoException (child_process.js:1011:11)\n    at Process.ChildProcess._handle.onexit (child_process.js:802:34)","code":"ENOENT","errno":"ENOENT","syscall":"spawn"},"args":["--linearize","/var/lib/sharelatex/data/compiles/56d5909594cc834d006400c2/output.pdf","/var/lib/sharelatex/data/compiles/56d5909594cc834d006400c2/.cache/clsi/153c412eee6/output.pdf.opt"],"msg":"qpdf failed","time":"2016-03-29T20:31:28.501Z","v":0}
{"name":"clsi","hostname":"63eb9548f5be","pid":69,"level":40,"code":-1,"args":["--linearize","/var/lib/sharelatex/data/compiles/56d5909594cc834d006400c2/output.pdf","/var/lib/sharelatex/data/compiles/56d5909594cc834d006400c2/.cache/clsi/153c412eee6/output.pdf.opt"],"msg":"qpdf returned error","time":"2016-03-29T20:31:28.502Z","v":0}
{"name":"clsi","hostname":"63eb9548f5be","pid":69,"level":30,"req":{"url":"/project/56d5909594cc834d006400c2/compile","method":"POST","remote-addr":"127.0.0.1","content-length":"1493"},"res":{"statusCode":200},"response-time":489,"msg":"http request","time":"2016-03-29T20:31:28.508Z","v":0}
{"name":"clsi","hostname":"63eb9548f5be","pid":69,"level":30,"req":{"url":"/project/56d5909594cc834d006400c2/output/output.log","method":"GET","remote-addr":"127.0.0.1"},"res":{"statusCode":200},"response-time":2,"msg":"http request","time":"2016-03-29T20:31:28.528Z","v":0}
```

**Comment by apus2016** [comment]
I experience a similiar problem quite often, sometimes I press the compile button and only a second afterwards the perfectly fine preview of the last compilation run is gone and I get the error message, that an error occured and the document could not be compiled. This error happens quite a lot, although upon clicking the compile button one or two times more it compiles just fine. So this seems like a sharelatex issue. Please someone fix this, it is getting on my last nerve.

**Comment by das7pad** [comment]
Hello,

It looks like there was an issue with spawning `qpdf` for linearizing the PDF. This should be fixed in the latest version of Overleaf Community Edition or [Server Pro](https://www.overleaf.com/for/enterprises).

Greetings,
Jakob
