### ISSUE TITLE
DTrace-provider #error "<malloc.h> has been replaced by <stdlib.h>"

### ISSUE THREAD

**Issue by rubenverhoef** [overleaf/overleaf#409]
I have a problem compiling sharelatex. It is about the dtrace-provider in document-updater and docstore.

The error is: #error "<malloc.h> has been replaced by <stdlib.h>" Can someone help me?
I'm using:
FreeBSD 9.3
node 0.10.40
npm 2.14.7

```
Running "install:document-updater" task
document-updater already installed, skipping.
npm WARN package.json document-updater-sharelatex@0.1.4 No license field.
-
> dtrace-provider@0.2.4 install /root/sharelatex/document-updater/node_modules/logger-sharelatex/node_modules/bunyan/node_modules/dtrace-provider
> node-gyp rebuild

gmake: Entering directory '/root/sharelatex/document-updater/node_modules/logger-sharelatex/node_modules/bunyan/node_modules/dtrace-provider/build'
  ACTION binding_gyp_libusdt_target_build_libusdt .
Using node: /usr/local/bin/node
Building libusdt for x86_64
make[1]: Entering directory '/root/sharelatex/document-updater/node_modules/logger-sharelatex/node_modules/bunyan/node_modules/dtrace-provider/libusdt'
rm -f *.gch
rm -f *.o
rm -f libusdt.a
rm -f test_usdt
rm -f test_usdt32
rm -f test_usdt64
gcc -O2 -Wno-error=unknown-pragmas -I/usr/src/sys/cddl/compat/opensolaris -I/usr/src/sys/cddl/contrib/opensolaris/uts/common   -c -o usdt.o usdt.c
gcc -O2 -Wno-error=unknown-pragmas -I/usr/src/sys/cddl/compat/opensolaris -I/usr/src/sys/cddl/contrib/opensolaris/uts/common   -c -o usdt_dof_file.o usdt_dof_file.c
gcc -O2 -Wno-error=unknown-pragmas -I/usr/src/sys/cddl/compat/opensolaris -I/usr/src/sys/cddl/contrib/opensolaris/uts/common -o usdt_tracepoints.o -c usdt_tracepoints_x86_64.s
gcc -O2 -Wno-error=unknown-pragmas -I/usr/src/sys/cddl/compat/opensolaris -I/usr/src/sys/cddl/contrib/opensolaris/uts/common   -c -o usdt_probe.o usdt_probe.c
gcc -O2 -Wno-error=unknown-pragmas -I/usr/src/sys/cddl/compat/opensolaris -I/usr/src/sys/cddl/contrib/opensolaris/uts/common   -c -o usdt_dof.o usdt_dof.c
gcc -O2 -Wno-error=unknown-pragmas -I/usr/src/sys/cddl/compat/opensolaris -I/usr/src/sys/cddl/contrib/opensolaris/uts/common   -c -o usdt_dof_sections.o usdt_dof_sections.c
rm -f libusdt.a
ar cru libusdt.a usdt.o usdt_dof_file.o usdt_tracepoints.o usdt_probe.o usdt_dof.o usdt_dof_sections.o
ranlib libusdt.a
make[1]: Leaving directory '/root/sharelatex/document-updater/node_modules/logger-sharelatex/node_modules/bunyan/node_modules/dtrace-provider/libusdt'
  TOUCH Release/obj.target/libusdt.stamp
  CXX(target) Release/obj.target/DTraceProviderBindings/dtrace_provider.o
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:9:24: warning: sys/dtrace.h: No such file or directory
In file included from ../dtrace_provider.h:20,
                 from ../dtrace_provider.cc:1:
/usr/include/malloc.h:3:2: error: #error "<malloc.h> has been replaced by <stdlib.h>"
DTraceProviderBindings.target.mk:93: recipe for target 'Release/obj.target/DTraceProviderBindings/dtrace_provider.o' failed
gmake: *** [Release/obj.target/DTraceProviderBindings/dtrace_provider.o] Error 1
gmake: Leaving directory '/root/sharelatex/document-updater/node_modules/logger-sharelatex/node_modules/bunyan/node_modules/dtrace-provider/build'


gyp ERR! build error
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System FreeBSD 9.3-RELEASE-p31
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/sharelatex/document-updater/node_modules/logger-sharelatex/node_modules/bunyan/node_modules/dtrace-provider
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! FreeBSD 9.3-RELEASE-p31
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.40
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! dtrace-provider@0.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dtrace-provider@0.2.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the dtrace-provider package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls dtrace-provider
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/sharelatex/document-updater/npm-debug.log
```

**Comment by rubenverhoef** [comment]
When I modified /.npm/dtrace-provider/0.2.4/package.tgz to the latest github version it builds without an error but when i start sharelatex i get:

    { [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
    { [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
    { [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }

**Comment by hrjakobsen** [comment]
Hi! The recommended way to run Overleaf Community Edition is now with Docker, using the [Overleaf Toolkit](https://github.com/overleaf/toolkit). I'll close this issue, as it is based on old build instructions, but please open a new issue if you face problems using Overleaf Toolkit.
