### ISSUE TITLE
Error: Cannot find module 'logger-sharelatex'

### ISSUE THREAD

**Issue by hanxue** [overleaf/overleaf#41]
Following the installation steps in the README file, and running `npm install` and `grunt install`, running `grunt run` results in this error:

```
$ grunt run
Running "concurrent:all" (concurrent) task
Running "bunyan" task
Running "bunyan" task
Running "bunyan" task


    Running "bunyan" task

Running "execute:document-updater" (execute) task
-> executing /Users/hanxue/Github/sharelatex/document-updater/app.js

Running "execute:web" (execute) task

>> 0 files and 0 calls executed (10ms)

Done, without errors.

Running "execute:filestore" (execute) task
-> executing /Users/hanxue/Github/sharelatex/filestore/app.js

module.js:333
    throw err;
          ^
Error: Cannot find module 'logger-sharelatex'
    at Function.Module._resolveFilename (module.js:331:15)
    at Function.Module._load (module.js:273:25)
    at Module.require (module.js:357:17)
    at require (module.js:373:17)
    at Object.<anonymous> (/Users/hanxue/Github/sharelatex/filestore/app.js:6:12)
    at Object.<anonymous> (/Users/hanxue/Github/sharelatex/filestore/app.js:151:4)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)
Warning: -> error 1 /Users/hanxue/Github/sharelatex/filestore/app.js (211ms) Use --force to continue.

Aborted due to warnings.
    Warning:  Use --force to continue.

        Aborted due to warnings.

Running "execute:clsi" (execute) task
-> executing /Users/hanxue/Github/sharelatex/clsi/app.js
```

**Comment by joannekoong** [comment]
I get a  /root/sharelatex/docstore/app.js error when I run grunt run:all after following the installation steps for the developer environment. Running grunt install:docstore gives

```
make: *** [Release/obj.target/DTraceProviderBindings/dtrace_provider.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Joanne/Desktop/iterate/sharelatex/docstore/node_modules/logger-sharelatex/node_modules/bunyan/node_modules/dtrace-provider
gyp ERR! node -v v0.12.3
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.3
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! dtrace-provider@0.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dtrace-provider@0.2.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the dtrace-provider package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls dtrace-provider
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Joanne/Desktop/iterate/sharelatex/docstore/npm-debug.log
```
that I can't seem to resolve. Googling tells me it's an error with the /DTraceProviderBindings part of the Bunyan package, but there doesn't seem to be a workaround for this yet. Any tips??
