### ISSUE TITLE
Spell checking doesn't work

### ISSUE THREAD

**Issue by marksnaith** [overleaf/overleaf#465]
After working fine for several months, spell checking seems to have stopped working. The error log reports the following:

"name":"spelling-sharelatex","hostname":"468d0cb3b523","pid":82,"level":50,"err":{"message":"connection to host dockerhost:27017 was destroyed","name":"MongoError","stack":"MongoError: connection to host dockerhost:27017 was destroyed\n    at Function.MongoError.create (/var/www/sharelatex/spelling/node_modules/mongojs/node_modules/mongodb-core/lib/error.js:29:11)\n    at isConnectionDead (/var/www/sharelatex/spelling/node_modules/mongojs/node_modules/mongodb-core/lib/cursor.js:414:25)\n    at nextFunction (/var/www/sharelatex/spelling/node_modules/mongojs/node_modules/mongodb-core/lib/cursor.js:537:8)\n    at Cursor.next (/var/www/sharelatex/spelling/node_modules/mongojs/node_modules/mongodb-core/lib/cursor.js:655:3)\n    at /var/www/sharelatex/spelling/node_modules/mongojs/lib/cursor.js:37:12\n    at apply (/var/www/sharelatex/spelling/node_modules/mongojs/node_modules/thunky/index.js:16:28)\n    at /var/www/sharelatex/spelling/node_modules/mongojs/node_modules/thunky/index.js:20:25\n    at /var/www/sharelatex/spelling/node_modules/mongojs/lib/cursor.js:14:7\n    at apply (/var/www/sharelatex/spelling/node_modules/mongojs/node_modules/thunky/index.js:16:28)\n    at /var/www/sharelatex/spelling/node_modules/mongojs/node_modules/thunky/index.js:27:3\n    at /var/www/sharelatex/spelling/node_modules/mongojs/lib/cursor.js:12:5\n    at run (/var/www/sharelatex/spelling/node_modules/mongojs/node_modules/thunky/index.js:13:3)\n    at null._get (/var/www/sharelatex/spelling/node_modules/mongojs/node_modules/thunky/index.js:27:3)\n    at Cursor.next (/var/www/sharelatex/spelling/node_modules/mongojs/lib/cursor.js:35:8)\n    at Collection.findOne (/var/www/sharelatex/spelling/node_modules/mongojs/lib/collection.js:49:32)\n    at Collection.findOne (/var/www/sharelatex/spelling/node_modules/mongojs/lib/collection.js:48:53)\n    at Object.module.exports.LearnedWordsManager.getLearnedWords (/var/www/sharelatex/spelling/app/js/LearnedWordsManager.js:45:37)\n    at Object.module.exports.SpellingAPIManager.runRequest (/var/www/sharelatex/spelling/app/js/SpellingAPIManager.js:28:36)\n    at module.exports.SpellingAPIController.check (/var/www/sharelatex/spelling/app/js/SpellingAPIController.js:18:33)\n    at Layer.handle [as handle_request](/var/www/sharelatex/spelling/node_modules/express/lib/router/layer.js:95:5)\n    at next (/var/www/sharelatex/spelling/node_modules/express/lib/router/route.js:131:13)\n    at Route.dispatch (/var/www/sharelatex/spelling/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request](/var/www/sharelatex/spelling/node_modules/express/lib/router/layer.js:95:5)\n    at /var/www/sharelatex/spelling/node_modules/express/lib/router/index.js:277:22\n    at param (/var/www/sharelatex/spelling/node_modules/express/lib/router/index.js:349:14)\n    at param (/var/www/sharelatex/spelling/node_modules/express/lib/router/index.js:365:14)\n    at Function.process_params (/var/www/sharelatex/spelling/node_modules/express/lib/router/index.js:410:3)\n    at next (/var/www/sharelatex/spelling/node_modules/express/lib/router/index.js:271:10)\n    at /var/www/sharelatex/spelling/node_modules/metrics-sharelatex/http.coffee:37:14\n    at Layer.handle [as handle_request](/var/www/sharelatex/spelling/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/var/www/sharelatex/spelling/node_modules/express/lib/router/index.js:312:13)\n    at /var/www/sharelatex/spelling/node_modules/express/lib/router/index.js:280:7\n    at Function.process_params (/var/www/sharelatex/spelling/node_modules/express/lib/router/index.js:330:12)\n    at next (/var/www/sharelatex/spelling/node_modules/express/lib/router/index.js:271:10)\n    at /var/www/sharelatex/spelling/node_modules/body-parser/lib/read.js:129:5\n    at invokeCallback (/var/www/sharelatex/spelling/node_modules/body-parser/node_modules/raw-body/index.js:262:16)\n    at done (/var/www/sharelatex/spelling/node_modules/body-parser/node_modules/raw-body/index.js:251:7)\n    at IncomingMessage.onEnd (/var/www/sharelatex/spelling/node_modules/body-parser/node_modules/raw-body/index.js:308:7)\n    at IncomingMessage.emit (events.js:92:17)\n    at _stream_readable.js:944:16\n    at process._tickCallback (node.js:458:13)"},"user_id":"577a5e045b5e4de00cfba23b","word_count":173,"msg":"error processing spelling request","time":"2016-09-01T11:08:13.761Z","v":0}
{"name":"spelling-sharelatex","hostname":"468d0cb3b523","pid":82,"level":30,"req":{"url":"/user/577a5e045b5e4de00cfba23b/check","method":"POST","referrer":"http://latex.arg.tech/project/57a05cbe7eba06f8173924de","remote-addr":"127.0.0.1","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.7 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.7","content-length":"1557"},"res":{"statusCode":500},"response-time":3,"msg":"http request","time":"2016-09-01T11:08:13.762Z","v":0}
{"name":"spelling-sharelatex","hostname":"468d0cb3b523","pid":82,"level":30,"rss":"96.59","heapTotal":"83.06","heapUsed":"36.33","msg":"process.memoryUsage()","time":"2016-09-01T11:08:54.896Z","v":0}
{"name":"spelling-sharelatex","hostname":"468d0cb3b523","pid":82,"level":30,"token":"5795ce2f79dfbc5e161e046a","word_count":16043,"msg":"running check","time":"2016-09-01T11:09:07.219Z","v":0}
{"name":"spelling-sharelatex","hostname":"468d0cb3b523","pid":82,"level":30,"user_token":"5795ce2f79dfbc5e161e046a","msg":"mongoCache miss","time":"2016-09-01T11:09:07.219Z","v":0}
{"name":"spelling-sharelatex","hostname":"468d0cb3b523","pid":82,"level":50,"err":{"message":"connection to host dockerhost:27017 was destroyed","name":"MongoError","stack":"MongoError: connection to host dockerhost:27017 was destroyed\n    at Function.MongoError.create (/var/www/sharelatex/spelling/node_modules/mongojs/node_modules/mongodb-core/lib/error.js:29:11)\n    at isConnectionDead (/var/www/sharelatex/spelling/node_modules/mongojs/node_modules/mongodb-core/lib/cursor.js:414:25)\n    at nextFunction (/var/www/sharelatex/spelling/node_modules/mongojs/node_modules/mongodb-core/lib/cursor.js:537:8)\n    at Cursor.next (/var/www/sharelatex/spelling/node_modules/mongojs/node_modules/mongodb-core/lib/cursor.js:655:3)\n    at /var/www/sharelatex/spelling/node_modules/mongojs/lib/cursor.js:37:12\n    at apply (/var/www/sharelatex/spelling/node_modules/mongojs/node_modules/thunky/index.js:16:28)\n    at /var/www/sharelatex/spelling/node_modules/mongojs/node_modules/thunky/index.js:20:25\n    at /var/www/sharelatex/spelling/node_modules/mongojs/lib/cursor.js:14:7\n    at apply (/var/www/sharelatex/spelling/node_modules/mongojs/node_modules/thunky/index.js:16:28)\n    at /var/www/sharelatex/spelling/node_modules/mongojs/node_modules/thunky/index.js:27:3\n    at /var/www/sharelatex/spelling/node_modules/mongojs/lib/cursor.js:12:5\n    at run (/var/www/sharelatex/spelling/node_modules/mongojs/node_modules/thunky/index.js:13:3)\n    at null._get (/var/www/sharelatex/spelling/node_modules/mongojs/node_modules/thunky/index.js:27:3)\n    at Cursor.next (/var/www/sharelatex/spelling/node_modules/mongojs/lib/cursor.js:35:8)\n    at Collection.findOne (/var/www/sharelatex/spelling/node_modules/mongojs/lib/collection.js:49:32)\n    at Collection.findOne (/var/www/sharelatex/spelling/node_modules/mongojs/lib/collection.js:48:53)\n    at Object.module.exports.LearnedWordsManager.getLearnedWords (/var/www/sharelatex/spelling/app/js/LearnedWordsManager.js:45:37)\n    at Object.module.exports.SpellingAPIManager.runRequest (/var/www/sharelatex/spelling/app/js/SpellingAPIManager.js:28:36)\n    at module.exports.SpellingAPIController.check (/var/www/sharelatex/spelling/app/js/SpellingAPIController.js:18:33)\n    at Layer.handle [as handle_request](/var/www/sharelatex/spelling/node_modules/express/lib/router/layer.js:95:5)\n    at next (/var/www/sharelatex/spelling/node_modules/express/lib/router/route.js:131:13)\n    at Route.dispatch (/var/www/sharelatex/spelling/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request](/var/www/sharelatex/spelling/node_modules/express/lib/router/layer.js:95:5)\n    at /var/www/sharelatex/spelling/node_modules/express/lib/router/index.js:277:22\n    at param (/var/www/sharelatex/spelling/node_modules/express/lib/router/index.js:349:14)\n    at param (/var/www/sharelatex/spelling/node_modules/express/lib/router/index.js:365:14)\n    at Function.process_params (/var/www/sharelatex/spelling/node_modules/express/lib/router/index.js:410:3)\n    at next (/var/www/sharelatex/spelling/node_modules/express/lib/router/index.js:271:10)\n    at /var/www/sharelatex/spelling/node_modules/metrics-sharelatex/http.coffee:37:14\n    at Layer.handle [as handle_request](/var/www/sharelatex/spelling/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/var/www/sharelatex/spelling/node_modules/express/lib/router/index.js:312:13)\n    at /var/www/sharelatex/spelling/node_modules/express/lib/router/index.js:280:7\n    at Function.process_params (/var/www/sharelatex/spelling/node_modules/express/lib/router/index.js:330:12)\n    at next (/var/www/sharelatex/spelling/node_modules/express/lib/router/index.js:271:10)\n    at /var/www/sharelatex/spelling/node_modules/body-parser/lib/read.js:129:5\n    at invokeCallback (/var/www/sharelatex/spelling/node_modules/body-parser/node_modules/raw-body/index.js:262:16)\n    at done (/var/www/sharelatex/spelling/node_modules/body-parser/node_modules/raw-body/index.js:251:7)\n    at IncomingMessage.onEnd (/var/www/sharelatex/spelling/node_modules/body-parser/node_modules/raw-body/index.js:308:7)\n    at IncomingMessage.emit (events.js:92:17)\n    at _stream_readable.js:944:16\n    at process._tickCallback (node.js:458:13)"},"user_id":"5795ce2f79dfbc5e161e046a","word_count":16043,"msg":"error processing spelling request","time":"2016-09-01T11:09:07.220Z","v":0}
"name":"spelling-sharelatex","hostname":"468d0cb3b523","pid":82,"level":50,"err":{"message":"connection to host dockerhost:27017 was destroyed","name":"MongoError","stack":"MongoError: connection to host dockerhost:27017 was destroyed\n    at Function.MongoError.create (/var/www/sharelatex/spelling/node_modules/mongojs/node_modules/mongodb-core/lib/error.js:29:11)\n    at isConnectionDead (/var/www/sharelatex/spelling/node_modules/mongojs/node_modules/mongodb-core/lib/cursor.js:414:25)\n    at nextFunction (/var/www/sharelatex/spelling/node_modules/mongojs/node_modules/mongodb-core/lib/cursor.js:537:8)\n    at Cursor.next (/var/www/sharelatex/spelling/node_modules/mongojs/node_modules/mongodb-core/lib/cursor.js:655:3)\n    at /var/www/sharelatex/spelling/node_modules/mongojs/lib/cursor.js:37:12\n    at apply (/var/www/sharelatex/spelling/node_modules/mongojs/node_modules/thunky/index.js:16:28)\n    at /var/www/sharelatex/spelling/node_modules/mongojs/node_modules/thunky/index.js:20:25\n    at /var/www/sharelatex/spelling/node_modules/mongojs/lib/cursor.js:14:7\n    at apply (/var/www/sharelatex/spelling/node_modules/mongojs/node_modules/thunky/index.js:16:28)\n    at /var/www/sharelatex/spelling/node_modules/mongojs/node_modules/thunky/index.js:27:3\n    at /var/www/sharelatex/spelling/node_modules/mongojs/lib/cursor.js:12:5\n    at run (/var/www/sharelatex/spelling/node_modules/mongojs/node_modules/thunky/index.js:13:3)\n    at null._get (/var/www/sharelatex/spelling/node_modules/mongojs/node_modules/thunky/index.js:27:3)\n    at Cursor.next (/var/www/sharelatex/spelling/node_modules/mongojs/lib/cursor.js:35:8)\n    at Collection.findOne (/var/www/sharelatex/spelling/node_modules/mongojs/lib/collection.js:49:32)\n    at Collection.findOne (/var/www/sharelatex/spelling/node_modules/mongojs/lib/collection.js:48:53)\n    at Object.module.exports.LearnedWordsManager.getLearnedWords (/var/www/sharelatex/spelling/app/js/LearnedWordsManager.js:45:37)\n    at Object.module.exports.SpellingAPIManager.runRequest (/var/www/sharelatex/spelling/app/js/SpellingAPIManager.js:28:36)\n    at module.exports.SpellingAPIController.check (/var/www/sharelatex/spelling/app/js/SpellingAPIController.js:18:33)\n    at Layer.handle [as handle_request](/var/www/sharelatex/spelling/node_modules/express/lib/router/layer.js:95:5)\n    at next (/var/www/sharelatex/spelling/node_modules/express/lib/router/route.js:131:13)\n    at Route.dispatch (/var/www/sharelatex/spelling/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request](/var/www/sharelatex/spelling/node_modules/express/lib/router/layer.js:95:5)\n    at /var/www/sharelatex/spelling/node_modules/express/lib/router/index.js:277:22\n    at param (/var/www/sharelatex/spelling/node_modules/express/lib/router/index.js:349:14)\n    at param (/var/www/sharelatex/spelling/node_modules/express/lib/router/index.js:365:14)\n    at Function.process_params (/var/www/sharelatex/spelling/node_modules/express/lib/router/index.js:410:3)\n    at next (/var/www/sharelatex/spelling/node_modules/express/lib/router/index.js:271:10)\n    at /var/www/sharelatex/spelling/node_modules/metrics-sharelatex/http.coffee:37:14\n    at Layer.handle [as handle_request](/var/www/sharelatex/spelling/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/var/www/sharelatex/spelling/node_modules/express/lib/router/index.js:312:13)\n    at /var/www/sharelatex/spelling/node_modules/express/lib/router/index.js:280:7\n    at Function.process_params (/var/www/sharelatex/spelling/node_modules/express/lib/router/index.js:330:12)\n    at next (/var/www/sharelatex/spelling/node_modules/express/lib/router/index.js:271:10)\n    at /var/www/sharelatex/spelling/node_modules/body-parser/lib/read.js:129:5\n    at invokeCallback (/var/www/sharelatex/spelling/node_modules/body-parser/node_modules/raw-body/index.js:262:16)\n    at done (/var/www/sharelatex/spelling/node_modules/body-parser/node_modules/raw-body/index.js:251:7)\n    at IncomingMessage.onEnd (/var/www/sharelatex/spelling/node_modules/body-parser/node_modules/raw-body/index.js:308:7)\n    at IncomingMessage.emit (events.js:92:17)\n    at _stream_readable.js:944:16\n    at process._tickCallback (node.js:458:13)"},"user_id":"577a5e045b5e4de00cfba23b","word_count":173,"msg":"error processing spelling request","time":"2016-09-01T11:08:13.761Z","v":0}
{"name":"spelling-sharelatex","hostname":"468d0cb3b523","pid":82,"level":30,"req":{"url":"/user/577a5e045b5e4de00cfba23b/check","method":"POST","referrer":"http://latex.arg.tech/project/57a05cbe7eba06f8173924de","remote-addr":"127.0.0.1","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.7 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.7","content-length":"1557"},"res":{"statusCode":500},"response-time":3,"msg":"http request","time":"2016-09-01T11:08:13.762Z","v":0}
{"name":"spelling-sharelatex","hostname":"468d0cb3b523","pid":82,"level":30,"rss":"96.59","heapTotal":"83.06","heapUsed":"36.33","msg":"process.memoryUsage()","time":"2016-09-01T11:08:54.896Z","v":0}
{"name":"spelling-sharelatex","hostname":"468d0cb3b523","pid":82,"level":30,"token":"5795ce2f79dfbc5e161e046a","word_count":16043,"msg":"running check","time":"2016-09-01T11:09:07.219Z","v":0}
{"name":"spelling-sharelatex","hostname":"468d0cb3b523","pid":82,"level":30,"user_token":"5795ce2f79dfbc5e161e046a","msg":"mongoCache miss","time":"2016-09-01T11:09:07.219Z","v":0}
{"name":"spelling-sharelatex","hostname":"468d0cb3b523","pid":82,"level":50,"err":{"message":"connection to host dockerhost:27017 was destroyed","name":"MongoError","stack":"MongoError: connection to host dockerhost:27017 was destroyed\n    at Function.MongoError.create (/var/www/sharelatex/spelling/node_modules/mongojs/node_modules/mongodb-core/lib/error.js:29:11)\n    at isConnectionDead (/var/www/sharelatex/spelling/node_modules/mongojs/node_modules/mongodb-core/lib/cursor.js:414:25)\n    at nextFunction (/var/www/sharelatex/spelling/node_modules/mongojs/node_modules/mongodb-core/lib/cursor.js:537:8)\n    at Cursor.next (/var/www/sharelatex/spelling/node_modules/mongojs/node_modules/mongodb-core/lib/cursor.js:655:3)\n    at /var/www/sharelatex/spelling/node_modules/mongojs/lib/cursor.js:37:12\n    at apply (/var/www/sharelatex/spelling/node_modules/mongojs/node_modules/thunky/index.js:16:28)\n    at /var/www/sharelatex/spelling/node_modules/mongojs/node_modules/thunky/index.js:20:25\n    at /var/www/sharelatex/spelling/node_modules/mongojs/lib/cursor.js:14:7\n    at apply (/var/www/sharelatex/spelling/node_modules/mongojs/node_modules/thunky/index.js:16:28)\n    at /var/www/sharelatex/spelling/node_modules/mongojs/node_modules/thunky/index.js:27:3\n    at /var/www/sharelatex/spelling/node_modules/mongojs/lib/cursor.js:12:5\n    at run (/var/www/sharelatex/spelling/node_modules/mongojs/node_modules/thunky/index.js:13:3)\n    at null._get (/var/www/sharelatex/spelling/node_modules/mongojs/node_modules/thunky/index.js:27:3)\n    at Cursor.next (/var/www/sharelatex/spelling/node_modules/mongojs/lib/cursor.js:35:8)\n    at Collection.findOne (/var/www/sharelatex/spelling/node_modules/mongojs/lib/collection.js:49:32)\n    at Collection.findOne (/var/www/sharelatex/spelling/node_modules/mongojs/lib/collection.js:48:53)\n    at Object.module.exports.LearnedWordsManager.getLearnedWords (/var/www/sharelatex/spelling/app/js/LearnedWordsManager.js:45:37)\n    at Object.module.exports.SpellingAPIManager.runRequest (/var/www/sharelatex/spelling/app/js/SpellingAPIManager.js:28:36)\n    at module.exports.SpellingAPIController.check (/var/www/sharelatex/spelling/app/js/SpellingAPIController.js:18:33)\n    at Layer.handle [as handle_request](/var/www/sharelatex/spelling/node_modules/express/lib/router/layer.js:95:5)\n    at next (/var/www/sharelatex/spelling/node_modules/express/lib/router/route.js:131:13)\n    at Route.dispatch (/var/www/sharelatex/spelling/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request](/var/www/sharelatex/spelling/node_modules/express/lib/router/layer.js:95:5)\n    at /var/www/sharelatex/spelling/node_modules/express/lib/router/index.js:277:22\n    at param (/var/www/sharelatex/spelling/node_modules/express/lib/router/index.js:349:14)\n    at param (/var/www/sharelatex/spelling/node_modules/express/lib/router/index.js:365:14)\n    at Function.process_params (/var/www/sharelatex/spelling/node_modules/express/lib/router/index.js:410:3)\n    at next (/var/www/sharelatex/spelling/node_modules/express/lib/router/index.js:271:10)\n    at /var/www/sharelatex/spelling/node_modules/metrics-sharelatex/http.coffee:37:14\n    at Layer.handle [as handle_request](/var/www/sharelatex/spelling/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/var/www/sharelatex/spelling/node_modules/express/lib/router/index.js:312:13)\n    at /var/www/sharelatex/spelling/node_modules/express/lib/router/index.js:280:7\n    at Function.process_params (/var/www/sharelatex/spelling/node_modules/express/lib/router/index.js:330:12)\n    at next (/var/www/sharelatex/spelling/node_modules/express/lib/router/index.js:271:10)\n    at /var/www/sharelatex/spelling/node_modules/body-parser/lib/read.js:129:5\n    at invokeCallback (/var/www/sharelatex/spelling/node_modules/body-parser/node_modules/raw-body/index.js:262:16)\n    at done (/var/www/sharelatex/spelling/node_modules/body-parser/node_modules/raw-body/index.js:251:7)\n    at IncomingMessage.onEnd (/var/www/sharelatex/spelling/node_modules/body-parser/node_modules/raw-body/index.js:308:7)\n    at IncomingMessage.emit (events.js:92:17)\n    at _stream_readable.js:944:16\n    at process._tickCallback (node.js:458:13)"},"user_id":"5795ce2f79dfbc5e161e046a","word_count":16043,"msg":"error processing spelling request","time":"2016-09-01T11:09:07.220Z","v":0}

We are using Docker, with mongo and reds on the host machine.

**Comment by mlevans0** [comment]
Hey there! As there hasn't been any recent comments or activity on this issue since September 2016, we’re going to close it to keep our tracker focused on the most active and current issues/questions.

If you’re still experiencing this issue and would like to keep it open, please verify the issue is present on the latest version of Overleaf CE and leave a comment to re-open. Thanks!
