### ISSUE TITLE
Can't edit .Tex

### ISSUE THREAD

**Issue by M-Gregoire** [overleaf/overleaf#485]
Hello !
I've configured 2 dockers : mongodb and redis which are password protected.
I then launched : 

```
docker run -d \
  -v [PATH]/sharelatex:/var/lib/sharelatex \
  -p 81:80 \
  --name=shareLatex \
  --env SHARELATEX_SITE_URL=https://[DOMAIN]:81 \
  --env SHARELATEX_MONGO_URL=mongodb://admin:[PASSWORD]p@172.17.0.1/sharelatex \
  --env SHARELATEX_REDIS_HOST=172.17.0.1 \
  --env SHARELATEX_REDIS_PORT=6379 \
  --env SHARELATEX_REDIS_PASS=[PASSWORD] \
  sharelatex/sharelatex

```

The ShareLatex platform works perfeclty, I can create users/projects. But when I open a project, I have an error message : 

> Sorry, something went wrong opening this document. Please try again.

I'm working on this issue for 2 days so any help would be appreciated :).

Please find the log attached.

Thanks in advance

```
*** Running /etc/my_init.d/00_make_sharelatex_data_dirs.sh...
*** Running /etc/my_init.d/00_regen_sharelatex_secrets.sh...
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/00_set_docker_host_ipaddress.sh...
*** Running /etc/my_init.d/98_check_db_access.sh...
Checking can connect to mongo and redis
Loading "Gruntfile.coffee" tasks...ERROR
>> Error: ENOENT, no such file or directory 'check:redis'

Running "check:redis" task
Checking can connect to redis
OK.
Done, without errors.
Loading "Gruntfile.coffee" tasks...ERROR
>> Error: ENOENT, no such file or directory 'check:mongo'

Running "check:mongo" task
Checking can connect to mongoOK.
Done, without errors.
All checks passed
*** Running /etc/my_init.d/99_migrate.sh...
/usr/bin/node
/usr/bin/grunt
total 76
drwxr-xr-x.  2 root root  4096 Nov  6 14:18 .
drwxr-xr-x. 19 root root  4096 Oct 19 11:47 ..
-rw-r--r--.  1 root root  5074 Oct 19 11:33 1_move_doc_lines_to_doc_collection.coffee
-rw-r--r--.  1 root root  7679 Nov  6 14:18 1_move_doc_lines_to_doc_collection.js
-rw-r--r--.  1 root root  5936 Oct 19 11:33 2_doc_lines_delete_from_project.coffee
-rw-r--r--.  1 root root  9337 Nov  6 14:18 2_doc_lines_delete_from_project.js
-rw-r--r--.  1 root root 10606 Oct 19 11:33 3_pack_docHistory_collection.coffee
-rw-r--r--.  1 root root 15371 Nov  6 14:18 3_pack_docHistory_collection.js
-rw-r--r--.  1 root root   179 Oct 19 11:33 about_migrations.md
Initializing
Command-line options: --verbose

Reading "Gruntfile.coffee" Gruntfile...OK

Registering Gruntfile tasks.

Registering "grunt-bunyan" local Npm module tasks.
Reading /var/www/sharelatex/node_modules/grunt-bunyan/package.json...OK
Parsing /var/www/sharelatex/node_modules/grunt-bunyan/package.json...OK
Loading "bunyan.js" tasks...OK
+ bunyan

Registering "grunt-execute" local Npm module tasks.
Reading /var/www/sharelatex/node_modules/grunt-execute/package.json...OK
Parsing /var/www/sharelatex/node_modules/grunt-execute/package.json...OK
Loading "execute.js" tasks...OK
+ execute

Registering "grunt-available-tasks" local Npm module tasks.
Reading /var/www/sharelatex/node_modules/grunt-available-tasks/package.json...OK
Parsing /var/www/sharelatex/node_modules/grunt-available-tasks/package.json...OK
Loading "available_tasks.js" tasks...OK
+ availabletasks

Registering "grunt-concurrent" local Npm module tasks.
Reading /var/www/sharelatex/node_modules/grunt-concurrent/package.json...OK
Parsing /var/www/sharelatex/node_modules/grunt-concurrent/package.json...OK
Loading "concurrent.js" tasks...OK
+ concurrent

Registering "grunt-contrib-coffee" local Npm module tasks.
Reading /var/www/sharelatex/node_modules/grunt-contrib-coffee/package.json...OK
Parsing /var/www/sharelatex/node_modules/grunt-contrib-coffee/package.json...OK
Loading "coffee.js" tasks...OK
+ coffee

Registering "grunt-shell" local Npm module tasks.
Reading /var/www/sharelatex/node_modules/grunt-shell/package.json...OK
Parsing /var/www/sharelatex/node_modules/grunt-shell/package.json...OK
Loading "shell.js" tasks...OK
+ shell
Initializing config...OK
Loading "Gruntfile.coffee" tasks...ERROR
>> Error: ENOENT, no such file or directory 'migrate'
>>   at Object.fs.lstatSync (fs.js:691:18)
>>   at Object.<anonymous> (/var/www/sharelatex/grunt/ProjectSize.coffee:10:15)
>>   at Object.<anonymous> (/var/www/sharelatex/grunt/ProjectSize.coffee:1:1)
>>   at Module._compile (module.js:456:26)
>>   at Object.loadFile (/var/www/sharelatex/node_modules/settings-sharelatex/node_modules/coffee-script/lib/coffee-script/coffee-script.js:24:19)
>>   at Module.load (module.js:356:32)
>>   at Function.Module._load (module.js:312:12)
>>   at Module.require (module.js:364:17)
>>   at require (module.js:380:17)
>>   at module.exports (/var/www/sharelatex/node_modules/load-grunt-config/lib/readfile.js:28:16)
>>   at /var/www/sharelatex/node_modules/load-grunt-config/lib/readconfigdir.js:21:18
>>   at Array.forEach (native)
>>   at module.exports (/var/www/sharelatex/node_modules/load-grunt-config/lib/readconfigdir.js:19:9)
>>   at /var/www/sharelatex/node_modules/load-grunt-config/lib/gruntconfig.js:10:28
>>   at arrayReduce (/var/www/sharelatex/node_modules/lodash/index.js:1450:23)
>>   at Function.<anonymous> (/var/www/sharelatex/node_modules/lodash/index.js:3445:13)
>>   at LodashWrapper.reduce (/var/www/sharelatex/node_modules/lodash/index.js:11369:27)
>>   at module.exports (/var/www/sharelatex/node_modules/load-grunt-config/lib/gruntconfig.js:9:6)
>>   at module.exports (/var/www/sharelatex/node_modules/load-grunt-config/index.js:33:16)
>>   at Object.module.exports (/var/www/sharelatex/Gruntfile.coffee:245:2)
>>   at loadTask (/var/www/sharelatex/node_modules/grunt/lib/grunt/task.js:325:10)
>>   at Task.task.init (/var/www/sharelatex/node_modules/grunt/lib/grunt/task.js:437:5)
>>   at Object.grunt.tasks (/var/www/sharelatex/node_modules/grunt/lib/grunt.js:120:8)
>>   at Object.module.exports [as cli] (/var/www/sharelatex/node_modules/grunt/lib/grunt/cli.js:38:9)
>>   at Object.<anonymous> (/usr/lib/node_modules/grunt-cli/bin/grunt:44:20)
>>   at Module._compile (module.js:456:26)
>>   at Object.Module._extensions..js (module.js:474:10)
>>   at Module.load (module.js:356:32)
>>   at Function.Module._load (module.js:312:12)
>>   at Function.Module.runMain (module.js:497:10)
>>   at startup (node.js:119:16)
>>   at node.js:945:3

Running tasks: migrate

Running "migrate" task

Running "coffee:migrate" (coffee) task
Verifying property coffee.migrate exists in config...OK
Files: migrations/1_move_doc_lines_to_doc_collection.coffee -> migrations/1_move_doc_lines_to_doc_collection.js
Files: migrations/2_doc_lines_delete_from_project.coffee -> migrations/2_doc_lines_delete_from_project.js
Files: migrations/3_pack_docHistory_collection.coffee -> migrations/3_pack_docHistory_collection.js
Options: bare, join=false, sourceMap=false, joinExt=".src.coffee", separator="\n"
Reading migrations/1_move_doc_lines_to_doc_collection.coffee...OK
Writing migrations/1_move_doc_lines_to_doc_collection.js...OK
Reading migrations/2_doc_lines_delete_from_project.coffee...OK
Writing migrations/2_doc_lines_delete_from_project.js...OK
Reading migrations/3_pack_docHistory_collection.coffee...OK
Writing migrations/3_pack_docHistory_collection.js...OK

Running "shell:migrate" (shell) task
Verifying property shell.migrate exists in config...OK
File: [no files]
Options: stdout, stderr, stdin, failOnError, stdinRawMode=false, preferLocal=false, execOptions={"env":null}
Command: ./node_modules/east/bin/east migrate --adapter east-mongo --url mongodb://admin:[PASSWORD]@172.17.0.1/sharelatex
target migrations:
	1_move_doc_lines_to_doc_collection
	2_doc_lines_delete_from_project
	3_pack_docHistory_collection
mongodb://admin:[PASSWORD]@172.17.0.1/sharelatex
migrate `1_move_doc_lines_to_doc_collection`
loading project ids from /tmp/all-projects
loaded 2 project ids from /tmp/all-projects
581f394d48348f6801373c1e already procssed, skipping
581f39e648348f6801373c21 already procssed, skipping
finished
migration done
migrate `2_doc_lines_delete_from_project`
loading project ids from /tmp/all-projects-2
loaded 2 project ids from /tmp/all-projects-2
581f394d48348f6801373c1e already procssed, skipping
581f39e648348f6801373c21 already procssed, skipping
finished
migration done
migrate `3_pack_docHistory_collection`
loading doc ids from /tmp/all-docs-3
loaded 1 doc ids from /tmp/all-docs-3
finished at Sun Nov 06 2016 14:26:22 GMT+0000 (UTC)
migration done

Done, without errors.
All migrations finished
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 79
Nov  6 14:26:23 6a00f75612cf syslog-ng[98]: syslog-ng starting up; version='3.5.3'

```

**Comment by hrjakobsen** [comment]
Hi! The recommended way to run Overleaf Community Edition is now with Docker, using the [Overleaf Toolkit](https://github.com/overleaf/toolkit). I'll close this issue, as it is based on old build instructions, but please open a new issue if you face problems using Overleaf Toolkit.
