### ISSUE TITLE
Failed to run docker container

### ISSUE THREAD

**Issue by achirkin** [overleaf/overleaf#527]
I cannot run sharelatex in a docker container as shown in quickstart.
```
$ docker --version
Docker version 17.03.1-ce, build c6d412e
```
Here is the full output:
```
/opt/sharelatex$ sudo docker run -d \
>   -v ~/sharelatex_data:/opt/sharelatex/data \
>   -p 80:80 \
>   --name=sharelatex \
>   sharelatex/sharelatex
Unable to find image 'sharelatex/sharelatex:latest' locally
latest: Pulling from sharelatex/sharelatex
a3ed95caeb02: Pull complete 
4445cf40c95c: Pull complete 
8106c180c70a: Pull complete 
f8a90451772f: Pull complete 
ebeba59ebda5: Pull complete 
3fd5211a25c2: Pull complete 
2bb9cb23643e: Pull complete 
71a6b94dbdd4: Pull complete 
755dc3794411: Extracting [==================================================>] 290.2 MB/290.2 MB
7c01413c4ec2: Download complete 
959d73ac1439: Download complete 
e2a9d6de5c5a: Download complete 
cfc50207e286: Download complete 
a47cc1e02955: Download complete 
4c1b1cbedfa3: Download complete 
d6a921346013: Download complete 
4c6d097fa447: Download complete 
6b0f22fc36a4: Download complete 
f12d4f913b8a: Download complete 
74219f763668: Download complete 
40646dc3ab83: Download complete 
064d5d270cae: Download complete 
6a2ddd8d5c01: Download complete 
8753e2bb0f55: Download complete 
cc933b6b8ad8: Download complete 
058ab0cace92: Download complete 
55a925bd154e: Download complete 
9ae778a8da09: Download complete 
46191f50e578: Download complete 
405bc8bfc382: Download complete 
012137c88798: Download complete 
e0254c38a3f2: Download complete 
a8f58a7b5b57: Download complete 
af9ede8b4be7: Download complete 
docker: failed to register layer: Error processing tar file(exit status 1): symlink spanish.alias /usr/lib/aspell/espa�ol.alias: invalid or incomplete multibyte or wide character.
See 'docker run --help'.
```
Host system:
```
Ubuntu 16.04.2 LTS xenial
Linux 4.4.0-75-lowlatency #96-Ubuntu x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by bott0r** [comment]
try `sharelatex/sharelatex:0.6.1`

**Comment by achirkin** [comment]
Nope, the same error occurs. :(

**Comment by bott0r** [comment]
maybe give this a try.

`docker system prune -a`

to remove all dangling images and non used volumes than re-run your docker run

**Comment by achirkin** [comment]
Unfortunately, the same result.

**Comment by bott0r** [comment]
I use exactly the same system, no problem. This is indeed weird

**Comment by achirkin** [comment]
I believe something is wrong in locale within docker image, because if I run the same thing using docker-compose, I get following:
```
...
a8f58a7b5b57: Download complete
af9ede8b4be7: Download complete
Traceback (most recent call last):
  File "logging/__init__.py", line 861, in emit
  File "logging/__init__.py", line 734, in format
  File "compose/cli/formatter.py", line 50, in format
  File "logging/__init__.py", line 469, in format
UnicodeEncodeError: 'ascii' codec can't encode character u'\ufffd' in position 110: ordinal not in range(128)
Logged from file main.py, line 79
```
How can I tweak it to have utf-8 inside the image?

**Comment by djwf** [comment]
I just ran into this problem on a 16.04 system and tried to upgrade to 16.10 (just to see if that would make a difference).  I receive the same errors on both 16.04 and 16.10.  However, those were both inside a virtual machine.  When I tried on 16.04 on bare metal, the download and extraction worked when downloading sharelatex/sharelatex (the latest, 0.6.2).  That might give a clue as to what is going on: are there any troubleshooting steps I can try?

**Comment by Siedlerchr** [comment]
When I used docker-composer in an Ubuntu VM  (16.04 I think) I did not have any problems

**Comment by djwf** [comment]
FYI: I just got this error message on a bare metal Debian 9 installation on ZFS, without formd normalization (no enforcement of UTF-8 filenames).  Any suggestions from the devs?  I'll help out if I can, but I'm not sure what to try.
```
$ docker pull sharelatex/sharelatex:v1.0.0
v1.0.0: Pulling from sharelatex/sharelatex
a3ed95caeb02: Pull complete 
4445cf40c95c: Pull complete 
8106c180c70a: Pull complete 
f8a90451772f: Pull complete 
ebeba59ebda5: Pull complete 
3fd5211a25c2: Pull complete 
205589d79f18: Pull complete 
2fa30b2d2fc1: Pull complete 
757481b2138d: Extracting [==================================================>]  297.1MB/297.1MB
977bc48c1ccf: Download complete 
7ed65c327392: Download complete 
faecc315c1b5: Download complete 
d04513b1c881: Download complete 
af9124267095: Download complete 
128b46c3137e: Download complete 
f852051df9e9: Download complete 
e09d0d996cd0: Download complete 
9f232e2d2ee1: Download complete 
ab7a645358f1: Download complete 
4423bd419880: Download complete 
e8dcd6e10f2d: Download complete 
248fbcefe596: Download complete 
7241dd7603c7: Download complete 
f10caf676380: Download complete 
5867bb624f75: Download complete 
110f9e1f540e: Download complete 
2a8855cf9131: Download complete 
e1c11992f135: Download complete 
b86477603753: Download complete 
273f39258759: Download complete 
746b4c97844f: Download complete 
ec2f6df933be: Download complete 
527c517458df: Download complete 
312a100fb8a4: Download complete 
failed to register layer: ApplyLayer exit status 1 stdout:  stderr: symlink spanish.alias /usr/lib/aspell/espa�ol.alias: invalid or incomplete multibyte or wide character
```

**Comment by flixman** [comment]
Hi, I have the same error here on a "brand new" Debian stable. Did somebody find a solution?

Thank you!

**Comment by Braintelligence** [comment]
![grafik](https://user-images.githubusercontent.com/6761196/46482514-0dab1c00-c7f6-11e8-8afa-04bb3b88a47d.png)

Running docker-compose.yml on a rancher cattle host. Any ideas?

**Comment by Braintelligence** [comment]
Solved my problem by removing special character from ENV variables.
