### ISSUE TITLE
Open source release

### ISSUE THREAD

**Issue by schrodincat** [overleaf/overleaf#613]
It would be really nice to have a new open source release, the last one is [a year old by this point](https://hub.docker.com/r/sharelatex/sharelatex). Do you have plans/timeframe for that?

**Comment by jdleesmiller** [comment]
Yes, we do plan another docker image release soon, but I don't have a definite time for you yet, sorry. We still have some work to do in wrapping up the Overleaf-ShareLaTeX integration, but a new release is next on the list after that.

**Comment by wixaw** [comment]
The opensource version is not dead \o/ 
Hoping that pdflatex process issues are resolved :laughing: 
Thanks

**Comment by prohde** [comment]
@jdleesmiller Will you keep us up-to-date or is there some kind of channel where we can follow the timeplan for the next release?

**Comment by wixaw** [comment]
Hello @jdleesmiller 
I see that changes :+1: 
Maybe we could test a beta soon?

**Comment by prohde** [comment]
@jdleesmiller any news on the open source release?

**Comment by gnanakeethan** [comment]
Is there any update on this?

**Comment by mserranom** [comment]
We’re very happy to announce that you can now try out the new **Overleaf Community Edition 2.0-beta-1**.

Just head over to [Docker Hub](https://hub.docker.com/layers/sharelatex/sharelatex/2.0-beta-1) to give it a go. Check the latest version of [`docker-compose.yml`](https://github.com/overleaf/overleaf/blob/master/docker-compose.yml) since there are breaking environmental changes.

Please note this is the first beta version, don't forget to backup your system before updating.  We're looking forward to your feedback.

**Comment by wixaw** [comment]
Yeeeaaahhh !!! 
I test this monday and I send you a feedback !
Thanks

**Comment by Grumium** [comment]
First, many thanks for providing a new community edition!
I just ran it on a test system. "Upgrading" from the previous version worked flawlessly and without breaking the data base. This is great news.
- However, I would be interested in a dedicated Changelog. (Maybe I overlooked it.) Besides the rather cosmetic improvements in the GUI's visual appearance I did not notice any new features so far, which leads me to my next point: 
- Unfortunately, the track change & commenting feature is still not implemented yet. Even your Server Pro customers (paying customers!) still do NOT have access to this feature. In times of Open Access and Open Science, I consider it a really bad idea.
- Besides that, I noticed an error when I try to open a project. It occurs sporadically depending on what the server currently does. 
Server log:
<---- Opening a project works, UNTIL:
```
 2019-09-16T09:22:39.554+0000 I NETWORK  [conn99] end connection 127.0.0.1:38282 (18 connections now open)
mongo         | 2019-09-16T09:22:41.155+0000 I NETWORK  [conn96] end connection 172.21.0.4:56462 (15 connections now open)
mongo         | 2019-09-16T09:22:41.155+0000 I NETWORK  [conn97] end connection 172.21.0.4:56464 (17 connections now open)
mongo         | 2019-09-16T09:22:41.155+0000 I NETWORK  [conn98] end connection 172.21.0.4:56466 (16 connections now open)
mongo         | 2019-09-16T09:22:41.155+0000 I NETWORK  [conn91] end connection 172.21.0.4:56450 (14 connections now open)
mongo         | 2019-09-16T09:22:41.155+0000 I NETWORK  [conn90] end connection 172.21.0.4:56442 (13 connections now open)
mongo         | 2019-09-16T09:22:41.156+0000 I NETWORK  [conn89] end connection 172.21.0.4:56432 (12 connections now open)
mongo         | 2019-09-16T09:22:41.156+0000 I NETWORK  [conn88] end connection 172.21.0.4:56430 (11 connections now open)
mongo         | 2019-09-16T09:22:41.156+0000 I NETWORK  [conn87] end connection 172.21.0.4:56426 (10 connections now open)
mongo         | 2019-09-16T09:22:41.156+0000 I NETWORK  [conn85] end connection 172.21.0.4:56422 (9 connections now open)
mongo         | 2019-09-16T09:22:41.156+0000 I NETWORK  [conn86] end connection 172.21.0.4:56424 (8 connections now open)
mongo         | 2019-09-16T09:22:41.156+0000 I NETWORK  [conn83] end connection 172.21.0.4:56416 (6 connections now open)
mongo         | 2019-09-16T09:22:41.156+0000 I NETWORK  [conn81] end connection 172.21.0.4:56412 (7 connections now open)
mongo         | 2019-09-16T09:22:41.156+0000 I NETWORK  [conn82] end connection 172.21.0.4:56414 (5 connections now open)
mongo         | 2019-09-16T09:22:41.157+0000 I NETWORK  [conn84] end connection 172.21.0.4:56420 (4 connections now open)
mongo         | 2019-09-16T09:22:44.040+0000 I NETWORK  [listener] connection accepted from 172.21.0.4:56550 #100 (5 connections now open)
mongo         | 2019-09-16T09:22:44.040+0000 I NETWORK  [listener] connection accepted from 172.21.0.4:56552 #101 (6 connections now open)
mongo         | 2019-09-16T09:22:44.040+0000 I NETWORK  [listener] connection accepted from 172.21.0.4:56554 #102 (7 connections now open)
mongo         | 2019-09-16T09:22:44.040+0000 I NETWORK  [listener] connection accepted from 172.21.0.4:56558 #103 (8 connections now open)
mongo         | 2019-09-16T09:22:44.041+0000 I NETWORK  [listener] connection accepted from 172.21.0.4:56560 #104 (9 connections now open)
mongo         | 2019-09-16T09:22:44.041+0000 I NETWORK  [listener] connection accepted from 172.21.0.4:56562 #105 (10 connections now open)
mongo         | 2019-09-16T09:22:44.041+0000 I NETWORK  [listener] connection accepted from 172.21.0.4:56564 #106 (11 connections now open)
mongo         | 2019-09-16T09:22:44.041+0000 I NETWORK  [listener] connection accepted from 172.21.0.4:56568 #107 (12 connections now open)
mongo         | 2019-09-16T09:22:44.041+0000 I NETWORK  [listener] connection accepted from 172.21.0.4:56570 #108 (13 connections now open)
mongo         | 2019-09-16T09:22:44.042+0000 I NETWORK  [listener] connection accepted from 172.21.0.4:56580 #109 (14 connections now open)
mongo         | 2019-09-16T09:22:44.042+0000 I NETWORK  [listener] connection accepted from 172.21.0.4:56588 #110 (15 connections now open)
```
<---- Let's say I try to open a project just now. This results in a "502 Bad Gateway" error.
```
mongo         | 2019-09-16T09:22:44.051+0000 I NETWORK  [conn100] received client metadata from 172.21.0.4:56550 conn100: { driver: { name: "nodejs", version: "2.2.27" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.9.0-9-amd64" }, platform: "Node.js v10.16.3, LE, mongodb-core: 2.1.11" }
mongo         | 2019-09-16T09:22:44.051+0000 I NETWORK  [conn101] received client metadata from 172.21.0.4:56552 conn101: { driver: { name: "nodejs", version: "2.2.27" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.9.0-9-amd64" }, platform: "Node.js v10.16.3, LE, mongodb-core: 2.1.11" }
mongo         | 2019-09-16T09:22:44.052+0000 I NETWORK  [conn102] received client metadata from 172.21.0.4:56554 conn102: { driver: { name: "nodejs", version: "2.2.27" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.9.0-9-amd64" }, platform: "Node.js v10.16.3, LE, mongodb-core: 2.1.11" }
mongo         | 2019-09-16T09:22:44.054+0000 I NETWORK  [conn103] received client metadata from 172.21.0.4:56558 conn103: { driver: { name: "nodejs", version: "2.2.27" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.9.0-9-amd64" }, platform: "Node.js v10.16.3, LE, mongodb-core: 2.1.11" }
mongo         | 2019-09-16T09:22:44.054+0000 I NETWORK  [conn104] received client metadata from 172.21.0.4:56560 conn104: { driver: { name: "nodejs", version: "2.2.27" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.9.0-9-amd64" }, platform: "Node.js v10.16.3, LE, mongodb-core: 2.1.11" }
mongo         | 2019-09-16T09:22:44.055+0000 I NETWORK  [conn105] received client metadata from 172.21.0.4:56562 conn105: { driver: { name: "nodejs", version: "2.2.27" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.9.0-9-amd64" }, platform: "Node.js v10.16.3, LE, mongodb-core: 2.1.11" }
mongo         | 2019-09-16T09:22:44.055+0000 I NETWORK  [conn106] received client metadata from 172.21.0.4:56564 conn106: { driver: { name: "nodejs", version: "2.2.27" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.9.0-9-amd64" }, platform: "Node.js v10.16.3, LE, mongodb-core: 2.1.11" }
mongo         | 2019-09-16T09:22:44.056+0000 I NETWORK  [conn107] received client metadata from 172.21.0.4:56568 conn107: { driver: { name: "nodejs", version: "2.2.27" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.9.0-9-amd64" }, platform: "Node.js v10.16.3, LE, mongodb-core: 2.1.11" }
mongo         | 2019-09-16T09:22:44.057+0000 I NETWORK  [conn108] received client metadata from 172.21.0.4:56570 conn108: { driver: { name: "nodejs", version: "2.2.27" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.9.0-9-amd64" }, platform: "Node.js v10.16.3, LE, mongodb-core: 2.1.11" }
mongo         | 2019-09-16T09:22:44.058+0000 I NETWORK  [conn109] received client metadata from 172.21.0.4:56580 conn109: { driver: { name: "nodejs", version: "2.2.27" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.9.0-9-amd64" }, platform: "Node.js v10.16.3, LE, mongodb-core: 2.1.11" }
mongo         | 2019-09-16T09:22:44.059+0000 I NETWORK  [conn110] received client metadata from 172.21.0.4:56588 conn110: { driver: { name: "nodejs", version: "2.2.27" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.9.0-9-amd64" }, platform: "Node.js v10.16.3, LE, mongodb-core: 2.1.11" }

```
<---- Opening a project is working again!

**Comment by wixaw** [comment]
Hello, 
I have external mongo db, 
I config this in docker-compose : 

> SHARELATEX_MONGO_URL: mongodb://sharelatextest.domain.fr/sharelatex

This is error  when start 'docker-compose up' 

```
sharelatex    | Command: ./node_modules/east/bin/east migrate --adapter east-mongo --url mongodb://sharelatextest.domain.fr/sharelatex
sharelatex    | /var/www/sharelatex/node_modules/east-mongo/lib/adapter.js:26
sharelatex    | 	this.db.close(callback);
sharelatex    | 	       ^
sharelatex    | 
sharelatex    | TypeError: Cannot read property 'close' of undefined
sharelatex    |     at Adapter.disconnect (/var/www/sharelatex/node_modules/east-mongo/lib/adapter.js:26:9)
sharelatex    |     at Migrator.disconnect (/var/www/sharelatex/node_modules/east/lib/migrator.js:331:15)
sharelatex    |     at /var/www/sharelatex/node_modules/east/bin/commands/base.js:122:18
sharelatex    |     at next (/var/www/sharelatex/node_modules/twostep/lib/twoStep.js:148:20)
sharelatex    |     at Group.done (/var/www/sharelatex/node_modules/twostep/lib/twoStep.js:30:16)
sharelatex    |     at Group.error (/var/www/sharelatex/node_modules/twostep/lib/twoStep.js:34:7)
sharelatex    |     at next (/var/www/sharelatex/node_modules/twostep/lib/twoStep.js:155:17)
sharelatex    |     at Group.done (/var/www/sharelatex/node_modules/twostep/lib/twoStep.js:30:16)
sharelatex    |     at Group.error (/var/www/sharelatex/node_modules/twostep/lib/twoStep.js:34:7)
sharelatex    |     at /var/www/sharelatex/node_modules/twostep/lib/twoStep.js:69:17
sharelatex    | Warning: Command failed: ./node_modules/east/bin/east migrate --adapter east-mongo --url mongodb://sharelatextest.domain.fr/sharelatex
sharelatex    | /var/www/sharelatex/node_modules/east-mongo/lib/adapter.js:26
sharelatex    | 	this.db.close(callback);
sharelatex    | 	       ^
sharelatex    | 
sharelatex    | TypeError: Cannot read property 'close' of undefined
sharelatex    |     at Adapter.disconnect (/var/www/sharelatex/node_modules/east-mongo/lib/adapter.js:26:9)
sharelatex    |     at Migrator.disconnect (/var/www/sharelatex/node_modules/east/lib/migrator.js:331:15)
sharelatex    |     at /var/www/sharelatex/node_modules/east/bin/commands/base.js:122:18
sharelatex    |     at next (/var/www/sharelatex/node_modules/twostep/lib/twoStep.js:148:20)
sharelatex    |     at Group.done (/var/www/sharelatex/node_modules/twostep/lib/twoStep.js:30:16)
sharelatex    |     at Group.error (/var/www/sharelatex/node_modules/twostep/lib/twoStep.js:34:7)
sharelatex    |     at next (/var/www/sharelatex/node_modules/twostep/lib/twoStep.js:155:17)
sharelatex    |     at Group.done (/var/www/sharelatex/node_modules/twostep/lib/twoStep.js:30:16)
sharelatex    |     at Group.error (/var/www/sharelatex/node_modules/twostep/lib/twoStep.js:34:7)
sharelatex    |     at /var/www/sharelatex/node_modules/twostep/lib/twoStep.js:69:17
sharelatex    |  Use --force to continue.
sharelatex    | 
sharelatex    | Aborted due to warnings.
```

We did not have a docker-compose before.

Thanks you in advance
William

**Comment by blubbsy** [comment]
> We’re very happy to announce that you can now try out the new **Overleaf Community Edition 2.0-beta-1**.
> 
> Just head over to [Docker Hub](https://hub.docker.com/layers/sharelatex/sharelatex/2.0-beta-1) to give it a go. Check the latest version of [`docker-compose.yml`](https://github.com/overleaf/overleaf/blob/master/docker-compose.yml) since there are breaking environmental changes.
> 
> Please note this is the first beta version, don't forget to backup your system before updating. We're looking forward to your feedback.

thanks! but dont forget to update the installation guide as it is still refering to sharelatex. :)

**Comment by JehandadKhan** [comment]
It would be nice to have the commenting feature available in the public version.

**Comment by Whinegum** [comment]
@mserranom 

I just tried to download the new overleaf 2.0 beta by using the folowing link:
https://hub.docker.com/layers/sharelatex/sharelatex/2.0-beta-1

It seems like the link is not valid anymore. Is it still possible to try out the new beta?

**Comment by jdleesmiller** [comment]
@Whinegum I think that link isn't right, sorry. You should still be able to see it on the main tags page: https://hub.docker.com/r/sharelatex/sharelatex/tags

**Comment by wixaw** [comment]
Hello
Add this in your docker-compose 
```
version: '2.2'
services:
    sharelatex:
        restart: always
        image: sharelatex/sharelatex:2.0-beta-1
```

**Comment by wixaw** [comment]
Hello 
Is it released ? https://hub.docker.com/r/sharelatex/sharelatex/tags 
I see 2.0.0

**Comment by wixaw** [comment]
I have a new issue.
Unable to add a new administrator 
```
docker-compose exec sharelatex /bin/bash -c "cd /var/www/sharelatex; grunt user:create-admin --email user@xxx.fr"
Warning: Task "user@xxx.fr" not found. Use --force to continue.
```

Thanks
Will

**Comment by mserranom** [comment]
Thanks @wixaw, is this an error using `2.0.0` version? should've been fixed in https://github.com/overleaf/overleaf/pull/643.

**Comment by mserranom** [comment]
Thanks for your feedback. I'm closing this ticket, Overleaf Community Edition 2.0.0 has been released in [Docker Hub](https://hub.docker.com/r/sharelatex/sharelatex/tags), please raise separate issues in case you experience any problem.
