### ISSUE TITLE
docker-compose broken

### ISSUE THREAD

**Issue by agowa338** [overleaf/overleaf#625]
## Problem

The provided docker-compose does not work.

## Install type

`git clone git@github.com:overleaf/overleaf.git && cd overleaf && docker-compose up` 

## Version

image: sharelatex/sharelatex

## Logs and errors

<details>
  <summary>docker-compose log</summary>

```
Creating network "overleaf_default" with the default driver
Creating redis ... 
Creating mongo ... 
[2A[2K
Creating redis ... [32mdone[0m
[2B[1A[2K
Creating mongo ... [32mdone[0m
[1BCreating sharelatex ... 
[1A[2K
Creating sharelatex ... [32mdone[0m
[1BAttaching to redis, mongo, sharelatex
[36mredis         |[0m 1:C 24 Jul 2019 11:35:08.815 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
[36mredis         |[0m 1:C 24 Jul 2019 11:35:08.815 # Redis version=5.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
[36mredis         |[0m 1:C 24 Jul 2019 11:35:08.815 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
[36mredis         |[0m 1:M 24 Jul 2019 11:35:08.817 * Running mode=standalone, port=6379.
[36mredis         |[0m 1:M 24 Jul 2019 11:35:08.817 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
[36mredis         |[0m 1:M 24 Jul 2019 11:35:08.817 # Server initialized
[36mredis         |[0m 1:M 24 Jul 2019 11:35:08.817 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
[36mredis         |[0m 1:M 24 Jul 2019 11:35:08.817 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
[36mredis         |[0m 1:M 24 Jul 2019 11:35:08.817 * DB loaded from disk: 0.000 seconds
[36mredis         |[0m 1:M 24 Jul 2019 11:35:08.817 * Ready to accept connections
[33mmongo         |[0m 2019-07-24T11:35:08.898+0000 I CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
[33mmongo         |[0m 2019-07-24T11:35:08.901+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=f462e3373645
[33mmongo         |[0m 2019-07-24T11:35:08.901+0000 I CONTROL  [initandlisten] db version v4.0.10
[33mmongo         |[0m 2019-07-24T11:35:08.901+0000 I CONTROL  [initandlisten] git version: c389e7f69f637f7a1ac3cc9fae843b635f20b766
[33mmongo         |[0m 2019-07-24T11:35:08.901+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
[33mmongo         |[0m 2019-07-24T11:35:08.901+0000 I CONTROL  [initandlisten] allocator: tcmalloc
[33mmongo         |[0m 2019-07-24T11:35:08.901+0000 I CONTROL  [initandlisten] modules: none
[33mmongo         |[0m 2019-07-24T11:35:08.901+0000 I CONTROL  [initandlisten] build environment:
[33mmongo         |[0m 2019-07-24T11:35:08.901+0000 I CONTROL  [initandlisten]     distmod: ubuntu1604
[33mmongo         |[0m 2019-07-24T11:35:08.901+0000 I CONTROL  [initandlisten]     distarch: x86_64
[33mmongo         |[0m 2019-07-24T11:35:08.901+0000 I CONTROL  [initandlisten]     target_arch: x86_64
[33mmongo         |[0m 2019-07-24T11:35:08.901+0000 I CONTROL  [initandlisten] options: { net: { bindIpAll: true } }
[33mmongo         |[0m 2019-07-24T11:35:08.902+0000 I STORAGE  [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
[33mmongo         |[0m 2019-07-24T11:35:08.902+0000 I STORAGE  [initandlisten] 
[33mmongo         |[0m 2019-07-24T11:35:08.902+0000 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
[33mmongo         |[0m 2019-07-24T11:35:08.902+0000 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
[33mmongo         |[0m 2019-07-24T11:35:08.902+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=7465M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
[32msharelatex    |[0m *** Running /etc/my_init.d/00_make_sharelatex_data_dirs.sh...
[32msharelatex    |[0m *** Running /etc/my_init.d/00_regen_sharelatex_secrets.sh...
[32msharelatex    |[0m *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
[32msharelatex    |[0m *** Running /etc/my_init.d/00_set_docker_host_ipaddress.sh...
[32msharelatex    |[0m *** Running /etc/my_init.d/98_check_db_access.sh...
[32msharelatex    |[0m Checking can connect to mongo and redis
[33mmongo         |[0m 2019-07-24T11:35:09.745+0000 I STORAGE  [initandlisten] WiredTiger message [1563968109:745509][1:0x7fe9dbfd1a80], txn-recover: Main recovery loop: starting at 1/22272 to 2/256
[33mmongo         |[0m 2019-07-24T11:35:09.882+0000 I STORAGE  [initandlisten] WiredTiger message [1563968109:882424][1:0x7fe9dbfd1a80], txn-recover: Recovering log 1 through 2
[33mmongo         |[0m 2019-07-24T11:35:09.976+0000 I STORAGE  [initandlisten] WiredTiger message [1563968109:976067][1:0x7fe9dbfd1a80], txn-recover: Recovering log 2 through 2
[33mmongo         |[0m 2019-07-24T11:35:10.058+0000 I STORAGE  [initandlisten] WiredTiger message [1563968110:58304][1:0x7fe9dbfd1a80], txn-recover: Set global recovery timestamp: 0
[33mmongo         |[0m 2019-07-24T11:35:10.093+0000 I RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
[33mmongo         |[0m 2019-07-24T11:35:10.104+0000 I CONTROL  [initandlisten] 
[33mmongo         |[0m 2019-07-24T11:35:10.104+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
[33mmongo         |[0m 2019-07-24T11:35:10.105+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
[33mmongo         |[0m 2019-07-24T11:35:10.105+0000 I CONTROL  [initandlisten] 
[33mmongo         |[0m 2019-07-24T11:35:10.148+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
[33mmongo         |[0m 2019-07-24T11:35:10.152+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
[32msharelatex    |[0m [4mRunning "check:redis" task[24m
[32msharelatex    |[0m Checking can connect to redis
[32msharelatex    |[0m [31m>> [39mFAIL.
[32msharelatex    |[0m [31m>> [39m!!!!!!!!!!!!!! REDIS ERROR !!!!!!!!!!!!!![31m
[32msharelatex    |[0m >> [39m[31m
[32msharelatex    |[0m >> [39mShareLaTeX can not talk to the redis instance[31m
[32msharelatex    |[0m >> [39m[31m
[32msharelatex    |[0m >> [39mCheck the redis instance is running and accessible on env var[31m
[32msharelatex    |[0m >> [39mSHARELATEX_REDIS_HOST[31m
[32msharelatex    |[0m >> [39m[31m
[32msharelatex    |[0m >> [39m!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[32msharelatex    |[0m [31mFatal error: Can not connect to redis[39m
[32msharelatex    |[0m [4mRunning "check:mongo" task[24m
[32msharelatex    |[0m Checking can connect to mongo[31m>> [39mFAIL.
[32msharelatex    |[0m [31m>> [39m!!!!!!!!!!!!!! MONGO ERROR !!!!!!!!!!!!!![31m
[32msharelatex    |[0m >> [39m[31m
[32msharelatex    |[0m >> [39mShareLaTeX can not talk to the mongdb instance[31m
[32msharelatex    |[0m >> [39m[31m
[32msharelatex    |[0m >> [39mCheck the mongodb instance is running and accessible on env var[31m
[32msharelatex    |[0m >> [39mSHARELATEX_MONGO_URL[31m
[32msharelatex    |[0m >> [39m[31m
[32msharelatex    |[0m >> [39m!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[32msharelatex    |[0m [31mFatal error: Can not connect to Mongodb[39m
[32msharelatex    |[0m All checks passed
[32msharelatex    |[0m *** Running /etc/my_init.d/99_migrate.sh...
[32msharelatex    |[0m /usr/bin/node
[32msharelatex    |[0m /usr/bin/grunt
[32msharelatex    |[0m total 56
[32msharelatex    |[0m drwxr-xr-x 1 www-data www-data  4096 Mar  8  2018 .
[32msharelatex    |[0m drwxr-xr-x 1 www-data www-data  4096 Mar  8  2018 ..
[32msharelatex    |[0m -rw-r--r-- 1 www-data www-data  5031 Mar  8  2018 1_move_doc_lines_to_doc_collection.coffee
[32msharelatex    |[0m -rw-r--r-- 1 www-data www-data  5936 Mar  8  2018 2_doc_lines_delete_from_project.coffee
[32msharelatex    |[0m -rw-r--r-- 1 www-data www-data 10627 Mar  8  2018 3_pack_docHistory_collection.coffee
[32msharelatex    |[0m -rw-r--r-- 1 www-data www-data   788 Mar  8  2018 4_update_user_features.coffee
[32msharelatex    |[0m -rw-r--r-- 1 www-data www-data  3526 Mar  8  2018 5_remove_holding_accounts.coffee
[32msharelatex    |[0m -rw-r--r-- 1 www-data www-data   652 Mar  8  2018 6_add_track_changes_feature.coffee
[32msharelatex    |[0m -rw-r--r-- 1 www-data www-data   733 Mar  8  2018 7_add_track_changes_feature_again.coffee
[32msharelatex    |[0m -rw-r--r-- 1 www-data www-data   335 Mar  8  2018 about_migrations.md
[32msharelatex    |[0m [4mInitializing[24m
[32msharelatex    |[0m Command-line options: [36m--verbose[39m
[32msharelatex    |[0m 
[32msharelatex    |[0m Reading "Gruntfile.coffee" Gruntfile...[32mOK[39m
[32msharelatex    |[0m 
[32msharelatex    |[0m [1mRegistering Gruntfile tasks.[22m
[32msharelatex    |[0m 
[32msharelatex    |[0m [1mRegistering "grunt-bunyan" local Npm module tasks.[22m
[32msharelatex    |[0m Reading /var/www/sharelatex/node_modules/grunt-bunyan/package.json...[32mOK[39m
[32msharelatex    |[0m Parsing /var/www/sharelatex/node_modules/grunt-bunyan/package.json...[32mOK[39m
[32msharelatex    |[0m Loading "bunyan.js" tasks...[32mOK[39m
[32msharelatex    |[0m + [36mbunyan[39m
[32msharelatex    |[0m 
[32msharelatex    |[0m [1mRegistering "grunt-execute" local Npm module tasks.[22m
[32msharelatex    |[0m Reading /var/www/sharelatex/node_modules/grunt-execute/package.json...[32mOK[39m
[32msharelatex    |[0m Parsing /var/www/sharelatex/node_modules/grunt-execute/package.json...[32mOK[39m
[32msharelatex    |[0m Loading "execute.js" tasks...[32mOK[39m
[32msharelatex    |[0m + [36mexecute[39m
[32msharelatex    |[0m 
[32msharelatex    |[0m [1mRegistering "grunt-available-tasks" local Npm module tasks.[22m
[32msharelatex    |[0m Reading /var/www/sharelatex/node_modules/grunt-available-tasks/package.json...[32mOK[39m
[32msharelatex    |[0m Parsing /var/www/sharelatex/node_modules/grunt-available-tasks/package.json...[32mOK[39m
[32msharelatex    |[0m Loading "available_tasks.js" tasks...[32mOK[39m
[32msharelatex    |[0m + [36mavailabletasks[39m
[32msharelatex    |[0m 
[32msharelatex    |[0m [1mRegistering "grunt-concurrent" local Npm module tasks.[22m
[32msharelatex    |[0m Reading /var/www/sharelatex/node_modules/grunt-concurrent/package.json...[32mOK[39m
[32msharelatex    |[0m Parsing /var/www/sharelatex/node_modules/grunt-concurrent/package.json...[32mOK[39m
[32msharelatex    |[0m Loading "concurrent.js" tasks...[32mOK[39m
[32msharelatex    |[0m + [36mconcurrent[39m
[32msharelatex    |[0m 
[32msharelatex    |[0m [1mRegistering "grunt-contrib-coffee" local Npm module tasks.[22m
[32msharelatex    |[0m Reading /var/www/sharelatex/node_modules/grunt-contrib-coffee/package.json...[32mOK[39m
[32msharelatex    |[0m Parsing /var/www/sharelatex/node_modules/grunt-contrib-coffee/package.json...[32mOK[39m
[32msharelatex    |[0m Loading "coffee.js" tasks...[32mOK[39m
[32msharelatex    |[0m + [36mcoffee[39m
[32msharelatex    |[0m 
[32msharelatex    |[0m [1mRegistering "grunt-shell" local Npm module tasks.[22m
[32msharelatex    |[0m Reading /var/www/sharelatex/node_modules/grunt-shell/package.json...[32mOK[39m
[32msharelatex    |[0m Parsing /var/www/sharelatex/node_modules/grunt-shell/package.json...[32mOK[39m
[32msharelatex    |[0m Loading "shell.js" tasks...[32mOK[39m
[32msharelatex    |[0m + [36mshell[39m
[32msharelatex    |[0m 
[32msharelatex    |[0m [1mRegistering "./tasks" tasks.[22m
[32msharelatex    |[0m Loading "CreateAndDestoryUsers.coffee" tasks...[32mOK[39m
[32msharelatex    |[0m + [36muser:create-admin[39m, [36muser:delete[39m
[32msharelatex    |[0m Loading "ProjectSize.coffee" tasks...[32mOK[39m
[32msharelatex    |[0m [31m>> [39mNo tasks were registered or unregistered.
[32msharelatex    |[0m Initializing config...[32mOK[39m
[32msharelatex    |[0m Loading "Gruntfile.coffee" tasks...[32mOK[39m
[32msharelatex    |[0m + [36mcheck[39m, [36mcheck:make[39m, [36mcheck:mongo[39m, [36mcheck:redis[39m, [36mdefault[39m, [36mhelp[39m, [36minstall[39m, [36minstall:all[39m, [36minstall:chat[39m, [36minstall:clsi[39m, [36minstall:contacts[39m, [36minstall:docstore[39m, [36minstall:document-updater[39m, [36minstall:filestore[39m, [36minstall:notifications[39m, [36minstall:real-time[39m, [36minstall:spelling[39m, [36minstall:tags[39m, [36minstall:track-changes[39m, [36minstall:web[39m, [36mmigrate[39m, [36mpostinstall[39m, [36mrun[39m, [36mrun:all[39m, [36mupdate[39m, [36mupdate:all[39m
[32msharelatex    |[0m 
[32msharelatex    |[0m Running tasks: [36mmigrate[39m
[32msharelatex    |[0m 
[32msharelatex    |[0m [4mRunning "migrate" task[24m
[32msharelatex    |[0m 
[32msharelatex    |[0m [4mRunning "coffee:migrate" (coffee) task[24m
[32msharelatex    |[0m Verifying property [36mcoffee.migrate[39m exists in config...[32mOK[39m
[32msharelatex    |[0m Files: [36mmigrations/1_move_doc_lines_to_doc_collection.coffee[39m -> [36mmigrations/1_move_doc_lines_to_doc_collection.js[39m
[32msharelatex    |[0m Files: [36mmigrations/2_doc_lines_delete_from_project.coffee[39m -> [36mmigrations/2_doc_lines_delete_from_project.js[39m
[32msharelatex    |[0m Files: [36mmigrations/3_pack_docHistory_collection.coffee[39m -> [36mmigrations/3_pack_docHistory_collection.js[39m
[32msharelatex    |[0m Files: [36mmigrations/4_update_user_features.coffee[39m -> [36mmigrations/4_update_user_features.js[39m
[32msharelatex    |[0m Files: [36mmigrations/5_remove_holding_accounts.coffee[39m -> [36mmigrations/5_remove_holding_accounts.js[39m
[32msharelatex    |[0m Files: [36mmigrations/6_add_track_changes_feature.coffee[39m -> [36mmigrations/6_add_track_changes_feature.js[39m
[32msharelatex    |[0m Files: [36mmigrations/7_add_track_changes_feature_again.coffee[39m -> [36mmigrations/7_add_track_changes_feature_again.js[39m
[32msharelatex    |[0m Options: [36mbare[39m, [36mjoin=false[39m, [36msourceMap=false[39m, [36mjoinExt=".src.coffee"[39m, [36mseparator="\n"[39m
[32msharelatex    |[0m Reading migrations/1_move_doc_lines_to_doc_collection.coffee...[32mOK[39m
[32msharelatex    |[0m Writing migrations/1_move_doc_lines_to_doc_collection.js...[32mOK[39m
[32msharelatex    |[0m Reading migrations/2_doc_lines_delete_from_project.coffee...[32mOK[39m
[32msharelatex    |[0m Writing migrations/2_doc_lines_delete_from_project.js...[32mOK[39m
[32msharelatex    |[0m Reading migrations/3_pack_docHistory_collection.coffee...[32mOK[39m
[32msharelatex    |[0m Writing migrations/3_pack_docHistory_collection.js...[32mOK[39m
[32msharelatex    |[0m Reading migrations/4_update_user_features.coffee...[32mOK[39m
[32msharelatex    |[0m Writing migrations/4_update_user_features.js...[32mOK[39m
[32msharelatex    |[0m Reading migrations/5_remove_holding_accounts.coffee...[32mOK[39m
[32msharelatex    |[0m Writing migrations/5_remove_holding_accounts.js...[32mOK[39m
[32msharelatex    |[0m Reading migrations/6_add_track_changes_feature.coffee...[32mOK[39m
[32msharelatex    |[0m Writing migrations/6_add_track_changes_feature.js...[32mOK[39m
[32msharelatex    |[0m Reading migrations/7_add_track_changes_feature_again.coffee...[32mOK[39m
[32msharelatex    |[0m Writing migrations/7_add_track_changes_feature_again.js...[32mOK[39m
[32msharelatex    |[0m 
[32msharelatex    |[0m [4mRunning "shell:migrate" (shell) task[24m
[32msharelatex    |[0m Verifying property [36mshell.migrate[39m exists in config...[32mOK[39m
[32msharelatex    |[0m File: [33m[no files][39m
[32msharelatex    |[0m Options: [36mstdout[39m, [36mstderr[39m, [36mstdin[39m, [36mfailOnError[39m, [36mstdinRawMode=false[39m, [36mpreferLocal=false[39m, [36mexecOptions={"env":null}[39m
[32msharelatex    |[0m Command: ./node_modules/east/bin/east migrate --adapter east-mongo --url mongodb://mongo/sharelatex
[32msharelatex    |[0m MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: connect EHOSTUNREACH 172.19.0.3:27017]
[32msharelatex    |[0m     at Pool.<anonymous> (/var/www/sharelatex/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:336:35)
[32msharelatex    |[0m     at emitOne (events.js:96:13)
[32msharelatex    |[0m     at Pool.emit (events.js:188:7)
[32msharelatex    |[0m     at Connection.<anonymous> (/var/www/sharelatex/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:280:12)
[32msharelatex    |[0m     at Connection.g (events.js:292:16)
[32msharelatex    |[0m     at emitTwo (events.js:106:13)
[32msharelatex    |[0m     at Connection.emit (events.js:191:7)
[32msharelatex    |[0m     at Socket.<anonymous> (/var/www/sharelatex/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:189:49)
[32msharelatex    |[0m     at Socket.g (events.js:292:16)
[32msharelatex    |[0m     at emitOne (events.js:96:13)
[32msharelatex    |[0m [33mWarning: Command failed: ./node_modules/east/bin/east migrate --adapter east-mongo --url mongodb://mongo/sharelatex
[32msharelatex    |[0m MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: connect EHOSTUNREACH 172.19.0.3:27017]
[32msharelatex    |[0m     at Pool.<anonymous> (/var/www/sharelatex/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:336:35)
[32msharelatex    |[0m     at emitOne (events.js:96:13)
[32msharelatex    |[0m     at Pool.emit (events.js:188:7)
[32msharelatex    |[0m     at Connection.<anonymous> (/var/www/sharelatex/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:280:12)
[32msharelatex    |[0m     at Connection.g (events.js:292:16)
[32msharelatex    |[0m     at emitTwo (events.js:106:13)
[32msharelatex    |[0m     at Connection.emit (events.js:191:7)
[32msharelatex    |[0m     at Socket.<anonymous> (/var/www/sharelatex/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:189:49)
[32msharelatex    |[0m     at Socket.g (events.js:292:16)
[32msharelatex    |[0m     at emitOne (events.js:96:13)
[32msharelatex    |[0m  Use --force to continue.[39m
[32msharelatex    |[0m 
[32msharelatex    |[0m [31mAborted due to warnings.[39m
[32msharelatex    |[0m All migrations finished
[32msharelatex    |[0m *** Running /etc/rc.local...
[32msharelatex    |[0m *** Booting runit daemon...
[32msharelatex    |[0m *** Runit started as PID 97
[32msharelatex    |[0m tail: unrecognized file system type 0x794c7630 for ‘/var/log/syslog’. please report this to bug-coreutils@gnu.org. reverting to polling
[32msharelatex    |[0m tail: unrecognized file system type 0x794c7630 for ‘/var/log/sharelatex/chat.log’. please report this to bug-coreutils@gnu.org. reverting to polling
[32msharelatex    |[0m tail: unrecognized file system type 0x794c7630 for ‘/var/log/sharelatex/clsi.log’. please report this to bug-coreutils@gnu.org. reverting to polling
[32msharelatex    |[0m tail: unrecognized file system type 0x794c7630 for ‘/var/log/sharelatex/docstore.log’. please report this to bug-coreutils@gnu.org. reverting to polling
[32msharelatex    |[0m tail: unrecognized file system type 0x794c7630 for ‘/var/log/sharelatex/document-updater.log’. please report this to bug-coreutils@gnu.org. reverting to polling
[32msharelatex    |[0m tail: unrecognized file system type 0x794c7630 for ‘/var/log/sharelatex/filestore.log’. please report this to bug-coreutils@gnu.org. reverting to polling
[32msharelatex    |[0m tail: unrecognized file system type 0x794c7630 for ‘/var/log/sharelatex/notifications.log’. please report this to bug-coreutils@gnu.org. reverting to polling
[32msharelatex    |[0m tail: unrecognized file system type 0x794c7630 for ‘/var/log/sharelatex/real-time.log’. please report this to bug-coreutils@gnu.org. reverting to polling
[32msharelatex    |[0m tail: unrecognized file system type 0x794c7630 for ‘/var/log/sharelatex/spelling.log’. please report this to bug-coreutils@gnu.org. reverting to polling
[32msharelatex    |[0m tail: unrecognized file system type 0x794c7630 for ‘/var/log/sharelatex/tags.log’. please report this to bug-coreutils@gnu.org. reverting to polling
[32msharelatex    |[0m tail: unrecognized file system type 0x794c7630 for ‘/var/log/sharelatex/track-changes.log’. please report this to bug-coreutils@gnu.org. reverting to polling
[32msharelatex    |[0m tail: unrecognized file system type 0x794c7630 for ‘/var/log/sharelatex/web.log’. please report this to bug-coreutils@gnu.org. reverting to polling
[32msharelatex    |[0m Jul 24 11:35:17 99f3c19aeda3 syslog-ng[113]: syslog-ng starting up; version='3.5.3'
```

</details>

**Comment by bonanza123** [comment]
I guess this is due to the filesystem being used by docker. Post output of `docker info`

**Comment by agowa338** [comment]
Can no longer reproduce the issue. It works with the latest ubuntu 18.04 instance.
