### ISSUE TITLE
Service /user/emails not available from /project route => 502 Bad Gateway

### ISSUE THREAD

**Issue by mickaelbaron** [overleaf/overleaf#637]
## Problem

Our Sharelatex instance is hosted at this URL https://sharelatex.mycompany.com. When I go to the project page https://sharelatex.mycompany.com/project I have an HTTP error 502 Bad Gateway. 

From the developer tools of Chrome, I identified the problem. Sharelatex tries to connect to this URL https://sharelatex.mycompany.com/user/emails but the user service seems not to exist. 

## Install type

I'm using a Docker image built by myself. 

## Version

Docker image build from the master branch of https://github.com/overleaf/overleaf. Sharelatex community edition.

## Logs and errors

Logs from NGINX included into Sharelatex container

`2019/09/11 15:30:24 [error] 147#147: *238 upstream prematurely closed connection while reading response header from upstream, client: 172.18.0.5, server: _, request: "GET /user/emails HTTP/1.1", upstream: "http://127.0.0.1:3000/user/emails", host: "sharelatex.mycompany.com", referrer: "https://sharelatex.mycompany.com/
project"`

Request header

`GET /user/emails HTTP/1.1
Host: sharelatex.mycompany.com
Connection: keep-alive
Accept: application/json, text/plain, */*
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Referer: https://sharelatex.mycompany.com/project
Accept-Encoding: gzip, deflate, br
Accept-Language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7,la;q=0.6,ca;q=0.5
Cookie: sharelatex.sid=TODO`

Reponse header

`HTTP/1.1 502 Bad Gateway
Server: nginx/1.13.6
Date: Wed, 11 Sep 2019 15:36:03 GMT
Content-Type: text/html
Content-Length: 584
Connection: keep-alive
Strict-Transport-Security: max-age=31536000; includeSubDomains`

**Comment by mserranom** [comment]
Fixed in https://github.com/overleaf/overleaf/commit/2576675662b610275ebe7073d15d44c39e3fc1c9

**Comment by mickaelbaron** [comment]
Hi @mserranom,

I've just build a new version of Sharelatex Docker image. I think there is a regression. 

I've always the same problem and there are some errors into the containers of Sharelatex

`
...
Reading migrations/7_add_token_indexes.coffee...OK
Writing migrations/7_add_token_indexes.js...OK
Reading migrations/7_add_track_changes_feature_again.coffee...OK
Writing migrations/7_add_track_changes_feature_again.js...OK
Running "shell:migrate" (shell) task
Verifying property shell.migrate exists in config...OK
File: [no files]
Options: stdout, stderr, stdin, failOnError, stdinRawMode=false, preferLocal=false, execOptions={"env":null}
Command: ./node_modules/east/bin/east migrate --adapter east-mongo --url mongodb://sharelatex-mongodb/sharelatex
target migrations:
	9_create_user_emails_array
migrate `9_create_user_emails_array`
/var/www/sharelatex/node_modules/mongodb/lib/utils.js:123
    process.nextTick(function() { throw err; });
                                  ^

ReferenceError: user is not defined
    at updateAllUsersEmailsAttribute (/var/www/sharelatex/migrations/9_create_user_emails_array.js:25:27)
    at db.users.find (/var/www/sharelatex/migrations/9_create_user_emails_array.js:37:9)
    at /var/www/sharelatex/node_modules/mongojs/lib/cursor.js:59:24
    at handleCallback (/var/www/sharelatex/node_modules/mongodb/lib/utils.js:120:56)
    at /var/www/sharelatex/node_modules/mongodb/lib/cursor.js:683:5
    at handleCallback (/var/www/sharelatex/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:171:5)
    at setCursorDeadAndNotified (/var/www/sharelatex/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:505:3)
    at nextFunction (/var/www/sharelatex/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:660:7)
    at Cursor.next [as _next] (/var/www/sharelatex/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:701:3)
    at nextObject (/var/www/sharelatex/node_modules/mongodb/lib/cursor.js:680:8)
    at Cursor.next (/var/www/sharelatex/node_modules/mongodb/lib/cursor.js:270:12)
    at /var/www/sharelatex/node_modules/mongojs/lib/cursor.js:36:14
    at apply (/var/www/sharelatex/node_modules/mongojs/node_modules/thunky/index.js:16:28)
    at Cursor._get (/var/www/sharelatex/node_modules/mongojs/node_modules/thunky/index.js:27:3)
    at Cursor.next (/var/www/sharelatex/node_modules/mongojs/lib/cursor.js:30:8)
    at Immediate.loop (/var/www/sharelatex/node_modules/mongojs/lib/cursor.js:57:10)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
Warning: Command failed: ./node_modules/east/bin/east migrate --adapter east-mongo --url mongodb://sharelatex-mongodb/sharelatex
/var/www/sharelatex/node_modules/mongodb/lib/utils.js:123
    process.nextTick(function() { throw err; });
                                  ^

ReferenceError: user is not defined
    at updateAllUsersEmailsAttribute (/var/www/sharelatex/migrations/9_create_user_emails_array.js:25:27)
    at db.users.find (/var/www/sharelatex/migrations/9_create_user_emails_array.js:37:9)
    at /var/www/sharelatex/node_modules/mongojs/lib/cursor.js:59:24
    at handleCallback (/var/www/sharelatex/node_modules/mongodb/lib/utils.js:120:56)
    at /var/www/sharelatex/node_modules/mongodb/lib/cursor.js:683:5
    at handleCallback (/var/www/sharelatex/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:171:5)
    at setCursorDeadAndNotified (/var/www/sharelatex/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:505:3)
    at nextFunction (/var/www/sharelatex/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:660:7)
    at Cursor.next [as _next] (/var/www/sharelatex/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:701:3)
    at nextObject (/var/www/sharelatex/node_modules/mongodb/lib/cursor.js:680:8)
    at Cursor.next (/var/www/sharelatex/node_modules/mongodb/lib/cursor.js:270:12)
    at /var/www/sharelatex/node_modules/mongojs/lib/cursor.js:36:14
    at apply (/var/www/sharelatex/node_modules/mongojs/node_modules/thunky/index.js:16:28)
    at Cursor._get (/var/www/sharelatex/node_modules/mongojs/node_modules/thunky/index.js:27:3)
    at Cursor.next (/var/www/sharelatex/node_modules/mongojs/lib/cursor.js:30:8)
    at Immediate.loop (/var/www/sharelatex/node_modules/mongojs/lib/cursor.js:57:10)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
 Use --force to continue.

Aborted due to warnings.
All migrations finished
*** Booting runit daemon...
*** Runit started as PID 113
Sep 13 19:47:02 e25c6d8107c8 cron[139]: (CRON) INFO (pidfile fd = 3)
Sep 13 19:47:02 e25c6d8107c8 cron[139]: (CRON) INFO (Running @reboot jobs)
`

Mickael
