### ISSUE TITLE
Failing to connect to mongo and redis using provided docker-compose file

### ISSUE THREAD

**Issue by twilsonco** [overleaf/overleaf#673]
## Steps to Reproduce

1. run `docker-compose up` on provided docker-compose.yml file having changed only the data directories for share latex, mongo, and redis, on fresh Lubuntu install with docker setup and running

## Expected Behaviour
Should have sharelatex up and running and accessible at http port 80

## Observed Behaviour
sharelatex reports (in docker-compose output) that it cannot talk to redis or mongo

## Technical Info
Apologies if I'm missing something simple here.
This seems related to #572, but that solution was to specify that the sharelatex container links to the mongo and redis containers, which is already specified in the docker-compose.yml file, so it seems that shouldn't be a problem here.
 
Also tried having set the two env vars below (mentioned in the below log output):

```
environment:
 '0': SHARELATEX_REDIS_HOST=redis
 '1': SHARELATEX_MONGO_URL=mongodb://mongo/sharelatex
```

With or without the env vars defined, the results are the same. This output is on first run of `docker-compose up`, so everything is a fresh install:

```
Creating redis ... 
Creating mongo ... 
Creating redis
Creating mongo ... done
Creating sharelatex ... 
Creating sharelatex ... done
Attaching to redis, mongo, sharelatex
redis         | 1:C 13 Dec 2019 16:32:12.847 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis         | 1:C 13 Dec 2019 16:32:12.847 # Redis version=5.0.7, bits=64, commit=00000000, modified=0, pid=1, just started
redis         | 1:C 13 Dec 2019 16:32:12.847 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
mongo         | 2019-12-13T16:32:13.834+0000 I  CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
redis         | 1:M 13 Dec 2019 16:32:12.847 * Running mode=standalone, port=6379.
redis         | 1:M 13 Dec 2019 16:32:12.847 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
sharelatex    | *** Running /etc/my_init.d/00_make_sharelatex_data_dirs.sh...
redis         | 1:M 13 Dec 2019 16:32:12.847 # Server initialized
mongo         | 2019-12-13T16:32:13.837+0000 I  CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=063958bfa422
mongo         | 2019-12-13T16:32:13.837+0000 I  CONTROL  [initandlisten] db version v4.2.2
mongo         | 2019-12-13T16:32:13.837+0000 I  CONTROL  [initandlisten] git version: a0bbbff6ada159e19298d37946ac8dc4b497eadf
mongo         | 2019-12-13T16:32:13.837+0000 I  CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
redis         | 1:M 13 Dec 2019 16:32:12.847 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
sharelatex    | *** Running /etc/my_init.d/00_regen_sharelatex_secrets.sh...
mongo         | 2019-12-13T16:32:13.837+0000 I  CONTROL  [initandlisten] allocator: tcmalloc
redis         | 1:M 13 Dec 2019 16:32:12.848 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
mongo         | 2019-12-13T16:32:13.837+0000 I  CONTROL  [initandlisten] modules: none
mongo         | 2019-12-13T16:32:13.837+0000 I  CONTROL  [initandlisten] build environment:
redis         | 1:M 13 Dec 2019 16:32:12.848 * DB loaded from disk: 0.000 seconds
sharelatex    | *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
mongo         | 2019-12-13T16:32:13.837+0000 I  CONTROL  [initandlisten]     distmod: ubuntu1804
mongo         | 2019-12-13T16:32:13.837+0000 I  CONTROL  [initandlisten]     distarch: x86_64
redis         | 1:M 13 Dec 2019 16:32:12.848 * Ready to accept connections
mongo         | 2019-12-13T16:32:13.837+0000 I  CONTROL  [initandlisten]     target_arch: x86_64
sharelatex    | *** Running /etc/my_init.d/00_set_docker_host_ipaddress.sh...
mongo         | 2019-12-13T16:32:13.837+0000 I  CONTROL  [initandlisten] options: { net: { bindIp: "*" } }
sharelatex    | *** Running /etc/my_init.d/10_syslog-ng.init...
mongo         | 2019-12-13T16:32:13.838+0000 I  STORAGE  [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
mongo         | 2019-12-13T16:32:13.838+0000 I  STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=1457M,cache_overflow=(file_max=0M),session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000,close_scan_interval=10,close_handle_minimum=250),statistics_log=(wait=0),verbose=[recovery_progress,checkpoint_progress],
sharelatex    | Dec 13 16:32:24 ca0a1e9ad128 syslog-ng[57]: syslog-ng starting up; version='3.13.2'
mongo         | 2019-12-13T16:32:15.272+0000 I  STORAGE  [initandlisten] WiredTiger message [1576254735:272334][1:0x7fa024102b00], txn-recover: Recovering log 4 through 5
mongo         | 2019-12-13T16:32:15.345+0000 I  STORAGE  [initandlisten] WiredTiger message [1576254735:345567][1:0x7fa024102b00], txn-recover: Recovering log 5 through 5
mongo         | 2019-12-13T16:32:15.417+0000 I  STORAGE  [initandlisten] WiredTiger message [1576254735:417314][1:0x7fa024102b00], txn-recover: Main recovery loop: starting at 4/4736 to 5/256
mongo         | 2019-12-13T16:32:15.560+0000 I  STORAGE  [initandlisten] WiredTiger message [1576254735:560673][1:0x7fa024102b00], txn-recover: Recovering log 4 through 5
mongo         | 2019-12-13T16:32:15.637+0000 I  STORAGE  [initandlisten] WiredTiger message [1576254735:637431][1:0x7fa024102b00], txn-recover: Recovering log 5 through 5
mongo         | 2019-12-13T16:32:15.709+0000 I  STORAGE  [initandlisten] WiredTiger message [1576254735:709058][1:0x7fa024102b00], txn-recover: Set global recovery timestamp: (0,0)
mongo         | 2019-12-13T16:32:15.714+0000 I  RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
mongo         | 2019-12-13T16:32:15.717+0000 I  STORAGE  [initandlisten] Timestamp monitor starting
mongo         | 2019-12-13T16:32:15.717+0000 I  CONTROL  [initandlisten] 
mongo         | 2019-12-13T16:32:15.717+0000 I  CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
mongo         | 2019-12-13T16:32:15.717+0000 I  CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
mongo         | 2019-12-13T16:32:15.717+0000 I  CONTROL  [initandlisten] 
mongo         | 2019-12-13T16:32:15.721+0000 I  SHARDING [initandlisten] Marking collection local.system.replset as collection version: <unsharded>
mongo         | 2019-12-13T16:32:15.723+0000 I  STORAGE  [initandlisten] Flow Control is enabled on this deployment.
mongo         | 2019-12-13T16:32:15.724+0000 I  SHARDING [initandlisten] Marking collection admin.system.roles as collection version: <unsharded>
mongo         | 2019-12-13T16:32:15.724+0000 I  SHARDING [initandlisten] Marking collection admin.system.version as collection version: <unsharded>
mongo         | 2019-12-13T16:32:15.726+0000 I  SHARDING [initandlisten] Marking collection local.startup_log as collection version: <unsharded>
mongo         | 2019-12-13T16:32:15.726+0000 I  FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
mongo         | 2019-12-13T16:32:15.727+0000 I  SHARDING [LogicalSessionCacheRefresh] Marking collection config.system.sessions as collection version: <unsharded>
mongo         | 2019-12-13T16:32:15.727+0000 I  NETWORK  [initandlisten] Listening on /tmp/mongodb-27017.sock
mongo         | 2019-12-13T16:32:15.727+0000 I  NETWORK  [initandlisten] Listening on 0.0.0.0
mongo         | 2019-12-13T16:32:15.727+0000 I  SHARDING [LogicalSessionCacheReap] Marking collection config.transactions as collection version: <unsharded>
mongo         | 2019-12-13T16:32:15.727+0000 I  NETWORK  [initandlisten] waiting for connections on port 27017
mongo         | 2019-12-13T16:32:16.001+0000 I  SHARDING [ftdc] Marking collection local.oplog.rs as collection version: <unsharded>
mongo         | 2019-12-13T16:32:23.976+0000 I  NETWORK  [listener] connection accepted from 127.0.0.1:59626 #1 (1 connection now open)
mongo         | 2019-12-13T16:32:23.976+0000 I  NETWORK  [conn1] received client metadata from 127.0.0.1:59626 conn1: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "4.2.2" }, os: { type: "Linux", name: "Ubuntu", architecture: "x86_64", version: "18.04" } }
mongo         | 2019-12-13T16:32:23.983+0000 I  NETWORK  [conn1] end connection 127.0.0.1:59626 (0 connections now open)
sharelatex    | *** Running /etc/my_init.d/98_check_db_access.sh...
sharelatex    | Checking can connect to mongo and redis
sharelatex    | Running "check:redis" task
sharelatex    | Checking can connect to redis
sharelatex    | >> FAIL.
sharelatex    | >> !!!!!!!!!!!!!! REDIS ERROR !!!!!!!!!!!!!!
sharelatex    | >> 
sharelatex    | >> ShareLaTeX can not talk to the redis instance
sharelatex    | >> 
sharelatex    | >> Check the redis instance is running and accessible on env var
sharelatex    | >> SHARELATEX_REDIS_HOST
sharelatex    | >> 
sharelatex    | >> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
sharelatex    | Fatal error: Can not connect to redis
sharelatex    | Running "check:mongo" task
sharelatex    | Checking can connect to mongo>> FAIL.
sharelatex    | >> !!!!!!!!!!!!!! MONGO ERROR !!!!!!!!!!!!!!
sharelatex    | >> 
sharelatex    | >> ShareLaTeX can not talk to the mongdb instance
sharelatex    | >> 
sharelatex    | >> Check the mongodb instance is running and accessible on env var
sharelatex    | >> SHARELATEX_MONGO_URL
sharelatex    | >> 
sharelatex    | >> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
sharelatex    | Fatal error: Can not connect to Mongodb
sharelatex    | All checks passed
sharelatex    | *** Running /etc/my_init.d/99_migrate.sh...
sharelatex    | /usr/bin/node
sharelatex    | /usr/bin/grunt
sharelatex    | total 68
sharelatex    | drwxr-xr-x 1 www-data www-data  4096 Oct  8 13:24 .
sharelatex    | drwxr-xr-x 1 www-data www-data  4096 Oct  8 13:25 ..
sharelatex    | -rw-r--r-- 1 www-data www-data  2911 Oct  8 13:24 10_update_project_tokens.js
sharelatex    | -rw-r--r-- 1 www-data www-data  5031 Oct  8 13:24 1_move_doc_lines_to_doc_collection.coffee
sharelatex    | -rw-r--r-- 1 www-data www-data  5936 Oct  8 13:24 2_doc_lines_delete_from_project.coffee
sharelatex    | -rw-r--r-- 1 www-data www-data 10627 Oct  8 13:24 3_pack_docHistory_collection.coffee
sharelatex    | -rw-r--r-- 1 www-data www-data   788 Oct  8 13:24 4_update_user_features.coffee
sharelatex    | -rw-r--r-- 1 www-data www-data  3526 Oct  8 13:24 5_remove_holding_accounts.coffee
sharelatex    | -rw-r--r-- 1 www-data www-data   652 Oct  8 13:24 6_add_track_changes_feature.coffee
sharelatex    | -rw-r--r-- 1 www-data www-data  1334 Oct  8 13:24 7_add_token_indexes.coffee
sharelatex    | -rw-r--r-- 1 www-data www-data   733 Oct  8 13:24 7_add_track_changes_feature_again.coffee
sharelatex    | -rw-r--r-- 1 www-data www-data  1153 Oct  8 13:24 9_create_user_emails_array.js
sharelatex    | -rw-r--r-- 1 www-data www-data   335 Oct  8 13:24 about_migrations.md
sharelatex    | Initializing
sharelatex    | Command-line options: --verbose, --gruntfile=/var/www/sharelatex/Gruntfile.coffee
sharelatex    | 
sharelatex    | Reading "Gruntfile.coffee" Gruntfile...OK
sharelatex    | 
sharelatex    | Registering Gruntfile tasks.
sharelatex    | 
sharelatex    | Registering "grunt-bunyan" local Npm module tasks.
sharelatex    | Reading /var/www/sharelatex/node_modules/grunt-bunyan/package.json...OK
sharelatex    | Parsing /var/www/sharelatex/node_modules/grunt-bunyan/package.json...OK
sharelatex    | Loading "bunyan.js" tasks...OK
sharelatex    | + bunyan
sharelatex    | 
sharelatex    | Registering "grunt-execute" local Npm module tasks.
sharelatex    | Reading /var/www/sharelatex/node_modules/grunt-execute/package.json...OK
sharelatex    | Parsing /var/www/sharelatex/node_modules/grunt-execute/package.json...OK
sharelatex    | Loading "execute.js" tasks...OK
sharelatex    | + execute
sharelatex    | 
sharelatex    | Registering "grunt-available-tasks" local Npm module tasks.
sharelatex    | Reading /var/www/sharelatex/node_modules/grunt-available-tasks/package.json...OK
sharelatex    | Parsing /var/www/sharelatex/node_modules/grunt-available-tasks/package.json...OK
sharelatex    | Loading "available_tasks.js" tasks...OK
sharelatex    | + availabletasks
sharelatex    | 
sharelatex    | Registering "grunt-concurrent" local Npm module tasks.
sharelatex    | Reading /var/www/sharelatex/node_modules/grunt-concurrent/package.json...OK
sharelatex    | Parsing /var/www/sharelatex/node_modules/grunt-concurrent/package.json...OK
sharelatex    | Loading "concurrent.js" tasks...OK
sharelatex    | + concurrent
sharelatex    | 
sharelatex    | Registering "grunt-contrib-coffee" local Npm module tasks.
sharelatex    | Reading /var/www/sharelatex/node_modules/grunt-contrib-coffee/package.json...OK
sharelatex    | Parsing /var/www/sharelatex/node_modules/grunt-contrib-coffee/package.json...OK
sharelatex    | Loading "coffee.js" tasks...OK
sharelatex    | + coffee
sharelatex    | 
sharelatex    | Registering "grunt-shell" local Npm module tasks.
sharelatex    | Reading /var/www/sharelatex/node_modules/grunt-shell/package.json...OK
sharelatex    | Parsing /var/www/sharelatex/node_modules/grunt-shell/package.json...OK
sharelatex    | Loading "shell.js" tasks...OK
sharelatex    | + shell
sharelatex    | 
sharelatex    | Registering "./tasks" tasks.
sharelatex    | Loading "CreateAndDestoryUsers.coffee" tasks...OK
sharelatex    | + user:create-admin, user:delete
sharelatex    | Loading "ProjectSize.coffee" tasks...OK
sharelatex    | >> No tasks were registered or unregistered.
sharelatex    | Initializing config...OK
sharelatex    | Loading "Gruntfile.coffee" tasks...OK
sharelatex    | + check, check:make, check:mongo, check:redis, default, help, install, install:all, install:chat, install:clsi, install:contacts, install:docstore, install:document-updater, install:filestore, install:notifications, install:real-time, install:spelling, install:tags, install:track-changes, install:web, migrate, postinstall, run, run:all, update, update:all
sharelatex    | 
sharelatex    | Running tasks: migrate
sharelatex    | 
sharelatex    | Running "migrate" task
sharelatex    | 
sharelatex    | Running "coffee:migrate" (coffee) task
sharelatex    | Verifying property coffee.migrate exists in config...OK
sharelatex    | Files: migrations/1_move_doc_lines_to_doc_collection.coffee -> migrations/1_move_doc_lines_to_doc_collection.js
sharelatex    | Files: migrations/2_doc_lines_delete_from_project.coffee -> migrations/2_doc_lines_delete_from_project.js
sharelatex    | Files: migrations/3_pack_docHistory_collection.coffee -> migrations/3_pack_docHistory_collection.js
sharelatex    | Files: migrations/4_update_user_features.coffee -> migrations/4_update_user_features.js
sharelatex    | Files: migrations/5_remove_holding_accounts.coffee -> migrations/5_remove_holding_accounts.js
sharelatex    | Files: migrations/6_add_track_changes_feature.coffee -> migrations/6_add_track_changes_feature.js
sharelatex    | Files: migrations/7_add_token_indexes.coffee -> migrations/7_add_token_indexes.js
sharelatex    | Files: migrations/7_add_track_changes_feature_again.coffee -> migrations/7_add_track_changes_feature_again.js
sharelatex    | Options: bare, join=false, sourceMap=false, joinExt=".src.coffee", separator="\n"
sharelatex    | Reading migrations/1_move_doc_lines_to_doc_collection.coffee...OK
sharelatex    | Writing migrations/1_move_doc_lines_to_doc_collection.js...OK
sharelatex    | Reading migrations/2_doc_lines_delete_from_project.coffee...OK
sharelatex    | Writing migrations/2_doc_lines_delete_from_project.js...OK
sharelatex    | Reading migrations/3_pack_docHistory_collection.coffee...OK
sharelatex    | Writing migrations/3_pack_docHistory_collection.js...OK
sharelatex    | Reading migrations/4_update_user_features.coffee...OK
sharelatex    | Writing migrations/4_update_user_features.js...OK
sharelatex    | Reading migrations/5_remove_holding_accounts.coffee...OK
sharelatex    | Writing migrations/5_remove_holding_accounts.js...OK
sharelatex    | Reading migrations/6_add_track_changes_feature.coffee...OK
sharelatex    | Writing migrations/6_add_track_changes_feature.js...OK
sharelatex    | Reading migrations/7_add_token_indexes.coffee...OK
sharelatex    | Writing migrations/7_add_token_indexes.js...OK
sharelatex    | Reading migrations/7_add_track_changes_feature_again.coffee...OK
sharelatex    | Writing migrations/7_add_track_changes_feature_again.js...OK
sharelatex    | 
sharelatex    | Running "shell:migrate" (shell) task
sharelatex    | Verifying property shell.migrate exists in config...OK
sharelatex    | File: [no files]
sharelatex    | Options: stdout, stderr, stdin, failOnError, stdinRawMode=false, preferLocal=false, execOptions={"env":null}
sharelatex    | Command: ./node_modules/east/bin/east migrate --adapter east-mongo --url mongodb://dockerhost/sharelatex
sharelatex    | MongoError: failed to connect to server [dockerhost:27017] on first connect [MongoError: connect ECONNREFUSED 172.18.0.1:27017]
sharelatex    |     at Pool.<anonymous> (/var/www/sharelatex/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:336:35)
sharelatex    |     at Pool.emit (events.js:198:13)
sharelatex    |     at Connection.<anonymous> (/var/www/sharelatex/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:280:12)
sharelatex    |     at Object.onceWrapper (events.js:286:20)
sharelatex    |     at Connection.emit (events.js:198:13)
sharelatex    |     at Socket.<anonymous> (/var/www/sharelatex/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:189:49)
sharelatex    |     at Object.onceWrapper (events.js:286:20)
sharelatex    |     at Socket.emit (events.js:198:13)
sharelatex    |     at emitErrorNT (internal/streams/destroy.js:91:8)
sharelatex    |     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
sharelatex    | Warning: Command failed: ./node_modules/east/bin/east migrate --adapter east-mongo --url mongodb://dockerhost/sharelatex
sharelatex    | MongoError: failed to connect to server [dockerhost:27017] on first connect [MongoError: connect ECONNREFUSED 172.18.0.1:27017]
sharelatex    |     at Pool.<anonymous> (/var/www/sharelatex/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:336:35)
sharelatex    |     at Pool.emit (events.js:198:13)
sharelatex    |     at Connection.<anonymous> (/var/www/sharelatex/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:280:12)
sharelatex    |     at Object.onceWrapper (events.js:286:20)
sharelatex    |     at Connection.emit (events.js:198:13)
sharelatex    |     at Socket.<anonymous> (/var/www/sharelatex/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:189:49)
sharelatex    |     at Object.onceWrapper (events.js:286:20)
sharelatex    |     at Socket.emit (events.js:198:13)
sharelatex    |     at emitErrorNT (internal/streams/destroy.js:91:8)
sharelatex    |     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
sharelatex    |  Use --force to continue.
sharelatex    | 
sharelatex    | Aborted due to warnings.
sharelatex    | All migrations finished
sharelatex    | *** Booting runit daemon...
sharelatex    | *** Runit started as PID 116
sharelatex    | Dec 13 16:32:27 ca0a1e9ad128 cron[127]: (CRON) INFO (pidfile fd = 3)
sharelatex    | Dec 13 16:32:27 ca0a1e9ad128 cron[127]: (CRON) INFO (Running @reboot jobs)
sharelatex    | >> Setting permissions on docker socket
mongo         | 2019-12-13T16:32:34.306+0000 I  NETWORK  [listener] connection accepted from 127.0.0.1:60380 #2 (1 connection now open)
mongo         | 2019-12-13T16:32:34.306+0000 I  NETWORK  [conn2] received client metadata from 127.0.0.1:60380 conn2: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "4.2.2" }, os: { type: "Linux", name: "Ubuntu", architecture: "x86_64", version: "18.04" } }
mongo         | 2019-12-13T16:32:34.311+0000 I  NETWORK  [conn2] end connection 127.0.0.1:60380 (0 connections now open)
mongo         | 2019-12-13T16:32:44.575+0000 I  NETWORK  [listener] connection accepted from 127.0.0.1:33318 #3 (1 connection now open)
mongo         | 2019-12-13T16:32:44.575+0000 I  NETWORK  [conn3] received client metadata from 127.0.0.1:33318 conn3: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "4.2.2" }, os: { type: "Linux", name: "Ubuntu", architecture: "x86_64", version: "18.04" } }
mongo         | 2019-12-13T16:32:44.579+0000 I  NETWORK  [conn3] end connection 127.0.0.1:33318 (0 connections now open)
mongo         | 2019-12-13T16:32:54.837+0000 I  NETWORK  [listener] connection accepted from 127.0.0.1:34382 #4 (1 connection now open)
mongo         | 2019-12-13T16:32:54.837+0000 I  NETWORK  [conn4] received client metadata from 127.0.0.1:34382 conn4: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "4.2.2" }, os: { type: "Linux", name: "Ubuntu", architecture: "x86_64", version: "18.04" } }
mongo         | 2019-12-13T16:32:54.842+0000 I  NETWORK  [conn4] end connection 127.0.0.1:34382 (0 connections now open)
mongo         | 2019-12-13T16:33:05.083+0000 I  NETWORK  [listener] connection accepted from 127.0.0.1:35352 #5 (1 connection now open)
mongo         | 2019-12-13T16:33:05.083+0000 I  NETWORK  [conn5] received client metadata from 127.0.0.1:35352 conn5: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "4.2.2" }, os: { type: "Linux", name: "Ubuntu", architecture: "x86_64", version: "18.04" } }
mongo         | 2019-12-13T16:33:05.088+0000 I  NETWORK  [conn5] end connection 127.0.0.1:35352 (0 connections now open)
mongo         | 2019-12-13T16:33:15.356+0000 I  NETWORK  [listener] connection accepted from 127.0.0.1:36238 #6 (1 connection now open)
mongo         | 2019-12-13T16:33:15.356+0000 I  NETWORK  [conn6] received client metadata from 127.0.0.1:36238 conn6: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "4.2.2" }, os: { type: "Linux", name: "Ubuntu", architecture: "x86_64", version: "18.04" } }
mongo         | 2019-12-13T16:33:15.361+0000 I  NETWORK  [conn6] end connection 127.0.0.1:36238 (0 connections now open)
mongo         | 2019-12-13T16:33:25.624+0000 I  NETWORK  [listener] connection accepted from 127.0.0.1:37348 #7 (1 connection now open)
mongo         | 2019-12-13T16:33:25.625+0000 I  NETWORK  [conn7] received client metadata from 127.0.0.1:37348 conn7: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "4.2.2" }, os: { type: "Linux", name: "Ubuntu", architecture: "x86_64", version: "18.04" } }
mongo         | 2019-12-13T16:33:25.630+0000 I  NETWORK  [conn7] end connection 127.0.0.1:37348 (0 connections now open)
mongo         | 2019-12-13T16:33:35.878+0000 I  NETWORK  [listener] connection accepted from 127.0.0.1:38372 #8 (1 connection now open)
mongo         | 2019-12-13T16:33:35.878+0000 I  NETWORK  [conn8] received client metadata from 127.0.0.1:38372 conn8: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "4.2.2" }, os: { type: "Linux", name: "Ubuntu", architecture: "x86_64", version: "18.04" } }
mongo         | 2019-12-13T16:33:35.883+0000 I  NETWORK  [conn8] end connection 127.0.0.1:38372 (0 connections now open)
^CGracefully stopping... (press Ctrl+C again to force)
Stopping sharelatex ... done
Stopping mongo      ... done
Stopping redis      ... done
```

**Comment by mserranom** [comment]
Doesn't seem related to https://github.com/overleaf/overleaf/issues/572 because, in this case, you have confirmation that redis is running before sharelatex unsuccessfully attempts to connect to it.

Would you mind checking the version of docker you're using? Also worth double checking no changes to docker-compose.yml have been performed.

**Comment by twilsonco** [comment]
I'm using `Docker version 19.03.5, build 633a0ea838` on a fresh minimal install of Lubuntu 18.04 LTS per [these instructions](https://help.ubuntu.com/community/Lubuntu/Documentation/MinimalInstall) (command line install of Lubuntu-core) in a VM in Parallels Desktop 15 on macOS 10.15. The VM is on a network created by Parallels Desktop. 

(I didn't mention this earlier, but on one of my earlier attempts running docker-compose via DockStation, ShareLeTeX was able to load successfully and I was able to open it and start the configuration process in my browser. Having changed nothing, I restarted the "project" in DockStation—same as quitting and rerunning docker-compose—and then it failed to connect to mongo and Redis as in now the case)

Here's my docker-compose.yml file where the only changes from the provided docker-compose.yml are the ShareLatex, mongo, and Redis data folder host paths:

```
version: '2.2'
services:
  sharelatex:
    restart: always
    image: sharelatex/sharelatex
    container_name: sharelatex
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_started
    privileged: true
    ports:
      - '80:80'
    links:
      - mongo
      - redis
    volumes:
      - '/media/psf/ShareLaTeX_sync/sharelatex_data:/var/lib/sharelatex'
      - '/var/run/docker.sock:/var/run/docker.sock'
  mongo:
    restart: always
    image: mongo
    container_name: mongo
    expose:
      - 27017
    volumes:
      - '/media/psf/ShareLaTeX_sync/mongo_data:/data/db'
    healthcheck:
      test: 'echo ''db.stats().ok'' | mongo localhost:27017/test --quiet'
      interval: 10s
      timeout: 10s
      retries: 5
  redis:
    restart: always
    image: redis
    container_name: redis
    expose:
      - 6379
    volumes:
      - '/media/psf/ShareLaTeX_sync/redis_data:/data'
```

**Comment by mserranom** [comment]
Your configuration looks good. I have no experience with DockStation, I wonder if that extra component affects how networking is configured in Docker. Have you tried restarting docker and using exclusively `docker-compose` CLI?

**Comment by twilsonco** [comment]
As far as I can tell, DockStation just provides a GUI for editing and running docker-compose.yml files, with diagrams to show container linking structure and dialogs for editing volumes and env vars and stuff. Regardless, I took DockStation out of the equation once I started having issues, so my ticket was in regards to my experience with the docker-compose CLI. I just wanted to mention that it was working the first time I ran docker-compose (albeit through DockStation), but now does not, even though I have changed nothing.

I have docker running as a daemon. I restarted the VM and ran again and the same problem occurs.  

Since I'm almost out of ideas, I tried using a bridged network for the VM so that it has a direct connection to my network, removing any potential problems introduced by the Parallels Desktop internal DHCP server and network. The problem persists when a bridged network is used.

For completeness, here's the exact process I'm following, starting at the command line install of Lubuntu:

1. Install minimal version of Lubuntu using [these instructions](https://help.ubuntu.com/community/Lubuntu/Documentation/MinimalInstall):
Setup basic stuff (drive partitioning and acquisition of installation materials, then run 
```
sudo -i
apt-get install lubuntu-core
apt-get dist-upgrade
apt-get autoclean
rm /var/cache/apt/archives/*.deb
reboot
```

2. Boot into Lubuntu, then from terminal, [install docker](https://phoenixnap.com/kb/how-to-install-docker-on-ubuntu-18-04) from terminal (I've tried with both methods below, though the builds may be identical)
```
sudo apt install docker.io
sudo systemctl start docker
sudo systemctl enable docker
```
or 
```
sudo apt update
sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add –
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable" 
sudo apt-get update
sudo apt-get install docker-ce
```
3. Add user to docker group so you can execute docker commands by running `sudo usermod -a -G docker $USER`
4. reboot
5. Run docker-compose on my modified docker-compose.yml file
```
cd /media/psf/ShareLaTeX_sync # contains the share latex, mongo, and Redis directories specified in my docker-compose.yml file
docker-compose up
```

I just repeated this from a fresh install of Lubuntu and got the same results. Hopefully this helps to understand what's going on?

**Comment by mserranom** [comment]
I don't see any specific problem in your setup. I've no experience with lubuntu not its minimal installation. We know there are issues running Overleaf in small footprint distributions like Alpine, but not sure if that's related to your case. We [do recommend Ubuntu](https://github.com/overleaf/overleaf/wiki/Quick-Start-Guide#operating-systems) to run Overleaf.

**Comment by twilsonco** [comment]
Right. I’ll mirror this setup to ubuntu and see if that resolves it. On a sidenote, would it not be more efficient to host this on a smaller footprint OS? No reason for a more demanding OS GUI, detracting from the resources available to Overleaf, right? I chose Lubuntu after confirming (I thought, at least) that it was identical to Ubuntu under the hood. Regardless, I’ll update shortly with results.

**Comment by twilsonco** [comment]
I've now tried in a fresh install of Ubuntu 18.04 LTS, and I'm working with local directories for the share latex, mongo, and Redis data directories rather than shared folders from the host machine running the Ubuntu VM, and the problem persists, with the exact same output printed.

**Comment by ShaneKilkelly** [comment]
I have a feeling that this is a problem in the interaction between docker networking and Parallels Desktop. The docker-compose config creates a docker network on which the services will communicate, which seems to not be working for some reason not evident in the logs. I'm afraid this is beyond the scope of the support we can offer. I'd recommend contacting Parallels support, or posting on their forums to see if anyone else has encountered a similar problem.

**Comment by gutocarvalho** [comment]
I had the same problem here, docker 24.x running on top of Ubuntu 22.04 server.

To fix the problem I changed the connection string adding ?replicaSet=rs

SHARELATEX_MONGO_URL: mongodb://overleaf_mongo/sharelatex?replicaSet=rs

**Comment by calederer** [comment]
I ran into this issue running on older hardware. 
Looked at the docker logs for the mongo db:

WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
  see https://jira.mongodb.org/browse/SERVER-54407
  see also https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2
  see also https://github.com/docker-library/mongo/issues/485#issuecomment-891991814

**Comment by mlevans0** [comment]
Hey @calederer 

Recent versions of MongoDB use AVX CPU instructions, which I suspect your CPU/host does not support. The [Overleaf Toolkit](https://github.com/overleaf/toolkit) has the config `MONGO_IMAGE=third-party-mongo-image` in **config/overleaf.rc** to select a third-party MongoDB image that works on your host.
