### ISSUE TITLE
Can not open the website with the latest v2.1.0 image

### ISSUE THREAD

**Issue by yxnchen** [overleaf/overleaf#683]
## Steps to Reproduce

1. run `docker-compose up -d` with the latest sharelatex/sharelatex image (2.1.0)
2. open [localhost:5060](localhost:5060) in Chrome

## Expected Behaviour

Open the Overleaf website in browser

## Observed Behaviour

No UI loaded in browser but the following error message:
`TypeError: Cannot read property 'saml' of undefined
   at handleError (/var/www/sharelatex/web/app/src/Features/Errors/ErrorController.js:26:21)
   at Layer.handle_error (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:71:5)
   at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:310:13)
   at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)
   at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)
   at handleError (/var/www/sharelatex/web/app/src/Features/Errors/HttpErrorController.js:55:14)
   at Layer.handle_error (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:71:5)
   at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:310:13)
   at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)
   at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)
   at /var/www/sharelatex/web/node_modules/celebrate/lib/index.js:111:12
   at Layer.handle_error (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:71:5)
   at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:310:13)
   at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)
   at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)
   at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:615:15
   at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:256:14)
   at Layer.handle_error (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:67:12)
   at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:310:13)
   at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)
   at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)
   at Layer.handle_error (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:67:12)
   at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:310:13)
   at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)
   at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)
   at Layer.handle_error (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:67:12)
   at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:310:13)
   at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)
   at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)
   at Layer.handle_error (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:67:12)
   at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:310:13)
   at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)
   at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)
   at Layer.handle_error (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:67:12)
   at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:310:13)
   at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)
   at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)
   at Layer.handle_error (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:67:12)
   at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:310:13)
   at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)
   at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)
   at Layer.handle_error (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:67:12)
   at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:310:13)
   at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)
   at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)
   at Layer.handle_error (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:67:12)
   at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:310:13)
   at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)
   at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)
   at Layer.handle_error (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:67:12)
   at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:310:13)
   at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)
   at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)
   at Layer.handle_error (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:67:12)
   at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:310:13)
   at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)
   at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)
   at Layer.handle_error (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:67:12)
   at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:310:13)
   at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)
   at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)
   at Layer.handle_error (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:67:12)
   at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:310:13)
   at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)
   at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)
   at Layer.handle_error (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:67:12)
   at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:310:13)
   at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)
   at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)
   at Layer.handle_error (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:67:12)
   at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:310:13)
   at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)
   at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)
   at Layer.handle_error (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:67:12)
   at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:310:13)
   at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)
   at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)
   at Layer.handle_error (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:67:12)
   at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:310:13)
   at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)
   at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)
   at Layer.handle_error (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:67:12)
   at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:310:13)
   at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)
   at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)
   at Layer.handle_error (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:67:12)
   at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:310:13)
   at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)
   at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)
   at Layer.handle_error (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:67:12)
   at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:310:13)
   at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)
   at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)
   at Layer.handle_error (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:67:12)
   at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:310:13)
   at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)
   at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)
   at Layer.handle_error (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:67:12)
   at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:310:13)
   at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)
   at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)
   at Layer.handle_error (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:67:12)
   at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:310:13)
   at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)
   at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)
   at Layer.handle_error (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:67:12)
   at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:310:13)
   at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)
   at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)
   at Layer.handle_error (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:67:12)
   at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:310:13)
   at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)
   at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)
   at Layer.handle_error (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:67:12)
   at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:310:13)
   at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)
   at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)
   at Layer.handle_error (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:67:12)
   at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:310:13)
   at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)
   at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)
   at Layer.handle_error (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:67:12)
   at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:310:13)
   at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)
   at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)
   at csrf (/var/www/sharelatex/web/node_modules/csurf/index.js:71:14)
   at Csrf.middleware (/var/www/sharelatex/web/app/src/infrastructure/Csrf.js:65:14)
   at Layer.handle [as handle_request] (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:312:13)
   at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)
   at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)
   at SessionStrategy.strategy.pass (/var/www/sharelatex/web/node_modules/passport/lib/middleware/authenticate.js:325:9)
   at SessionStrategy.authenticate (/var/www/sharelatex/web/node_modules/passport/lib/strategies/session.js:71:10)
   at attempt (/var/www/sharelatex/web/node_modules/passport/lib/middleware/authenticate.js:348:16)
   at authenticate (/var/www/sharelatex/web/node_modules/passport/lib/middleware/authenticate.js:349:7)
   at Layer.handle [as handle_request] (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:312:13)
   at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)
   at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)
   at initialize (/var/www/sharelatex/web/node_modules/passport/lib/middleware/initialize.js:53:5)
   at Layer.handle [as handle_request] (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:312:13)
   at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)
   at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)
   at validationMiddleware (/var/www/sharelatex/web/app/src/infrastructure/SessionStoreManager.js:62:14)
   at Layer.handle [as handle_request] (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:312:13)
   at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)
   at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)
   at session (/var/www/sharelatex/web/node_modules/express-session/index.js:189:7)
   at Layer.handle [as handle_request] (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:312:13)
   at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)
   at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)
   at cookieParser (/var/www/sharelatex/web/node_modules/cookie-parser/index.js:34:14)
   at Layer.handle [as handle_request] (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:312:13)
   at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)
   at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)
   at SendStream.error (/var/www/sharelatex/web/node_modules/serve-static/index.js:120:7)
   at SendStream.emit (events.js:198:13)
   at SendStream.EventEmitter.emit (domain.js:448:20)
   at SendStream.error (/var/www/sharelatex/web/node_modules/serve-static/node_modules/send/index.js:245:17)
   at SendStream.onStatError (/var/www/sharelatex/web/node_modules/serve-static/node_modules/send/index.js:356:12)
   at next (/var/www/sharelatex/web/node_modules/serve-static/node_modules/send/index.js:658:28)
   at /var/www/sharelatex/web/node_modules/serve-static/node_modules/send/index.js:666:23
   at FSReqWrap.oncomplete (fs.js:153:21)`

![image](https://user-images.githubusercontent.com/8400698/72410595-b12dff00-37a3-11ea-96d4-424feaeeab52.png)

## Context

Can not open the proper website

## Technical Info

* URL:
* Browser Name and version: Chrome 79
* Operating System and version (desktop or mobile): Ubuntu 18.04
* Signed in as:
* Project and/or file:

## Analysis

Maybe something wrong with the front-end code

**Comment by ShaneKilkelly** [comment]
cc @mserranom

**Comment by ShaneKilkelly** [comment]
Hi @yxnchen , thanks for bringing this to our attention. Did you mean to close this issue? Is the error still happening?

**Comment by mserranom** [comment]
A fresh checkout and `docker-compose up -d` works correctly for me, can see the login page in http://localhost:80

**Comment by yxnchen** [comment]
> Hi @yxnchen , thanks for bringing this to our attention. Did you mean to close this issue? Is the error still happening?

Hi, I made some mistakes in the docker-compose file and the error has gone.

**Comment by claystation** [comment]
@yxnchen what did you change? What was the solution? I am having the same problem but i do not know how to fix it.

**Comment by claystation** [comment]
Okay never mind. I fixed it too. I use Unraid and used a given template for it. It missed the Redis environment variables. I had to set both SHARELATEX_REDIS_HOST and REDIS_HOST also the same for
SHARELATEX_REDIS_PORT and REDIS_PORT. That fixed my issue.

**Comment by muguruzawang** [comment]
> Okay never mind. I fixed it too. I use Unraid and used a given template for it. It missed the Redis environment variables. I had to set both SHARELATEX_REDIS_HOST and REDIS_HOST also the same for
> SHARELATEX_REDIS_PORT and REDIS_PORT. That fixed my issue.

Hello, could you tell me how you fixed this question. Because I also met with this question. When I update sharelatex to the newest version according to the official tutorial,  I can't visit the website.

**Comment by claystation** [comment]
@muguruzawang What is the error? Is it the same as the post? Did you specify all the environment variables i mentioned in my post? Can you show us your docker compose file? We need a little more information. I already mentioned in my post how i fixed it for my situation. So i need to know what you are running in to.

**Comment by muguruzawang** [comment]
version: '2.2'
services:
    sharelatex:
        restart: always
        # Server Pro users:
        # image: quay.io/sharelatex/sharelatex-pro
        image: sharelatex/sharelatex
        container_name: sharelatex
        depends_on:
            mongo:
                condition: service_healthy
            redis:
                condition: service_started
        privileged: true
        ports:
            - 81:80
        links:
            - mongo
            - redis
        volumes:
            - /root/sharelatex
            - /var/run/docker.sock:/var/run/docker.sock
        environment:

            PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/texlive/2019/bin/x86_64-linux

            SHARELATEX_APP_NAME: Our ShareLaTeX

            SHARELATEX_NAV_TITLE: Our ShareLaTeX Instance
            SHARELATEX_HEADER_IMAGE_URL: http://somewhere.com/mylogo.png
            SHARELATEX_LEFT_FOOTER: '[{"text": "Powered by <a href=\"https://www.nudtnlp.cn/moockg\">国防科技大学人工智能与大数据重点实验室</a> 2019"} ]'
            SHARELATEX_RIGHT_FOOTER: '[{"text": } ]'

            SHARELATEX_MONGO_URL: mongodb://mongo/sharelatex

            # Same property, unfortunately with different names in
            # different locations
            SHARELATEX_REDIS_HOST: redis
            REDIS_HOST: redis

            ENABLED_LINKED_FILE_TYPES: 'url,project_file'

            # Enables Thumbnail generation using ImageMagick
            ENABLE_CONVERSIONS: 'true'

            ## Set for SSL via nginx-proxy
            #VIRTUAL_HOST: 103.112.212.22

            # SHARELATEX_SITE_URL: http://sharelatex.mydomain.com
            # SHARELATEX_NAV_TITLE: Our ShareLaTeX Instance
            # SHARELATEX_HEADER_IMAGE_URL: http://somewhere.com/mylogo.png
            # SHARELATEX_ADMIN_EMAIL: support@it.com

            # SHARELATEX_LEFT_FOOTER: '[{"text": "Powered by <a href=\"https://www.sharelatex.com\">ShareLaTeX</a> 2016"},{"text": "Another page I want to link to can be found <a href=\"here\">here</a>"} ]'
            # SHARELATEX_RIGHT_FOOTER: '[{"text": "Hello I am on the Right"} ]'

            # SHARELATEX_EMAIL_FROM_ADDRESS: "team@sharelatex.com"

            # SHARELATEX_EMAIL_AWS_SES_ACCESS_KEY_ID:
            # SHARELATEX_EMAIL_AWS_SES_SECRET_KEY:

            # SHARELATEX_EMAIL_SMTP_HOST: smtp.mydomain.com
            # SHARELATEX_EMAIL_SMTP_PORT: 587
            # SHARELATEX_EMAIL_SMTP_SECURE: false
            # SHARELATEX_EMAIL_SMTP_USER:
            # SHARELATEX_EMAIL_SMTP_PASS:
            # SHARELATEX_EMAIL_SMTP_TLS_REJECT_UNAUTH: true
            # SHARELATEX_EMAIL_SMTP_IGNORE_TLS: false
            # SHARELATEX_CUSTOM_EMAIL_FOOTER: "<div>This system is run by department x </div>"

            ################
            ## Server Pro ##
            ################

            # SANDBOXED_COMPILES: 'true'

            # SANDBOXED_COMPILES_SIBLING_CONTAINERS: 'true'
            # SANDBOXED_COMPILES_HOST_DIR: '/var/sharelatex_data/data/compiles'
            # SYNCTEX_BIN_HOST_PATH: '/var/sharelatex_data/synctex'

            # DOCKER_RUNNER: 'false'

            ## Works with test LDAP server shown at bottom of docker compose
            # SHARELATEX_LDAP_URL: 'ldap://ldap:389'
            # SHARELATEX_LDAP_SEARCH_BASE: 'ou=people,dc=planetexpress,dc=com'
            # SHARELATEX_LDAP_SEARCH_FILTER: '(uid={{username}})'
            # SHARELATEX_LDAP_BIND_DN: 'cn=admin,dc=planetexpress,dc=com'
            # SHARELATEX_LDAP_BIND_CREDENTIALS: 'GoodNewsEveryone'
            # SHARELATEX_LDAP_EMAIL_ATT: 'mail'
            # SHARELATEX_LDAP_NAME_ATT: 'cn'
            # SHARELATEX_LDAP_LAST_NAME_ATT: 'sn'
            # SHARELATEX_LDAP_UPDATE_USER_DETAILS_ON_LOGIN: 'true'

            # SHARELATEX_TEMPLATES_USER_ID: "578773160210479700917ee5"
            # SHARELATEX_NEW_PROJECT_TEMPLATE_LINKS: '[ {"name":"All Templates","url":"/templates/all"}]'


            # SHARELATEX_PROXY_LEARN: "true"

    mongo:
        restart: always
        image: mongo
        container_name: mongo
        expose:
            - 27017
        volumes:
            - ~/sharelatex/mongo_data:/data/db
        healthcheck:
            test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
            interval: 10s
            timeout: 10s
            retries: 5

    redis:
        restart: always
        image: redis
        container_name: redis
        expose:
            - 6379
        volumes:
            - ~/sharelatex/redis_data:/data

    # ldap:
    #    restart: always
    #    image: rroemhild/test-openldap
    #    container_name: ldap
    #    expose:
    #        - 389
    
    # See https://github.com/jwilder/nginx-proxy for documentation on how to configure the nginx-proxy container,
    # and https://github.com/overleaf/overleaf/wiki/HTTPS-reverse-proxy-using-Nginx for an example of some recommended
    # settings. We recommend using a properly managed nginx instance outside of the Overleaf Server Pro setup,
    # but the example here can be used if you'd prefer to run everything with docker-compose
    
    # nginx-proxy:
    #     image: jwilder/nginx-proxy
    #     container_name: nginx-proxy
    #     ports:
    #       #- "80:80"
    #       - "443:443"
    #     volumes:
    #       - /var/run/docker.sock:/tmp/docker.sock:ro
    #       - /home/sharelatex/tmp:/etc/nginx/certs

**Comment by muguruzawang** [comment]
> @muguruzawang What is the error? Is it the same as the post? Did you specify all the environment variables i mentioned in my post? Can you show us your docker compose file? We need a little more information. I already mentioned in my post how i fixed it for my situation. So i need to know what you are running in

I set both SHARELATEX_REDIS_HOST and REDIS_HOST  the same. Actually the question is, after I update to the newest version, I can load and edit on the website, However, when the number of landings increased, the webiste crashed.  Maybe after some hour, it will be back  to normal.

I don't know whether it's because I don't make a back up before updating.

**Comment by claystation** [comment]
@muguruzawang You do miss the `SHARELATEX_REDIS_PORT` and `REDIS_PORT` though. Try adding those.

**Comment by muguruzawang** [comment]
OK. Thanks. I will try

**Comment by muguruzawang** [comment]
> @muguruzawang You do miss the `SHARELATEX_REDIS_PORT` and `REDIS_PORT` though. Try adding those.

Could you tell me how to setup  SHARELATEX_REDIS_PORT and REDIS_PORT?

**Comment by claystation** [comment]
Add

    SHARELATEX_REDIS_PORT: 6379
    REDIS_PORT: 6379

to your docker compose file under the `SHARELATEX_REDIS_HOST` and `REDIS_HOST` so it looks like the following:

    # Same property, unfortunately with different names in
    # different locations
    SHARELATEX_REDIS_HOST: redis
    REDIS_HOST: redis

    SHARELATEX_REDIS_PORT: 6379
    REDIS_PORT: 6379

**Comment by muguruzawang** [comment]
> Add
> 
> ```
> SHARELATEX_REDIS_PORT: 6379
> REDIS_PORT: 6379
> ```
> 
> to your docker compose file under the `SHARELATEX_REDIS_HOST` and `REDIS_HOST` so it looks like the following:
> 
> ```
> # Same property, unfortunately with different names in
> # different locations
> SHARELATEX_REDIS_HOST: redis
> REDIS_HOST: redis
> 
> SHARELATEX_REDIS_PORT: 6379
> REDIS_PORT: 6379
> ```

I did this as you suggested. But unfortunately, the problem still exists. When I try to click  the "Project" Button, the following question appears:
![image](https://user-images.githubusercontent.com/48216295/80347898-86257200-889f-11ea-9465-42315a589c66.png)

**Comment by claystation** [comment]
Could you look into the logs of the container? Do you see the same error as in the original post? If not, please create a new issue. It seems like you can still access the application, as you mentioned you could click buttons. Please verify you have the exact same problem/error as the original post.
