### ISSUE TITLE
Internal Server Error - userAffiliations Null

### ISSUE THREAD

**Issue by maxanier** [overleaf/overleaf#736]
## Steps to Reproduce

1. Update from an older release (I think 2.0.0 from dockerehub) to a custom build from the latest git (4faadc77f2a8219d9cec8e9ff7220ffdfe37fbd7)
2. Start docker-compose 
3. Login and go to /project

Not sure if the latest git branch is supposed to be work, but I want to modify the sharelatex-base image (install more tex packages), so the dockerhub images don't work for me.

## Expected Behaviour

See the project overview
## Observed Behaviour

Something went wrong (`500` server response)
In the web.log I can find:
```
{
  "name": "web",
  "hostname": "140948adc8e5",
  "pid": 121,
  "level": 50,
  "err": {
    "message": "/var/www/sharelatex/web/app/views/project/list/notifications.pug:180\n    178| \t\t\t\t\t|\n    179| \t\t\t\t\t| #{translate('resending_confirmation_email')}&hellip;\n  > 180| \t- var hasPaidAffiliation = userAffiliations.some(affiliation => affiliation.licence && affiliation.licence !== 'free')\n    181| \tif settings.enableSubscriptions && !hasSubscription && !hasPaidAffiliation\n    182| \t\tul.list-unstyled(\n  183| \t\t\tng-controller=\"DismissableNotificationsController\",\n\nCannot read property 'some' of null",
    "name": "TypeError",
    "stack": "TypeError: /var/www/sharelatex/web/app/views/project/list/notifications.pug:180\n    178| \t\t\t\t\t|\n    179| \t\t\t\t\t| #{translate('resending_confirmation_email')}&hellip;\n  > 180| \t- var hasPaidAffiliation = userAffiliations.some(affiliation => affiliation.licence && affiliation.licence !== 'free')\n    181| \tif settings.enableSubscriptions && !hasSubscription && !hasPaidAffiliation\n    182| \t\tul.list-unstyled(\n    183| \t\t\tng-controller=\"DismissableNotificationsController\",\n\nCannot read property 'some' of null\n  at eval (<anonymous>:1641:43)\n  at template (<anonymous>:3336:97)\n  atObject.exports.renderFile (/var/www/sharelatex/web/node_modules/pug/lib/index.js:427:38)\n  at Object.exports.renderFile (/var/www/sharelatex/web/node_modules/pug/lib/index.js:417:21)\n  at View.exports.__express [as engine] (/var/www/sharelatex/web/node_modules/pug/lib/index.js:464:11)\n  at View.render (/var/www/sharelatex/web/node_modules/express/lib/view.js:135:8)\n  at tryRender (/var/www/sharelatex/web/node_modules/express/lib/application.js:640:10)\n  at Function.render (/var/www/sharelatex/web/node_modules/express/lib/application.js:592:3)\n  at ServerResponse.render (/var/www/sharelatex/web/node_modules/express/lib/response.js:1012:7)\n  at ProjectController._injectProjectUsers (/var/www/sharelatex/web/app/src/Features/Project/ProjectController.js:605:15)\n  at async.eachSeries.error (/var/www/sharelatex/web/app/src/Features/Project/ProjectController.js:1043:9)\n  at /var/www/sharelatex/web/node_modules/async/lib/async.js:150:25\n  at UserGetter.getUser (/var/www/sharelatex/web/app/src/Features/Project/ProjectController.js:1026:13)\n  at /var/www/sharelatex/web/node_modules/metrics-sharelatex/statsd/timeAsyncMethod.coffee:36:13\n  at /var/www/sharelatex/web/node_modules/mongojs/lib/collection.js:50:5\n  at handleCallback (/var/www/sharelatex/web/node_modules/mongodb/lib/utils.js:120:56)\n  at /var/www/sharelatex/web/node_modules/mongodb/lib/cursor.js:683:5\n  at handleCallback (/var/www/sharelatex/web/node_modules/mongodb-core/lib/cursor.js:171:5)\n  at nextFunction (/var/www/sharelatex/web/node_modules/mongodb-core/lib/cursor.js:691:5)\n  at /var/www/sharelatex/web/node_modules/mongodb-core/lib/cursor.js:602:7\n  at queryCallback (/var/www/sharelatex/web/node_modules/mongodb-core/lib/cursor.js:232:18)\n at /var/www/sharelatex/web/node_modules/mongodb-core/lib/connection/pool.js:469:18\n  at process._tickCallback (internal/process/next_tick.js:61:11)\n",
    "info": {
      
    }
  },
  "url": "/project",
  "method": "GET",
  "user": {
    "id": "59d8f00caf5c88007ce7bf9a",
    "email": "xxxx"
  },
  "msg": "error passed to top level next middleware",
  "time": "2020-05-08T08:43:02.699Z",
  "v": 0
}
```
Apparently userAffiliations is null when rendering the pug

## Context

Cannot browse projects with existing or new users.
Accessing projects still works, if one knows the URL

## Analysis

I think the pug file is here https://github.com/overleaf/web/blob/3ba7d0aa36ac2bda28169983be2dd3c7808f5d54/app/views/project/list/notifications.pug#L180
Not sure where it is rendered or where userAffiliation is supposed to be set.

**Comment by das7pad** [comment]
Hi, thanks for flagging this. There was a patch ready last week, but it was not picked up for deploy until Monday: https://github.com/overleaf/web/commit/605656c9b4b47ee55ffde26858b1b4a4b690bb06

**Comment by maxanier** [comment]
Thank you!
