### ISSUE TITLE
Docker broken after running docker-compose.yaml

### ISSUE THREAD

**Issue by MNCODE** [overleaf/overleaf#746]
## Steps to Reproduce

Steps followed of this [Guide](https://www.scaleway.com/en/docs/installing-sharelatex-ubuntu/)

## Expected Behaviour

Running instance of sharelatex.

## Observed Behaviour

Sharelatex seems to be running 
```shell
sharelatex.service - ShareLaTeX Service
   Loaded: loaded (/etc/systemd/system/sharelatex.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2020-05-24 22:48:58 CEST; 15h ago
 Main PID: 12037 (docker-compose)
    Tasks: 6 (limit: 60)
   CGroup: /system.slice/sharelatex.service
           ├─12037 /usr/local/bin/docker-compose -f /etc/sharelatex/docker-compose.yml up
           └─12038 /usr/local/bin/docker-compose -f /etc/sharelatex/docker-compose.yml up

Mai 25 06:19:32 m-neitsch.de docker-compose[12037]: mongo         | 2020-05-25T04:19:32.550+0000 I  NETWORK  [conn1236]
Mai 25 09:50:42 m-neitsch.de docker-compose[12037]: mongo         | 2020-05-25T07:50:42.362+0000 I  NETWORK  [listener]
Mai 25 09:50:42 m-neitsch.de docker-compose[12037]: mongo         | 2020-05-25T07:50:42.363+0000 I  NETWORK  [conn1237]
Mai 25 09:50:42 m-neitsch.de docker-compose[12037]: mongo         | 2020-05-25T07:50:42.379+0000 I  NETWORK  [conn1237]
Mai 25 10:19:31 m-neitsch.de docker-compose[12037]: mongo         | 2020-05-25T08:19:30.626+0000 I  NETWORK  [listener]
Mai 25 10:19:31 m-neitsch.de docker-compose[12037]: mongo         | 2020-05-25T08:19:30.627+0000 I  NETWORK  [conn1238]
Mai 25 10:19:31 m-neitsch.de docker-compose[12037]: mongo         | 2020-05-25T08:19:30.639+0000 I  NETWORK  [conn1238]
Mai 25 10:20:43 m-neitsch.de docker-compose[12037]: mongo         | 2020-05-25T08:20:43.464+0000 I  NETWORK  [listener]
Mai 25 10:20:43 m-neitsch.de docker-compose[12037]: mongo         | 2020-05-25T08:20:43.465+0000 I  NETWORK  [conn1239]
Mai 25 10:20:43 m-neitsch.de docker-compose[12037]: mongo         | 2020-05-25T08:20:43.479+0000 I  NETWORK  [conn1239]
```

Docker is not working anymore. Evertime I call ```docker``` or any other docker command i get an error like this 
```shell
runtime/cgo: pthread_create failed: Resource temporarily unavailable
runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x7f158ffd0e97 m=3 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7f158ffd0e97
stack: frame={sp:0x7f158d57e830, fp:0x0} stack=[0x7f158cd7f288,0x7f158d57ee88)
00007f158d57e730:  0000000000000000  0000000000000000
00007f158d57e740:  0000000000000000  0000000000000000
00007f158d57e750:  0000000000000000  0000000000000000
00007f158d57e760:  0000000000000000  0000000000000000
00007f158d57e770:  00007f159037e560  00007f1590381bc0
00007f158d57e780:  0000007e0000007d  000000800000007f
00007f158d57e790:  00007f1580000010  00007f1580000010
00007f158d57e7a0:  000000000000000e  000000000000000e
00007f158d57e7b0:  0000000000000000  0000000000000000
00007f158d57e7c0:  ffffffffffffffff  ffffffffffffffff
00007f158d57e7d0:  0000000400000004  0000000400000004
00007f158d57e7e0:  00007f1580000800  00007f1580000800
00007f158d57e7f0:  2e2a3a36333b3030  333b30303d63706d
00007f158d57e800:  3d67676f2e2a3a36  2e2a3a36333b3030
00007f158d57e810:  36333b30303d6172  303d7661772e2a3a
00007f158d57e820:  6f2e2a3a36333b30  36333b30303d6167
00007f158d57e830: <0000000000000000  2e2a3a36333b3030
00007f158d57e840:  333b30303d787073  667073782e2a3a36
00007f158d57e850:  3a3a36333b30303d  3a36333b303d6964
00007f158d57e860:  00007f158d57e890  0000562916db9cbe <runtime.(*mTreap).end+78>
00007f158d57e870:  0000000000000000  0000562900000001
00007f158d57e880:  0000000000000000  0000000100000001
00007f158d57e890:  00007f158d57e920  0000562916dc366f <runtime.(*mheap).scavengeLocked+559>
00007f158d57e8a0:  0000562919f25108  0000000000000003
00007f158d57e8b0:  fffffffe7fffffff  ffffffffffffffff
00007f158d57e8c0:  ffffffffffffffff  ffffffffffffffff
00007f158d57e8d0:  ffffffffffffffff  ffffffffffffffff
00007f158d57e8e0:  ffffffffffffffff  ffffffffffffffff
00007f158d57e8f0:  ffffffffffffffff  ffffffffffffffff
00007f158d57e900:  ffffffffffffffff  ffffffffffffffff
00007f158d57e910:  ffffffffffffffff  ffffffffffffffff
00007f158d57e920:  ffffffffffffffff  ffffffffffffffff
runtime: unknown pc 0x7f158ffd0e97
stack: frame={sp:0x7f158d57e830, fp:0x0} stack=[0x7f158cd7f288,0x7f158d57ee88)
00007f158d57e730:  0000000000000000  0000000000000000
00007f158d57e740:  0000000000000000  0000000000000000
00007f158d57e750:  0000000000000000  0000000000000000
00007f158d57e760:  0000000000000000  0000000000000000
00007f158d57e770:  00007f159037e560  00007f1590381bc0
00007f158d57e780:  0000007e0000007d  000000800000007f
00007f158d57e790:  00007f1580000010  00007f1580000010
00007f158d57e7a0:  000000000000000e  000000000000000e
00007f158d57e7b0:  0000000000000000  0000000000000000
00007f158d57e7c0:  ffffffffffffffff  ffffffffffffffff
00007f158d57e7d0:  0000000400000004  0000000400000004
00007f158d57e7e0:  00007f1580000800  00007f1580000800
00007f158d57e7f0:  2e2a3a36333b3030  333b30303d63706d
00007f158d57e800:  3d67676f2e2a3a36  2e2a3a36333b3030
00007f158d57e810:  36333b30303d6172  303d7661772e2a3a
00007f158d57e820:  6f2e2a3a36333b30  36333b30303d6167
00007f158d57e830: <0000000000000000  2e2a3a36333b3030
00007f158d57e840:  333b30303d787073  667073782e2a3a36
00007f158d57e850:  3a3a36333b30303d  3a36333b303d6964
00007f158d57e860:  00007f158d57e890  0000562916db9cbe <runtime.(*mTreap).end+78>
00007f158d57e870:  0000000000000000  0000562900000001
00007f158d57e880:  0000000000000000  0000000100000001
00007f158d57e890:  00007f158d57e920  0000562916dc366f <runtime.(*mheap).scavengeLocked+559>
00007f158d57e8a0:  0000562919f25108  0000000000000003
00007f158d57e8b0:  fffffffe7fffffff  ffffffffffffffff
00007f158d57e8c0:  ffffffffffffffff  ffffffffffffffff
00007f158d57e8d0:  ffffffffffffffff  ffffffffffffffff
00007f158d57e8e0:  ffffffffffffffff  ffffffffffffffff
00007f158d57e8f0:  ffffffffffffffff  ffffffffffffffff
00007f158d57e900:  ffffffffffffffff  ffffffffffffffff
00007f158d57e910:  ffffffffffffffff  ffffffffffffffff
00007f158d57e920:  ffffffffffffffff  ffffffffffffffff

goroutine 1 [syscall, locked to thread]:
github.com/docker/cli/vendor/github.com/modern-go/reflect2.loadGo17Types()
        /go/src/github.com/docker/cli/vendor/github.com/modern-go/reflect2/type_map.go:80 +0x2a2 fp=0xc0001d7cc0 sp=0xc0001d7bf0 pc=0x562917982d02
github.com/docker/cli/vendor/github.com/modern-go/reflect2.init.0()
        /go/src/github.com/docker/cli/vendor/github.com/modern-go/reflect2/type_map.go:28 +0x96 fp=0xc0001d7cf0 sp=0xc0001d7cc0 pc=0x5629179823a6

goroutine 7 [syscall]:
os/signal.signal_recv(0x562916df8976)
        /usr/local/go/src/runtime/sigqueue.go:147 +0x9e
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x24
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:29 +0x43

goroutine 9 [chan receive]:
github.com/docker/cli/vendor/k8s.io/klog.(*loggingT).flushDaemon(0x562919f1e400)
        /go/src/github.com/docker/cli/vendor/k8s.io/klog/klog.go:1010 +0x8d
created by github.com/docker/cli/vendor/k8s.io/klog.init.0
        /go/src/github.com/docker/cli/vendor/k8s.io/klog/klog.go:411 +0xd8

rax    0x0
rbx    0x7f159037e840
rcx    0xffffffffffffffff
rdx    0x0
rdi    0x2
rsi    0x7f158d57e830
rbp    0x5629185dd669
rsp    0x7f158d57e830
r8     0x0
r9     0x7f158d57e830
r10    0x8
r11    0x246
r12    0x7f1580000c50
r13    0x0
r14    0x5629185833d4
r15    0x0
rip    0x7f158ffd0e97
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
```
## Technical Info

* Docker Version: ```sudo apt list docker-ce```
```shell
docker-ce/bionic,now 5:19.03.9~3-0~ubuntu-bionic amd64  [installiert]
```
(can't use docker to get the docker version because it`s broken)
* Operating System and version: Ubuntu 18.04
* Signed in as: User with sudo

RAM: 5.4G free
```free -m```
```shell
              Gesamt   belegt    frei        gemns. Puffer/Cache verfügbar
Speicher:        8192         601        5476        1468        2113        6121
Auslagerungsspeicher:           0           0           0
```
Disk Usage:
```df```-> not more than 10%

Server: 2 CPUs, 8GB RAM, 100 GB Disk

## Analysis

Already tried to set the TasksMax Property in the service file to infinity and already tried to upgrade the process limits of the user.

**Comment by mlevans0** [comment]
Hey there! As there hasn't been any recent comments or activity on this issue since May 2020, we’re going to close it to keep our tracker focused on the most active and current issues/questions.

If you’re still experiencing this issue and would like to keep it open, please verify the issue is present on the latest version of Overleaf CE and leave a comment to re-open. Thanks!
