### ISSUE TITLE
text editor not loading, connection lost / error opening document

### ISSUE THREAD

**Issue by Spiritreader** [overleaf/overleaf#749]
## Steps to Reproduce
1. Open any document, wait for it to load

## Expected Behaviour
Editor loads, can edit without connection drops.

## Observed Behaviour
The project opens and the pdf is rendering fine. However the text editor doesn't load 99% of the time and if it does, it only works for 2-3 seconds before a prompt tells me that the connection to the server is down and I need to reload.

## Technical Info
* Host System: Unraid 6.8.3
* Sharelatex Container Version: 2.2.0 (https://hub.docker.com/r/sharelatex/sharelatex)
* Redis Version: 5.0
* MongoDB Version: 3.6

### Container network configuration
* Redis: Bridge
* Overleaf: Bridge
* MongoDB: Bridge

### Important container env variables
![image](https://user-images.githubusercontent.com/18438899/83556111-9fa98180-a50f-11ea-9330-ade0d18edece.png)

### Description
Overleaf is running via HTTPS on a reverse proxy with websockets enabled. Loading the page, logging in, managing users and the likes works without issues. I can load a project without the "connection error" message, which indicates that websockets are working. My nginx log also lists that websocket communication is working.

```
[02/Jun/2020:18:24:48 +0000] - 200 200 - GET https $DOMAIN "/socket.io/1/?t=1591122287936" [Client $IP] [Length 83] [Gzip -] [Sent-to 10.11.12.5] "$USERAGENT" "$DOMAIN"
```

When opening the project, it looks like connecting to redis fails. This is strange because the redis connection check passes in the beginning.

This is the container log for the database checks when it starts up:
```
*** Running /etc/my_init.d/98_check_db_access.sh...
Checking can connect to mongo and redis
[4mRunning "check:redis" task[24m
Checking can connect to redis
node_redis: Warning: Redis server does not require a password, but a password was supplied.

OK.
[32mDone, without errors.[39m
[4mRunning "check:mongo" task[24m
Checking can connect to mongoOK.
[32mDone, without errors.[39m
All checks passed
``` 
### real-time.log
```
{"name":"real-time","hostname":"81d114ec3865","pid":137,"level":30,"client":"Sn4_fUh0rRHLTxpuMzA3","entity":"doc","id":"5ed68c96bac0a4007ca78f0d","beforeCount":0,"msg":"client joined new room and subscribed to channel","time":"2020-06-02T18:11:11.381Z","v":0}
{"name":"real-time","hostname":"81d114ec3865","pid":137,"level":50,"project_id":"5ed68c96bac0a4007ca78f0c","doc_id":"5ed68c96bac0a4007ca78f0d","user_id":"5ed68c7da62e160195a742b0","fromVersion":-1,"client_id":"Sn4_fUh0rRHLTxpuMzA3","err":{"message":"Reached the max retries per request limit (which is 20). Refer to \"maxRetriesPerRequest\" option for details.","name":"MaxRetriesPerRequestError","stack":"MaxRetriesPerRequestError: Reached the max retries per request limit (which is 20). Refer to \"maxRetriesPerRequest\" option for details.\n  at Socket.<anonymous> (/var/www/sharelatex/real-time/node_modules/ioredis/built/redis/event_handler.js:108:37)\n  at Object.onceWrapper (events.js:286:20)\n  at Socket.emit (events.js:198:13)\n  at TCP._handle.close (net.js:607:12)\n"},"msg":"server side error in joinDoc","time":"2020-06-02T18:11:11.381Z","v":0}
(node:137) UnhandledPromiseRejectionWarning: MaxRetriesPerRequestError: Reached the max retries per request limit (which is 20). Refer to "maxRetriesPerRequest" option for details.
  at Socket.<anonymous> (/var/www/sharelatex/real-time/node_modules/ioredis/built/redis/event_handler.js:108:37)
  at Object.onceWrapper (events.js:286:20)
  at Socket.emit (events.js:198:13)
  at TCP._handle.close (net.js:607:12)

(node:137) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
  at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)

[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
  at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)

(node:137) UnhandledPromiseRejectionWarning: MaxRetriesPerRequestError: Reached the max retries per request limit (which is 20). Refer to "maxRetriesPerRequest" option for details.
  at Socket.<anonymous> (/var/www/sharelatex/real-time/node_modules/ioredis/built/redis/event_handler.js:108:37)
  at Object.onceWrapper (events.js:286:20)
  at Socket.emit (events.js:198:13)
  at TCP._handle.close (net.js:607:12)

(node:137) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 11)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
  at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)

[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
  at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)

[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
  at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)

[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
  at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)

[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
  at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)

[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
  at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
```

### docstore.log
```
{"name":"docstore","hostname":"81d114ec3865","pid":127,"level":30,"project_id":"5ed68c96bac0a4007ca78f0c","doc_id":"5ed68c96bac0a4007ca78f0d","msg":"got http request to update doc","time":"2020-06-02T18:10:29.614Z","v":0}
{"name":"docstore","hostname":"81d114ec3865","pid":127,"level":30,"key":"mongo.MongoManager.findDoc","args":{"0":"5ed68c96bac0a4007ca78f0c","1":"5ed68c96bac0a4007ca78f0d"},"elapsedTime":2,"msg":"[Metrics] timed async method call","time":"2020-06-02T18:10:29.616Z","v":0}
{"name":"docstore","hostname":"81d114ec3865","pid":127,"level":30,"key":"mongo.MongoManager.getDocVersion","args":{"0":"5ed68c96bac0a4007ca78f0d"},"elapsedTime":1,"msg":"[Metrics] timed async method call","time":"2020-06-02T18:10:29.617Z","v":0}
{"name":"docstore","hostname":"81d114ec3865","pid":127,"level":30,"project_id":"5ed68c96bac0a4007ca78f0c","doc_id":"5ed68c96bac0a4007ca78f0d","msg":"doc lines have not changed - not updating","time":"2020-06-02T18:10:29.618Z","v":0}
{"name":"docstore","hostname":"81d114ec3865","pid":127,"level":30,"project_id":"5ed68c96bac0a4007ca78f0c","doc_id":"5ed68c96bac0a4007ca78f0d","version":7,"msg":"doc version has not changed - not updating","time":"2020-06-02T18:10:29.618Z","v":0}
{"name":"docstore","hostname":"81d114ec3865","pid":127,"level":30,"req":{"url":"/project/5ed68c96bac0a4007ca78f0c/doc/5ed68c96bac0a4007ca78f0d","method":"POST","remote-addr":"127.0.0.1","content-length":"940"},"res":{"statusCode":200},"response-time":5,"msg":"http request","time":"2020-06-02T18:10:29.618Z","v":0}
{"name":"docstore","hostname":"81d114ec3865","pid":127,"level":30,"project_id":"5ed68c96bac0a4007ca78f0c","doc_id":"5ed68c97bac0a4007ca78f0e","msg":"got http request to update doc","time":"2020-06-02T18:10:29.634Z","v":0}
{"name":"docstore","hostname":"81d114ec3865","pid":127,"level":30,"key":"mongo.MongoManager.findDoc","args":{"0":"5ed68c96bac0a4007ca78f0c","1":"5ed68c97bac0a4007ca78f0e"},"elapsedTime":2,"msg":"[Metrics] timed async method call","time":"2020-06-02T18:10:29.637Z","v":0}
{"name":"docstore","hostname":"81d114ec3865","pid":127,"level":30,"key":"mongo.MongoManager.getDocVersion","args":{"0":"5ed68c97bac0a4007ca78f0e"},"elapsedTime":1,"msg":"[Metrics] timed async method call","time":"2020-06-02T18:10:29.638Z","v":0}
{"name":"docstore","hostname":"81d114ec3865","pid":127,"level":30,"project_id":"5ed68c96bac0a4007ca78f0c","doc_id":"5ed68c97bac0a4007ca78f0e","msg":"doc lines have not changed - not updating","time":"2020-06-02T18:10:29.638Z","v":0}
{"name":"docstore","hostname":"81d114ec3865","pid":127,"level":30,"project_id":"5ed68c96bac0a4007ca78f0c","doc_id":"5ed68c97bac0a4007ca78f0e","version":0,"msg":"doc version has not changed - not updating","time":"2020-06-02T18:10:29.638Z","v":0}
{"name":"docstore","hostname":"81d114ec3865","pid":127,"level":30,"req":{"url":"/project/5ed68c96bac0a4007ca78f0c/doc/5ed68c97bac0a4007ca78f0e","method":"POST","remote-addr":"127.0.0.1","content-length":"269"},"res":{"statusCode":200},"response-time":4,"msg":"http request","time":"2020-06-02T18:10:29.639Z","v":0}
{"name":"docstore","hostname":"81d114ec3865","pid":127,"level":30,"project_id":"5ed68c96bac0a4007ca78f0c","doc_id":"5ed68ce3bac0a4007ca78f10","msg":"got http request to update doc","time":"2020-06-02T18:10:29.658Z","v":0}
{"name":"docstore","hostname":"81d114ec3865","pid":127,"level":30,"key":"mongo.MongoManager.findDoc","args":{"0":"5ed68c96bac0a4007ca78f0c","1":"5ed68ce3bac0a4007ca78f10"},"elapsedTime":2,"msg":"[Metrics] timed async method call","time":"2020-06-02T18:10:29.660Z","v":0}
{"name":"docstore","hostname":"81d114ec3865","pid":127,"level":30,"key":"mongo.MongoManager.getDocVersion","args":{"0":"5ed68ce3bac0a4007ca78f10"},"elapsedTime":1,"msg":"[Metrics] timed async method call","time":"2020-06-02T18:10:29.662Z","v":0}
{"name":"docstore","hostname":"81d114ec3865","pid":127,"level":30,"project_id":"5ed68c96bac0a4007ca78f0c","doc_id":"5ed68ce3bac0a4007ca78f10","msg":"doc lines have not changed - not updating","time":"2020-06-02T18:10:29.662Z","v":0}
{"name":"docstore","hostname":"81d114ec3865","pid":127,"level":30,"project_id":"5ed68c96bac0a4007ca78f0c","doc_id":"5ed68ce3bac0a4007ca78f10","version":0,"msg":"doc version has not changed - not updating","time":"2020-06-02T18:10:29.662Z","v":0}
{"name":"docstore","hostname":"81d114ec3865","pid":127,"level":30,"req":{"url":"/project/5ed68c96bac0a4007ca78f0c/doc/5ed68ce3bac0a4007ca78f10","method":"POST","remote-addr":"127.0.0.1","content-length":"36"},"res":{"statusCode":200},"response-time":5,"msg":"http request","time":"2020-06-02T18:10:29.662Z","v":0}
{"name":"docstore","hostname":"81d114ec3865","pid":127,"level":30,"project_id":"5ed68c96bac0a4007ca78f0c","msg":"getting all docs","time":"2020-06-02T18:10:29.668Z","v":0}
{"name":"docstore","hostname":"81d114ec3865","pid":127,"level":30,"key":"mongo.MongoManager.getArchivedProjectDocs","args":{"0":"5ed68c96bac0a4007ca78f0c"},"elapsedTime":2,"msg":"[Metrics] timed async method call","time":"2020-06-02T18:10:29.670Z","v":0}
{"name":"docstore","hostname":"81d114ec3865","pid":127,"level":30,"key":"mongo.MongoManager.getProjectsDocs","args":{"0":"5ed68c96bac0a4007ca78f0c"},"elapsedTime":2,"msg":"[Metrics] timed async method call","time":"2020-06-02T18:10:29.672Z","v":0}
{"name":"docstore","hostname":"81d114ec3865","pid":127,"level":30,"req":{"url":"/project/5ed68c96bac0a4007ca78f0c/doc","method":"GET","remote-addr":"127.0.0.1"},"res":{"statusCode":200},"response-time":5,"msg":"http request","time":"2020-06-02T18:10:29.673Z","v":0}
```

## Screenshots
Loading the project
![image](https://user-images.githubusercontent.com/18438899/83555826-3164bf00-a50f-11ea-8231-668947724f93.png)

Editor times out most of the time
![image](https://user-images.githubusercontent.com/18438899/83555955-640eb780-a50f-11ea-9203-68d3f75a47d5.png)

I feel like I have done my due diligence trying to get this to work and would like to ask for help:
What am I doing wrong?

**Comment by mserranom** [comment]
I understand `sharelatex` and `redis` container belong to the same network. Would you mind checking whether you're setting `REDIS_HOST` and `SHARELATEX_REDIS_HOST` as described in https://github.com/overleaf/overleaf/wiki/Release-Notes-2.0#changes-to-the-docker-compose-file-format ?

**Comment by Spiritreader** [comment]
Thank you so much, it's working now!
I spent way too much time trying to figure out why it wasn't connecting.
The docker template provided in the Unraid applications page does list those two environment variables.

I never would've figured it out on my own.
