### ISSUE TITLE
502 BAD Gateway  GET /user/emails

### ISSUE THREAD

**Issue by neel** [overleaf/overleaf#769]
```
GET http://47.254.133.138:5000/user/emails 502 (Bad Gateway)
GET http://47.254.133.138:5000/fonts/merriweather-v21-latin-700italic-1ef5edaaa20ae53ea50399884c5e48c6.woff2 net::ERR_ABORTED 502 (Bad Gateway)
GET http://47.254.133.138:5000/favicon.ico 502 (Bad Gateway)
GET http://47.254.133.138:5000/touch-icon-192x192.png 502 (Bad Gateway)
```

## Steps to Reproduce
After installing sharelatex with docker restored mongodb and filesystem backup (filesystem backup doesn't seem to work)

## Expected Behaviour
No errors in networks panel

## Observed Behaviour

In web.log

```
{"name":"web","hostname":"dbb2c8db5967","pid":571,"level":30,"key":"mongo.UserGetter.getUser","args":{"0":"569a4693cbb1a98900180549"},"elapsedTime":9,"msg":"[Metrics] timed async method call","time":"2020-08-19T14:59:59.576Z","v":0}
/var/www/sharelatex/web/node_modules/mongodb/lib/utils.js:123
    process.nextTick(function() { throw err; });
                                  ^

TypeError: Cannot read property 'map' of undefined
  at decorateFullEmails (/var/www/sharelatex/web/app/src/Features/User/UserGetter.js:175:14)
  at /var/www/sharelatex/web/app/src/Features/User/UserGetter.js:47:11
  at /var/www/sharelatex/web/node_modules/metrics-sharelatex/statsd/timeAsyncMethod.coffee:36:13
  at /var/www/sharelatex/web/node_modules/mongojs/lib/collection.js:50:5
  at handleCallback (/var/www/sharelatex/web/node_modules/mongodb/lib/utils.js:120:56)
  at /var/www/sharelatex/web/node_modules/mongodb/lib/cursor.js:683:5
  at handleCallback (/var/www/sharelatex/web/node_modules/mongodb-core/lib/cursor.js:171:5)
  at nextFunction (/var/www/sharelatex/web/node_modules/mongodb-core/lib/cursor.js:691:5)
  at /var/www/sharelatex/web/node_modules/mongodb-core/lib/cursor.js:602:7
  at queryCallback (/var/www/sharelatex/web/node_modules/mongodb-core/lib/cursor.js:232:18)
  at /var/www/sharelatex/web/node_modules/mongodb-core/lib/connection/pool.js:469:18
  at process._tickCallback (internal/process/next_tick.js:61:11)

using statsd
Set UV_THREADPOOL_SIZE=16
{"name":"web","hostname":"dbb2c8db5967","pid":595,"level":40,"msg":"Email transport and/or parameters not defined. No emails will be sent.","time":"2020-08-19T15:00:01.277Z","v":0}

```

**Comment by das7pad** [comment]
Hi there.

You may be missing a migration. Here is how I would restore a full backup:
- start the mongo container only
- run the restore of mongo data
- copy the redis backup and user files
- start the redis and sharelatex container

The sequence for restoring the backup and starting the sharelatex container is important here. The later is running migrations as part of its startup. Each migration shall run only once. So in case you started all containers and then ran the mongo restore, your old data is not covered by all the migrations -- which in turn ran on an empty database.

You may get this sorted again in proceeding as followed:
- tear down all containers
- delete all the data dirs (only mongo is actually required)
- go though my above list

**Comment by neel** [comment]
I am serving mongo and redis from the vm itself outside the container. Should I interpret this as `stop` and `start` those services in that order ?

**Comment by neel** [comment]
Thanks Worked

**Comment by das7pad** [comment]
Great, thanks for confirming.
