### ISSUE TITLE
Cannot Migrate old projects to the new Instance

### ISSUE THREAD

**Issue by neel** [overleaf/overleaf#770]
## Steps to Reproduce

1. Install sharelatex through `docker-compose`
2. `mongorestore` with previous installation's backup
3. copied previous installation's `sharelatex_data` and paste to the new installation

## Expected Behaviour

The previous Projects will open along with the newly created projects

## Observed Behaviour

1. New projects can be created and compiled
2. Old projects (migrated) are listed properly and can be opened
3. Binary files of the old projects can be viewed by clicking on the filename on the sidebar
4. **The Old projects can NOT be compiled.**

![Screenshot_20200819_204037](https://user-images.githubusercontent.com/20411/90653025-5211fa80-e25c-11ea-919e-97f9ea5767ed.png)
![Screenshot_20200819_204152](https://user-images.githubusercontent.com/20411/90653126-7077f600-e25c-11ea-8a6b-b5d265856b6d.png)

## Context

Cannot compile old projects migrated from the previous installation.

## Technical Info

> GET /project/5c6fdcc92faa4edd00b15f0a/metadata
> 
>     {"projectId":"5c6fdcc92faa4edd00b15f0a","projectMeta":{}}
> 
> 

> POST /project/5c6fdcc92faa4edd00b15f0a/compile?auto_compile=true
> 
>     {"status":"validation-problems","outputFiles":null,"compileGroup":"standard","clsiServerId":null,"validationProblems":{"mainFile":"no main file specified"}}

```
==> docstore.log <==
{"name":"docstore","hostname":"dbb2c8db5967","pid":112,"level":50,"err":{"message":"No such doc: 5c753c559dca184900b4d7b2 in project 5c6fdcc92faa4edd00b15f0a","name":"NotFoundError","stack":"NotFoundError: No such doc: 5c753c559dca184900b4d7b2 in project 5c6fdcc92faa4edd00b15f0a\n    at /var/www/sharelatex/docstore/app/js/DocManager.js:48:11\n    at /var/www/sharelatex/docstore/node_modules/metrics-sharelatex/statsd/timeAsyncMethod.coffee:49:25\n    at /var/www/sharelatex/docstore/app/js/MongoManager.js:34:16\n    at /var/www/sharelatex/docstore/node_modules/mongojs/lib/cursor.js:73:24\n    at AsyncResource.runInAsyncScope (async_hooks.js:188:21)\n    at runInAsyncScope (/var/www/sharelatex/docstore/node_modules/mongojs/lib/cursor.js:195:16)\n    at /var/www/sharelatex/docstore/node_modules/mongojs/lib/cursor.js:205:5\n    at /var/www/sharelatex/docstore/node_modules/mongodb/lib/utils.js:731:5\n    at cursor._next (/var/www/sharelatex/docstore/node_modules/mongodb/lib/cursor.js:251:9)\n    at self._initializeCursor (/var/www/sharelatex/docstore/node_modules/mongodb/lib/core/cursor.js:750:9)\n    at handleCallback (/var/www/sharelatex/docstore/node_modules/mongodb/lib/core/cursor.js:32:5)\n    at _setCursorNotifiedImpl (/var/www/sharelatex/docstore/node_modules/mongodb/lib/core/cursor.js:694:38)\n    at self._endSession (/var/www/sharelatex/docstore/node_modules/mongodb/lib/core/cursor.js:703:39)\n    at Cursor._endSession (/var/www/sharelatex/docstore/node_modules/mongodb/lib/core/cursor.js:404:7)\n    at _setCursorNotifiedImpl (/var/www/sharelatex/docstore/node_modules/mongodb/lib/core/cursor.js:703:10)\n    at setCursorNotified (/var/www/sharelatex/docstore/node_modules/mongodb/lib/core/cursor.js:694:3)\n    at done (/var/www/sharelatex/docstore/node_modules/mongodb/lib/core/cursor.js:460:16)\n    at queryCallback (/var/www/sharelatex/docstore/node_modules/mongodb/lib/core/cursor.js:509:18)\n    at executeOperation (/var/www/sharelatex/docstore/node_modules/mongodb/lib/core/cursor.js:559:9)\n    at executeCallback (/var/www/sharelatex/docstore/node_modules/mongodb/lib/operations/execute_operation.js:70:5)\n    at callbackWithRetry (/var/www/sharelatex/docstore/node_modules/mongodb/lib/operations/execute_operation.js:118:14)\n    at fn (/var/www/sharelatex/docstore/node_modules/mongodb/lib/cmap/connection_pool.js:352:13)\n    at handleOperationResult (/var/www/sharelatex/docstore/node_modules/mongodb/lib/core/sdam/server.js:487:5)\n    at MessageStream.messageHandler (/var/www/sharelatex/docstore/node_modules/mongodb/lib/cmap/connection.js:270:5)\n    at MessageStream.emit (events.js:198:13)\n    at MessageStream.EventEmitter.emit (domain.js:448:20)\n    at processIncomingData (/var/www/sharelatex/docstore/node_modules/mongodb/lib/cmap/message_stream.js:144:12)\n    at MessageStream._write (/var/www/sharelatex/docstore/node_modules/mongodb/lib/cmap/message_stream.js:42:5)\n    at doWrite (_stream_writable.js:415:12)\n    at writeOrBuffer (_stream_writable.js:399:5)\n    at MessageStream.Writable.write (_stream_writable.js:299:11)\n    at Socket.ondata (_stream_readable.js:710:20)\n    at Socket.emit (events.js:198:13)\n    at Socket.EventEmitter.emit (domain.js:448:20)\n    at addChunk (_stream_readable.js:288:12)\n    at readableAddChunk (_stream_readable.js:269:11)\n    at Socket.Readable.push (_stream_readable.js:224:10)\n    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)","info":{}},"req":{"method":"GET","url":"/project/5c6fdcc92faa4edd00b15f0a/doc/5c753c559dca184900b4d7b2","headers":{"host":"localhost:3016","accept":"application/json","connection":"keep-alive"},"remoteAddress":"127.0.0.1","remotePort":60890},"msg":"request errored","time":"2020-08-19T15:20:06.619Z","v":0}
{"name":"docstore","hostname":"dbb2c8db5967","pid":112,"level":40,"req":{"url":"/project/5c6fdcc92faa4edd00b15f0a/doc/5c753c559dca184900b4d7b2","method":"GET","remote-addr":"127.0.0.1"},"res":{"statusCode":404},"response-time":3176,"msg":"GET /project/5c6fdcc92faa4edd00b15f0a/doc/5c753c559dca184900b4d7b2","time":"2020-08-19T15:20:06.619Z","v":0}
{"name":"docstore","hostname":"dbb2c8db5967","pid":112,"level":30,"project_id":"5c6fdcc92faa4edd00b15f0a","msg":"getting all docs","time":"2020-08-19T15:20:06.771Z","v":0}
{"name":"docstore","hostname":"dbb2c8db5967","pid":112,"level":30,"key":"mongo.MongoManager.getArchivedProjectDocs","args":{"0":"5c6fdcc92faa4edd00b15f0a"},"elapsedTime":1,"msg":"[Metrics] timed async method call","time":"2020-08-19T15:20:06.772Z","v":0}
{"name":"docstore","hostname":"dbb2c8db5967","pid":112,"level":30,"key":"mongo.MongoManager.getProjectsDocs","args":{"0":"5c6fdcc92faa4edd00b15f0a"},"elapsedTime":1,"msg":"[Metrics] timed async method call","time":"2020-08-19T15:20:06.773Z","v":0}
{"name":"docstore","hostname":"dbb2c8db5967","pid":112,"level":30,"req":{"url":"/project/5c6fdcc92faa4edd00b15f0a/doc","method":"GET","remote-addr":"127.0.0.1"},"res":{"statusCode":200},"response-time":2209,"msg":"GET /project/5c6fdcc92faa4edd00b15f0a/doc","time":"2020-08-19T15:20:06.774Z","v":0}
{"name":"docstore","hostname":"dbb2c8db5967","pid":112,"level":30,"project_id":"5c6fdcc92faa4edd00b15f0a","msg":"getting all docs","time":"2020-08-19T15:20:07.059Z","v":0}
{"name":"docstore","hostname":"dbb2c8db5967","pid":112,"level":30,"key":"mongo.MongoManager.getArchivedProjectDocs","args":{"0":"5c6fdcc92faa4edd00b15f0a"},"elapsedTime":1,"msg":"[Metrics] timed async method call","time":"2020-08-19T15:20:07.060Z","v":0}
{"name":"docstore","hostname":"dbb2c8db5967","pid":112,"level":30,"key":"mongo.MongoManager.getProjectsDocs","args":{"0":"5c6fdcc92faa4edd00b15f0a"},"elapsedTime":1,"msg":"[Metrics] timed async method call","time":"2020-08-19T15:20:07.062Z","v":0}
{"name":"docstore","hostname":"dbb2c8db5967","pid":112,"level":30,"req":{"url":"/project/5c6fdcc92faa4edd00b15f0a/doc","method":"GET","remote-addr":"127.0.0.1"},"res":{"statusCode":200},"response-time":2863,"msg":"GET /project/5c6fdcc92faa4edd00b15f0a/doc","time":"2020-08-19T15:20:07.062Z","v":0}

```

## Analysis

There is an error reported in the first line of `docstore.log`

How the `tex` files are stored ? In monogdb ? or in `/var/lib/sharelatex` ? Did the mongodb schema change in different versions ?

## Observations

Also encountered #769

**Comment by das7pad** [comment]
Hi there.

You may be missing data that was stored in redis only at the time you took the backup of your old instance. Do you still have the old redis data directory around? Copying the `dump.rdb` file over to the new host may get you back on track.

**Comment by neel** [comment]
@das7pad Tried

    scp fedora@old-servercom:/tmp/dump.rdb /var/lib/redis/dump.rdb 

Didn't work

**Comment by das7pad** [comment]
Just to make sure: the default redis data dir in here: https://github.com/overleaf/overleaf/blob/7c9ec6c63893e53028d4472f64a165f6e0b275f8/docker-compose.yml#L124

Did you adjust your docker-compose file to bind `/var/lib/redis/:/data` into the redis container?

**Comment by neel** [comment]
In my case The mongo and the docker is running outside the container.

**Comment by neel** [comment]
Worked after first restoring the data then composing docker
