### ISSUE TITLE
Error "Something went wrong" when creating or joining a project (internal 403 error)

### ISSUE THREAD

**Issue by dvmc** [overleaf/overleaf#802]
(This bug shows symptoms in different places, so the bug report template might not be adequate. However, I suspect that these two bugs have a common root cause due to their similarity. I will try my best to still adhere to the bug report template. I hope it's not too many logs.)

## Steps to Reproduce

Either

* Create a new blank project with any name from the main dashboard (`/project`).

or

* Join an existing project from the main dashboard by clicking on it.

## Expected Behaviour

* When creating a new project: The project should be created without any error message.
* When joining a project: The project should open

## Observed Behaviour

* When creating a new project: Error message `Sorry, something went wrong`, and the creation interface does not close. However, when refreshing the main dashboard, the new project is listed.
* When joining this newly created project: The Overleaf logo loads until shortly before the leaf. A popup appears, which is titled: `Something went wrong connecting`. It reopens after every retry, which is every few seconds.

## Context

I was trying to test Overleaf for the first time and create a few projects. It should be noted that it's behind an nginx reverse proxy, and that there is a network proxy for the outside world.

## Technical Info

* URL: https://server5.example.com:2025/
* Browser Name and version: Firefox 81.0.2 (64-Bit)
* Operating System and version (desktop or mobile): Ubuntu 16.04.6 LTS
* Signed in as: admin (first account)
* Project and/or file:

#### Network Monitor

* Request

```
POST /project/new HTTP/1.1
Host: server5.example.com:2025
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0
Accept: application/json, text/plain, */*
Accept-Language: de,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
Referer: https://server5.example.com:2025/project
Content-Type: application/json;charset=utf-8
Content-Length: 84
Origin: https://server5.example.com:2025
Connection: keep-alive
Cookie: express_sid=s%3AqoR8zuHV2_xtxCfSd2Fgc8xXL__Quun2.JNJmD9mu%2BARpxjEHAtZrV%2BaCrFcGntGpHiMoAO0vL9Y; sharelatex.sid=s%3AWCFB62jhs3Qf3ocrvFk0hCdDjlBqDi-0.fNwJsFmEMWKK7ytsBOV1p4BToB1EC7OUYL3%2Bak2h%2B5c
```

* Response
```
HTTP/1.1 500 Internal Server Error
Server: nginx
Date: Fri, 16 Oct 2020 14:47:46 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 842
Connection: keep-alive
Vary: X-HTTP-Method-Override
Content-Language: en
Surrogate-Control: no-store
Cache-Control: no-store, no-cache, must-revalidate, proxy-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: SAMEORIGIN
X-Download-Options: noopen
X-Content-Type-Options: nosniff
Referrer-Policy: origin-when-cross-origin
X-XSS-Protection: 1; mode=block
ETag: W/"34a-W12CV5VPR4aatmzCFHwGs0FVM0k"
Set-Cookie: sharelatex.sid=s%3AWCFB62jhs3Qf3ocrvFk0hCdDjlBqDi-0.fNwJsFmEMWKK7ytsBOV1p4BToB1EC7OUYL3%2Bak2h%2B5c; Path=/; Expires=Wed, 21 Oct 2020 14:47:46 GMT; HttpOnly; Secure; SameSite=Lax
```

#### `/var/log/sharelatex/web.log`
```
{"name":"web","hostname":"6a65d416a305","pid":112,"level":30,"key":"mongo.ProjectCreationHandler.createBlankProject","args":{"0":"5f8706265c09bc00853932f8"},"elapsedTime":12,"msg":"[Metrics] timed async method call","time":"2020-10-16T14:47:46.896Z","v":0}
{"name":"web","hostname":"6a65d416a305","pid":112,"level":50,"err":{"message":"docstore api responded with non-success code: 403","name":"OError","stack":"OError: docstore api responded with non-success code: 403\n  at Request._callback (/var/www/sharelatex/web/app/src/Features/Docstore/DocstoreManager.js:204:19)\n  at Request.self.callback (/var/www/sharelatex/web/node_modules/request/request.js:185:22)\n  at Request.emit (events.js:198:13)\n  at Request.EventEmitter.emit (domain.js:448:20)\n  at Request.<anonymous> (/var/www/sharelatex/web/node_modules/request/request.js:1154:10)\n  at Request.emit (events.js:198:13)\n  at Request.EventEmitter.emit (domain.js:448:20)\n  at IncomingMessage.<anonymous> (/var/www/sharelatex/web/node_modules/request/request.js:1076:12)\n  at Object.onceWrapper (events.js:286:20)\n  at IncomingMessage.emit (events.js:203:15)\n  at IncomingMessage.EventEmitter.emit (domain.js:448:20)\n  at endReadableNT (_stream_readable.js:1145:12)\n  at process._tickCallback (internal/process/next_tick.js:63:19)\n\n[object Object]\n  at /var/www/sharelatex/web/app/src/Features/Project/ProjectCreationHandler.js:264:18\n  at DocstoreManager.updateDoc (/var/www/sharelatex/web/app/src/Features/Project/ProjectEntityUpdateHandler.js:283:22)\n  at Request._callback (/var/www/sharelatex/web/app/src/Features/Docstore/DocstoreManager.js:208:18)\n  at Request.self.callback (/var/www/sharelatex/web/node_modules/request/request.js:185:22)\n  at Request.emit (events.js:198:13)\n  at Request.EventEmitter.emit (domain.js:448:20)\n  at Request.<anonymous> (/var/www/sharelatex/web/node_modules/request/request.js:1154:10)\n  at Request.emit (events.js:198:13)\n  at Request.EventEmitter.emit (domain.js:448:20)\n  at IncomingMessage.<anonymous> (/var/www/sharelatex/web/node_modules/request/request.js:1076:12)\n  at Object.onceWrapper (events.js:286:20)\n  at IncomingMessage.emit (events.js:203:15)\n  at IncomingMessage.EventEmitter.emit (domain.js:448:20)\n  at endReadableNT (_stream_readable.js:1145:12)\n  at process._tickCallback (internal/process/next_tick.js:63:19)\n","info":{"project_id":"5f89b292d0adac00701f2f26","doc_id":"5f89b292d0adac00701f2f27"}},"url":"/project/new","method":"POST","user":{"id":"5f8706265c09bc00853932f8","email":"david.michaelis@example.com"},"msg":"error passed to top level next middleware","time":"2020-10-16T14:47:46.933Z","v":0}
{"name":"web","hostname":"6a65d416a305","pid":112,"level":50,"req":{"url":"/project/new","method":"POST","referrer":"https://server5.example.com:2025/project","remote-addr":"172.29.246.134","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","content-length":"86"},"res":{"statusCode":500},"response-time":106193,"msg":"POST /project/new","time":"2020-10-16T14:47:46.984Z","v":0}
{"name":"web","hostname":"6a65d416a305","pid":112,"level":30,"rss":"125.14","heapTotal":"86.21","heapUsed":"74.62","external":"17.32","msg":"process.memoryUsage()","time":"2020-10-16T14:48:12.579Z","v":0}
```

#### `/var/log/sharelatex/docstore.log`
```
using statsd
Set UV_THREADPOOL_SIZE=16
{"name":"document-updater","hostname":"6a65d416a305","pid":115,"level":30,"msg":"Document-updater starting up, listening on localhost:3003","time":"2020-10-16T14:20:12.860Z","v":0}
redis event: connect undefined
redis event: ready undefined
```

#### Network Monitor

* Request 1
```
GET /socket.io/1/?t=1602860498795 HTTP/1.1
Host: server5.example.com:2025
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0
Accept: */*
Accept-Language: de,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
Referer: https://server5.example.com:2025/project/5f89b292d0adac00701f2f26
Connection: keep-alive
Cookie: express_sid=s%3AqoR8zuHV2_xtxCfSd2Fgc8xXL__Quun2.JNJmD9mu%2BARpxjEHAtZrV%2BaCrFcGntGpHiMoAO0vL9Y; sharelatex.sid=s%3AWCFB62jhs3Qf3ocrvFk0hCdDjlBqDi-0.fNwJsFmEMWKK7ytsBOV1p4BToB1EC7OUYL3%2Bak2h%2B5c
```

* Response 1
```
HTTP/1.1 200 OK
Server: nginx
Date: Fri, 16 Oct 2020 15:01:38 GMT
Content-Type: text/plain
Transfer-Encoding: chunked
Connection: keep-alive
```

* Response Content 1
```
IDJuVGWezZfaEloOyE26:60:60:websocket,flashsocket,htmlfile,xhr-polling,jsonp-polling
```

* Request 2
```
GET /socket.io/1/websocket/IDJuVGWezZfaEloOyE26 HTTP/1.1
Host: server5.example.com:2025
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0
Accept: */*
Accept-Language: de,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
Sec-WebSocket-Version: 13
Origin: https://server5.example.com:2025
Sec-WebSocket-Extensions: permessage-deflate
Sec-WebSocket-Key: yHftAx05eOPBZqrMkQONpA==
Connection: keep-alive, Upgrade
Cookie: express_sid=s%3AqoR8zuHV2_xtxCfSd2Fgc8xXL__Quun2.JNJmD9mu%2BARpxjEHAtZrV%2BaCrFcGntGpHiMoAO0vL9Y; sharelatex.sid=s%3AWCFB62jhs3Qf3ocrvFk0hCdDjlBqDi-0.fNwJsFmEMWKK7ytsBOV1p4BToB1EC7OUYL3%2Bak2h%2B5c
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket
```

* Response 2
```
HTTP/1.1 101 Switching Protocols
Server: nginx
Date: Fri, 16 Oct 2020 15:01:39 GMT
Connection: upgrade
Upgrade: websocket
Sec-WebSocket-Accept: +Zkv9iGKvOAFV4wlV+k8PwsN1sk=
```

* Content 2 (Websocket)
```
1::
5:::{"name":"connectionAccepted","args":[null,"P.6vLTpX18sx6gQxvDAAAS"]}
5:4+::{"name":"joinProject","args":[{"project_id":"5f89b292d0adac00701f2f26"}]}
6:::4+[{"message":"Something went wrong in real-time service"}]
0::
0::
```

#### `/var/log/sharelatex/web.log`

```
{"name":"web","hostname":"6a65d416a305","pid":112,"level":30,"user_id":"5f8706265c09bc00853932f8","msg":"got users subscription","time":"2020-10-16T15:01:09.116Z","v":0}
{"name":"web","hostname":"6a65d416a305","pid":112,"level":50,"err":null,"msg":"something went wrong getting notifications","time":"2020-10-16T15:01:09.147Z","v":0}
{"name":"web","hostname":"6a65d416a305","pid":112,"level":30,"key":"mongo.UserGetter.getUser","args":{"0":"5f8706265c09bc00853932f8"},"elapsedTime":2,"msg":"[Metrics] timed async method call","time":"2020-10-16T15:01:09.155Z","v":0}
{"name":"web","hostname":"6a65d416a305","pid":112,"level":40,"offset":1211,"msg":"slow event loop","time":"2020-10-16T15:01:10.417Z","v":0}
{"name":"web","hostname":"6a65d416a305","pid":112,"level":30,"req":{"url":"/project","method":"GET","remote-addr":"172.29.246.134","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"},"res":{"statusCode":200},"response-time":330700,"msg":"GET /project","time":"2020-10-16T15:01:10.419Z","v":0}
{"name":"web","hostname":"6a65d416a305","pid":112,"level":30,"req":{"url":"/system/messages","method":"GET","referrer":"https://server5.example.com:2025/project","remote-addr":"172.29.246.134","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"},"res":{"statusCode":200},"response-time":6123,"msg":"GET /system/messages","time":"2020-10-16T15:01:10.685Z","v":0}
{"name":"web","hostname":"6a65d416a305","pid":112,"level":30,"key":"mongo.UserGetter.getUser","args":{"0":"5f8706265c09bc00853932f8"},"elapsedTime":3,"msg":"[Metrics] timed async method call","time":"2020-10-16T15:01:10.798Z","v":0}
{"name":"web","hostname":"6a65d416a305","pid":112,"level":30,"req":{"url":"/user/emails","method":"GET","referrer":"https://server5.example.com:2025/project","remote-addr":"172.29.246.134","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"},"res":{"statusCode":200},"response-time":7847,"msg":"GET /user/emails","time":"2020-10-16T15:01:10.800Z","v":0}
{"name":"web","hostname":"6a65d416a305","pid":112,"level":30,"rss":"151.85","heapTotal":"111.67","heapUsed":"91.30","external":"17.38","msg":"process.memoryUsage()","time":"2020-10-16T15:01:12.589Z","v":0}
{"name":"web","hostname":"6a65d416a305","pid":112,"level":30,"key":"mongo.ProjectGetter.getProject","args":{"0":"5f89b292d0adac00701f2f26"},"elapsedTime":2,"msg":"[Metrics] timed async method call","time":"2020-10-16T15:01:14.933Z","v":0}
{"name":"web","hostname":"6a65d416a305","pid":112,"level":30,"userId":"5f8706265c09bc00853932f8","projectId":"5f89b292d0adac00701f2f26","msg":"allowing user read access to project","time":"2020-10-16T15:01:14.934Z","v":0}
{"name":"web","hostname":"6a65d416a305","pid":112,"level":30,"key":"mongo.ProjectGetter.getProject","args":{"0":"5f89b292d0adac00701f2f26"},"elapsedTime":12,"msg":"[Metrics] timed async method call","time":"2020-10-16T15:01:14.948Z","v":0}
{"name":"web","hostname":"6a65d416a305","pid":112,"level":30,"key":"mongo.ProjectGetter.getProject","args":{"0":"5f89b292d0adac00701f2f26"},"elapsedTime":14,"msg":"[Metrics] timed async method call","time":"2020-10-16T15:01:14.948Z","v":0}
{"name":"web","hostname":"6a65d416a305","pid":112,"level":30,"key":"mongo.ProjectGetter.getProject","args":{"0":"5f89b292d0adac00701f2f26"},"elapsedTime":13,"msg":"[Metrics] timed async method call","time":"2020-10-16T15:01:14.949Z","v":0}
{"name":"web","hostname":"6a65d416a305","pid":112,"level":30,"project_id":"5f89b292d0adac00701f2f26","active":true,"msg":"seeing if need to reactivate project","time":"2020-10-16T15:01:14.949Z","v":0}
{"name":"web","hostname":"6a65d416a305","pid":112,"level":30,"user_id":"5f8706265c09bc00853932f8","msg":"got users subscription","time":"2020-10-16T15:01:14.950Z","v":0}
{"name":"web","hostname":"6a65d416a305","pid":112,"level":30,"projectId":"5f89b292d0adac00701f2f26","userId":"5f8706265c09bc00853932f8","msg":"got user","time":"2020-10-16T15:01:14.950Z","v":0}
{"name":"web","hostname":"6a65d416a305","pid":112,"level":30,"key":"mongo.ProjectGetter.getProject","args":{"0":"5f89b292d0adac00701f2f26"},"elapsedTime":1,"msg":"[Metrics] timed async method call","time":"2020-10-16T15:01:14.952Z","v":0}
{"name":"web","hostname":"6a65d416a305","pid":112,"level":40,"offset":1644,"msg":"slow event loop","time":"2020-10-16T15:01:17.065Z","v":0}
{"name":"web","hostname":"6a65d416a305","pid":112,"level":30,"req":{"url":"/project/5f89b292d0adac00701f2f26","method":"GET","referrer":"https://server5.example.com:2025/project","remote-addr":"172.29.246.134","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"},"res":{"statusCode":200},"response-time":142336,"msg":"GET /project/5f89b292d0adac00701f2f26","time":"2020-10-16T15:01:17.067Z","v":0}
{"name":"web","hostname":"6a65d416a305","pid":112,"level":30,"req":{"url":"/system/messages","method":"GET","referrer":"https://server5.example.com:2025/project/5f89b292d0adac00701f2f26","remote-addr":"172.29.246.134","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"},"res":{"statusCode":200},"response-time":6208,"msg":"GET /system/messages","time":"2020-10-16T15:01:17.988Z","v":0}
```

#### `/var/log/sharelatex/real-time.log`

```
{"name":"real-time","hostname":"6a65d416a305","pid":116,"level":30,"session":{"cookie":{"originalMaxAge":432000000,"expires":"2020-10-20T16:12:05.758Z","secure":true,"httpOnly":true,"path":"/","sameSite":"lax"},"validationToken":"v1:Di-0","csrfSecret":"P1J48pbXbGfd9gL4F_JI3JAe","justLoggedIn":true,"passport":{"user":{"_id":"5f8706265c09bc00853932f8","first_name":"david.michaelis","last_name":"","isAdmin":true,"staffAccess":{"publisherMetrics":false,"publisherManagement":false,"institutionMetrics":false,"institutionManagement":false,"groupMetrics":false,"groupManagement":false,"adminMetrics":false},"email":"david.michaelis@example.com","referal_id":"df33716b","session_created":"2020-10-15T16:12:05.751Z","ip_address":"141.38.63.91","must_reconfirm":false}}},"client_id":"2CY2b3A_4SvfCyWryE3B","msg":"client connected","time":"2020-10-16T15:02:22.098Z","v":0}
{"name":"real-time","hostname":"6a65d416a305","pid":116,"level":30,"user_id":"5f8706265c09bc00853932f8","project_id":"5f89b292d0adac00701f2f26","client_id":"2CY2b3A_4SvfCyWryE3B","msg":"user joining project","time":"2020-10-16T15:02:22.241Z","v":0}
{"name":"real-time","hostname":"6a65d416a305","pid":116,"level":30,"project_id":"5f89b292d0adac00701f2f26","user_id":"5f8706265c09bc00853932f8","msg":"sending join project request to web","time":"2020-10-16T15:02:22.242Z","v":0}
{"name":"real-time","hostname":"6a65d416a305","pid":116,"level":50,"err":{"message":"non-success status code from web: 403","name":"Error","stack":"Error: non-success status code from web: 403\n  at Request._callback (/var/www/sharelatex/real-time/app/js/WebApiManager.js:60:17)\n  at Request.self.callback (/var/www/sharelatex/real-time/node_modules/request/request.js:185:22)\n  at Request.emit (events.js:198:13)\n  at Request.<anonymous> (/var/www/sharelatex/real-time/node_modules/request/request.js:1154:10)\n  at Request.emit (events.js:198:13)\n  at IncomingMessage.<anonymous> (/var/www/sharelatex/real-time/node_modules/request/request.js:1076:12)\n  at Object.onceWrapper (events.js:286:20)\n  at IncomingMessage.emit (events.js:203:15)\n  at endReadableNT (_stream_readable.js:1145:12)\n  at process._tickCallback (internal/process/next_tick.js:63:19)\n"},"project_id":"5f89b292d0adac00701f2f26","user_id":"5f8706265c09bc00853932f8","msg":"error accessing web api","time":"2020-10-16T15:02:22.271Z","v":0}
{"name":"real-time","hostname":"6a65d416a305","pid":116,"level":50,"client_id":"2CY2b3A_4SvfCyWryE3B","err":{"message":"non-success status code from web: 403","name":"Error","stack":"Error: non-success status code from web: 403\n  at Request._callback (/var/www/sharelatex/real-time/app/js/WebApiManager.js:60:17)\n  at Request.self.callback (/var/www/sharelatex/real-time/node_modules/request/request.js:185:22)\n  at Request.emit (events.js:198:13)\n  at Request.<anonymous> (/var/www/sharelatex/real-time/node_modules/request/request.js:1154:10)\n  at Request.emit (events.js:198:13)\n  at IncomingMessage.<anonymous> (/var/www/sharelatex/real-time/node_modules/request/request.js:1076:12)\n  at Object.onceWrapper (events.js:286:20)\n  at IncomingMessage.emit (events.js:203:15)\n  at endReadableNT (_stream_readable.js:1145:12)\n  at process._tickCallback (internal/process/next_tick.js:63:19)\n"},"msg":"server side error in joinProject","time":"2020-10-16T15:02:22.271Z","v":0}
```

#### `/var/log/sharelatex/document-updater.log` and `/var/log/sharelatex/docstore.log`

No logs in this time

### Nginx configuration

```
server {
        listen 2025 ssl default_server;
        server_tokens off;

        client_max_body_size 512M;

        # SSL Certs
        ssl_certificate /etc/ssl/certs/tisasel.example.com.cer;
        ssl_certificate_key /etc/ssl/private/tisasel.example.com.key;

        # Proxy everything to Overleaf
        location / {
        proxy_pass http://localhost:6543;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # websocket configuration
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 3m;
        proxy_send_timeout 3m;
        }
}
```

#### `conf/overleaf.rc`

```
PROJECT_NAME=overleaf

# Sharelatex container
SHARELATEX_DATA_PATH=data/sharelatex
SERVER_PRO=false
SHARELATEX_PORT=127.0.0.1:6543

# Sibling Containers
SIBLING_CONTAINERS_ENABLED=false
DOCKER_SOCKET_PATH=/var/run/docker.sock

# Mongo configuration
MONGO_ENABLED=true
MONGO_DATA_PATH=data/mongo

# Redis configuration
REDIS_ENABLED=true
REDIS_DATA_PATH=data/redis
```

#### `variables.env`

```
SHARELATEX_APP_NAME=Overleaf Example

ENABLED_LINKED_FILE_TYPES=url,project_file

# Enables Thumbnail generation using ImageMagick
ENABLE_CONVERSIONS=true

# Disables email confirmation requirement
EMAIL_CONFIRMATION_DISABLED=true

# temporary fix for LuaLaTex compiles
# see https://github.com/overleaf/overleaf/issues/695
TEXMFVAR=/var/lib/sharelatex/tmp/texmf-var

## Set for SSL via nginx-proxy
#VIRTUAL_HOST=103.112.212.22

SHARELATEX_SITE_URL=https://server5.example.com:2025
SHARELATEX_NAV_TITLE=Overleaf Example
SHARELATEX_ADMIN_EMAIL=David.Michaelis@example.com

# pasted from https://github.com/overleaf/overleaf/wiki/HTTPS-reverse-proxy-using-Nginx
SHARELATEX_SECURE_COOKIE=true
SHARELATEX_BEHIND_PROXY=true
```

#### ` cat lib/*.yml`

```
---
version: '2.2'
services:

    sharelatex:
        restart: always
        image: "${IMAGE}"
        container_name: sharelatex
        volumes:
            - "${SHARELATEX_DATA_PATH}:/var/lib/sharelatex"
        ports:
            - "${SHARELATEX_PORT:-80}:80"
        environment:
          SHARELATEX_MONGO_URL: "${MONGO_URL}"
          SHARELATEX_REDIS_HOST: "${REDIS_HOST}"
          REDIS_HOST: "${REDIS_HOST}"
        env_file: ../config/variables.env
---
version: '2.2'
services:

    mongo:
        restart: always
        image: "${MONGO_IMAGE}"
        container_name: mongo
        volumes:
            - "${MONGO_DATA_PATH}:/data/db"
        expose:
            - 27017
        healthcheck:
            test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
            interval: 10s
            timeout: 10s
            retries: 5

    sharelatex:
      depends_on:
        mongo:
          condition: service_healthy
      links:
        - mongo
---
version: '2.2'
services:

    redis:
        restart: always
        image: "${REDIS_IMAGE}"
        volumes:
            - "${REDIS_DATA_PATH}:/data"
        container_name: redis
        expose:
            - 6379

    sharelatex:
      depends_on:
        redis:
          condition: service_started
      links:
        - redis
---
version: '2.2'
services:
  sharelatex:
    volumes:
      - "${DOCKER_SOCKET_PATH}:/var/run/docker.sock"
    environment:
      DOCKER_RUNNER: 'true'
      SANDBOXED_COMPILES: 'true'
      SANDBOXED_COMPILES_SIBLING_CONTAINERS: 'true'
      SANDBOXED_COMPILES_HOST_DIR: "${SHARELATEX_DATA_PATH}/data/compiles"
      SYNCTEX_BIN_HOST_PATH: "${SHARELATEX_DATA_PATH}/bin/synctex"
```

#### `~/.docker/config.json`

```
{
        "auths": {},
        "HttpHeaders": {
                "User-Agent": "Docker-Client/19.03.12 (linux)"
        },
        "proxies": {
                "default": {
                        "httpProxy": "http://squid.example.com:8080",
                        "httpsProxy": "https://squid.example.com:8080",
                        "noProxy": "*.example.com"
                }
        }
}
```

## Analysis

There seems to be a 403 error either in the real-time and web component. I suspect that *maybe* this is because of the proxy to the outside world, which sometimes returns a 403 error, although it should be configured out for our domain. But I don't know how to peek into the response data that Overleaf is getting to either verify or falsify this.

**Comment by dvmc** [comment]
I have just discovered that with `docker ps` followed by `docker exec -it <CONTAINER_ID> /bin/bash` it is possible to move around inside the docker container. There, I have patched the error logging to show the response body, and it is indeed the external proxy, which I have had assumed that it was not configured anymore.

Inside the overleaf docker container, the proxy environment variables are still set, and the `SHARELATEX_SITE_URL` environment variable still has the initial value when overleaf was started for the first time. This is likely the root cause of the problems, therefore I am closing this issue here and move it over to overleaf/toolkit.
