### ISSUE TITLE
Self build image invite new user not working

### ISSUE THREAD

**Issue by Alice-space** [overleaf/overleaf#961]
## Steps to Reproduce

1. clone the repo and use `make build-community` then name it to `sharelatex/sharelatex:latest`
2. replace name and version in toolkit, and run `bin/up`
3. create a user and click register link

## Expected Behaviour

start set password 

## Observed Behaviour

Something went wrong, sorry.
Our staff are probably looking into this, but if it continues, please check our status page at or contact us at 

## Context

logs
```
{"name":"web","hostname":"119e13618920","pid":149,"level":50,"err":{"message":"Cannot read property 'length' of undefined","name":"TypeError","stack":"TypeError: Cannot read property 'length' of undefined\n    at eval (eval at wrap (/var/www/sharelatex/web/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:405:1150)\n    at template (eval at wrap (/var/www/sharelatex/web/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:521:7)\n    at Object.exports.renderFile (/var/www/sharelatex/web/node_modules/pug/lib/index.js:452:38)\n    at Object.exports.renderFile (/var/www/sharelatex/web/node_modules/pug/lib/index.js:442:21)\n    at View.exports.__express [as engine] (/var/www/sharelatex/web/node_modules/pug/lib/index.js:491:11)\n    at View.render (/var/www/sharelatex/web/node_modules/express/lib/view.js:135:8)\n    at tryRender (/var/www/sharelatex/web/node_modules/express/lib/application.js:640:10)\n    at Function.render (/var/www/sharelatex/web/node_modules/express/lib/application.js:592:3)\n    at ServerResponse.render (/var/www/sharelatex/web/node_modules/express/lib/response.js:1012:7)\n    at /var/www/sharelatex/web/modules/user-activate/app/src/UserActivateController.js:34:15\n    at /var/www/sharelatex/web/node_modules/@overleaf/metrics/timeAsyncMethod.js:81:23\n    at executeCallback (/var/www/sharelatex/web/node_modules/mongodb/lib/operations/execute_operation.js:70:5)\n    at handleCallback (/var/www/sharelatex/web/node_modules/mongodb/lib/utils.js:102:55)\n    at /var/www/sharelatex/web/node_modules/mongodb/lib/operations/find_one.js:29:9\n    at /var/www/sharelatex/web/node_modules/mongodb/lib/utils.js:674:5\n    at /var/www/sharelatex/web/node_modules/mongodb/lib/cursor.js:250:9\n    at handleCallback (/var/www/sharelatex/web/node_modules/mongodb/lib/core/cursor.js:31:5)\n    at nextFunction (/var/www/sharelatex/web/node_modules/mongodb/lib/core/cursor.js:864:5)\n    at /var/www/sharelatex/web/node_modules/mongodb/lib/core/cursor.js:740:7\n    at done (/var/www/sharelatex/web/node_modules/mongodb/lib/core/cursor.js:458:7)\n    at queryCallback (/var/www/sharelatex/web/node_modules/mongodb/lib/core/cursor.js:500:20)\n    at /var/www/sharelatex/web/node_modules/mongodb/lib/core/cursor.js:545:9","info":{}},"url":"/user/activate?token=7db05bf13efbb3664e11eca3bfa5bccce320b46d239a8737cc846d8d0a11ad47&user_id=615803db19ef3e00856fbea7","method":"GET","user":{"id":"6158034219ef3e00856fbe9f","email":"1900011438@pku.edu.cn"},"msg":"error passed to top level next middleware","time":"2021-10-02T07:20:19.617Z","v":0}
{"name":"web","hostname":"119e13618920","pid":149,"level":30,"req":{"url":"/user/activate?token=7db05bf13efbb3664e11eca3bfa5bccce320b46d239a8737cc846d8d0a11ad47&user_id=615803db19ef3e00856fbea7","method":"GET","remote-addr":"***","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15"},"res":{"statusCode":500},"response-time":96,"msg":"GET /user/activate?token=7db05bf13efbb3664e11eca3bfa5bccce320b46d239a8737cc846d8d0a11ad47&user_id=615803db19ef3e00856fbea7","time":"2021-10-02T07:20:19.624Z","v":0}
```

## Technical Info

* URL:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Signed in as:
* Project and/or file:

**Comment by Makiras** [comment]
I've met this problem too, u can search for
```
minlength=settings.passwordStrengthOptions.length.min,
maxlength=settings.passwordStrengthOptions.length.max
```
and remove them as workaround.

**Comment by jdleesmiller** [comment]
Thanks for reporting this. We're working on a fix.
